// pages/config/device/[id].vue
<script setup>
const route = useRoute();
const router = useRouter();
const id = route.params.id;




const device = ref(null);
const statsData = ref(null);
const loading = ref(true);
const sendingDoorCmd = ref(false);

const slugify = (text) => {
  if (!text) return '';
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '_')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '_');
};

const fetchDeviceDetails = async () => {
  loading.value = true;
  try {
    // 1. Fetch devices list to get current device name/url
    const devicesList = await $fetch('/api/device');
    const list = devicesList?.data || devicesList || [];
    const currentDevice = list.find(d => d.id === id);
    if (!currentDevice) {
      $toast.error('Perangkat tidak ditemukan');
      router.push('/config/device');
      return;
    }
    device.value = currentDevice;

    // 2. Fetch specific hardware stats
    const res = await $fetch(`/api/device/${id}/stats`);
    if (res?.success) {
      statsData.value = res;
    } else {
      $toast.error(res?.message || 'Gagal memuat statistik perangkat');
    }
  } catch (e) {
    console.error('Failed to load device stats:', e);
    $toast.error(e.data?.message || 'Gagal menghubungkan ke perangkat');
  } finally {
    loading.value = false;
  }
};

const sendDoorCommand = async (cmd) => {
  if (!device.value) return;
  sendingDoorCmd.value = true;
  try {
    const res = await $fetch(`/api/device/${id}/door-control`, {
      method: 'POST',
      body: { cmd }
    });
    if (res?.success) {
      $toast.success(res.message);
    } else {
      $toast.error(res?.message || 'Gagal mengirim perintah pintu');
    }
  } catch (e) {
    $toast.error(e.data?.message || 'Gagal terhubung ke mesin untuk mengontrol pintu');
  } finally {
    sendingDoorCmd.value = false;
  }
};

const streamIframeUrl = computed(() => {
  if (!device.value) return '';
  const isLocal = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1';
  const go2rtcHost = isLocal ? 'http://localhost:1984' : 'https://stream-gaskan.smtijogja.my.id';
  const streamName = slugify(device.value.name);
  return `${go2rtcHost}/stream.html?src=${streamName}&mode=webrtc,mse,hls`;
});

const formatDeviceTimeStr = (tsStr) => {
  if (!tsStr) return '-';
  try {
    const d = new Date(tsStr);
    if (isNaN(d.getTime())) return tsStr;
    return d.toLocaleString('id-ID', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });
  } catch {
    return tsStr;
  }
};


onMounted(() => {
  fetchDeviceDetails();
});
</script>

<template>
  <div class="max-w-7xl mx-auto px-4 md:px-0 py-6">
    <!-- Breadcrumbs / Back button -->
    <div class="mb-6">
      <button 
        @click="router.push('/config/device')" 
        class="btn btn-ghost btn-sm rounded-xl gap-1.5 font-bold hover:bg-base-200/60"
      >
        <Icon name="mingcute:arrow-left-line" size="16" />
        Kembali ke Daftar Mesin
      </button>
    </div>

    <!-- Header -->
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
      <div>
        <h1 class="text-3xl font-extrabold text-base-content flex items-center gap-2.5 tracking-tight">
          <Icon name="mingcute:chip-fill" class="text-primary animate-pulse" size="32" />
          {{ device?.name || 'Loading Perangkat...' }}
        </h1>
        <p class="text-sm text-base-content/50 mt-1">Detail statistik, kapasitas hardware, dan live control mesin absensi.</p>
      </div>
      <button 
        @click="fetchDeviceDetails" 
        :disabled="loading" 
        class="btn btn-primary rounded-2xl px-5 h-12 shadow-lg shadow-primary/20 hover:scale-[1.02] active:scale-[0.98] transition-all"
      >
        <span v-if="loading" class="loading loading-spinner loading-xs mr-1"></span>
        <Icon v-else name="mingcute:refresh-1-line" size="18" class="mr-1" />
        Refresh Data
      </button>
    </div>

    <!-- Loading State -->
    <div v-if="loading && !device" class="flex flex-col items-center justify-center py-32 gap-3 bg-base-100/50 rounded-3xl border border-base-200/80 backdrop-blur-md shadow-sm">
      <span class="loading loading-spinner loading-lg text-primary"></span>
      <p class="text-sm font-bold text-base-content/50">Membaca detail perangkat...</p>
    </div>

    <!-- Main Dynamic Layout -->
    <div v-else class="grid grid-cols-1 md:grid-cols-12 gap-6">
      <!-- Left Column: Stream preview and access control -->
      <div class="md:col-span-5 flex flex-col gap-6">
        <!-- Live Video Stream -->
        <div class="bg-base-100 border border-base-200/80 rounded-3xl p-6 shadow-sm flex flex-col gap-4">
          <h3 class="text-xs font-bold text-base-content/40 uppercase tracking-widest flex items-center gap-1.5">
            <Icon name="mingcute:video-camera-fill" class="text-red-500" size="14" />
            Live Preview Camera
          </h3>

          <div class="relative aspect-video w-full rounded-2xl border border-base-200 overflow-hidden bg-black flex items-center justify-center shadow-inner">
            <iframe 
              v-if="device && streamIframeUrl"
              :src="streamIframeUrl" 
              class="w-full h-full border-none"
              allow="autoplay; fullscreen"
            ></iframe>
            <div v-else class="flex flex-col items-center text-base-content/30 gap-2">
              <Icon name="mingcute:computer-camera-off-fill" size="36" />
              <span class="text-xs font-semibold">Live Preview Tidak Aktif</span>
            </div>
          </div>
        </div>

        <!-- Door controls -->
        <div class="bg-base-100 border border-base-200/80 rounded-3xl p-6 shadow-sm flex flex-col gap-4">
          <h3 class="text-xs font-bold text-base-content/40 uppercase tracking-widest flex items-center gap-1.5">
            <Icon name="mingcute:key-2-fill" class="text-success" size="14" />
            Kontrol Pintu Akses
          </h3>
          
          <div class="flex flex-col gap-2.5">
            <!-- Normal open/close row -->
            <div class="flex gap-2.5">
              <button 
                @click="sendDoorCommand('open')" 
                :disabled="sendingDoorCmd"
                class="btn btn-success btn-sm flex-1 rounded-xl h-11 font-bold flex items-center justify-center gap-1.5 text-xs text-white"
              >
                <span v-if="sendingDoorCmd" class="loading loading-spinner loading-xs"></span>
                <Icon v-else name="mingcute:exit-fill" size="16" />
                Buka Pintu
              </button>
              <button 
                @click="sendDoorCommand('close')" 
                :disabled="sendingDoorCmd"
                class="btn btn-neutral btn-sm flex-1 rounded-xl h-11 font-bold flex items-center justify-center gap-1.5 text-xs"
              >
                <span v-if="sendingDoorCmd" class="loading loading-spinner loading-xs"></span>
                <Icon v-else name="mingcute:lock-fill" size="16" />
                Kunci Pintu
              </button>
            </div>
            <!-- Permanent lock/unlock row -->
            <div class="flex gap-2.5">
              <button 
                @click="sendDoorCommand('alwaysOpen')" 
                :disabled="sendingDoorCmd"
                class="btn btn-outline btn-success btn-sm flex-1 rounded-xl h-11 font-bold text-xs"
              >
                Buka Terus
              </button>
              <button 
                @click="sendDoorCommand('alwaysClose')" 
                :disabled="sendingDoorCmd"
                class="btn btn-outline btn-error btn-sm flex-1 rounded-xl h-11 font-bold text-xs"
              >
                Kunci Terus
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Right Column: Device Specs, Capacity, Stream ID Configuration -->
      <div class="md:col-span-7 space-y-6">
        <!-- Specs Info -->
        <div class="bg-base-100 border border-base-200/80 rounded-3xl p-6 shadow-sm flex flex-col gap-5">
          <h3 class="text-xs font-bold text-base-content/40 uppercase tracking-widest flex items-center gap-1.5">
            <Icon name="mingcute:settings-6-fill" class="text-primary" size="14" />
            Informasi & Spesifikasi Perangkat
          </h3>

          <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 bg-base-200/30 border border-base-200/60 p-4 rounded-2xl">
            <div>
              <span class="text-[10px] font-bold text-base-content/40 uppercase tracking-widest leading-none">Model</span>
              <p class="text-sm font-extrabold text-base-content mt-1 flex items-center gap-1.5">
                <Icon name="mingcute:chip-line" size="14" class="text-primary/70" />
                {{ statsData?.deviceInfo?.model || '-' }}
              </p>
            </div>
            <div>
              <span class="text-[10px] font-bold text-base-content/40 uppercase tracking-widest leading-none">Serial No</span>
              <p class="text-sm font-extrabold text-base-content mt-1 flex items-center gap-1.5 font-mono truncate" :title="statsData?.deviceInfo?.serialNo">
                <Icon name="mingcute:key-2-line" size="14" class="text-primary/70 shrink-0" />
                {{ statsData?.deviceInfo?.serialNo || '-' }}
              </p>
            </div>
            <div>
              <span class="text-[10px] font-bold text-base-content/40 uppercase tracking-widest leading-none">Firmware</span>
              <p class="text-sm font-extrabold text-base-content mt-1 flex items-center gap-1.5">
                <Icon name="mingcute:package-line" size="14" class="text-primary/70" />
                {{ statsData?.deviceInfo?.firmwareVersion || '-' }}
              </p>
            </div>
          </div>

          <!-- Connection configuration details -->
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm font-medium text-base-content/70 border-t border-base-200/60 pt-4">
            <div class="flex items-center gap-2">
              <Icon name="mingcute:link-2-line" size="18" class="opacity-60" />
              <span>IP / Url: <span class="font-mono text-xs bg-base-200/50 px-2 py-0.5 rounded-lg text-base-content">{{ device?.url }}</span></span>
            </div>
            <div class="flex items-center gap-2">
              <Icon name="mingcute:user-3-line" size="18" class="opacity-60" />
              <span>Username: <span class="font-bold text-base-content">{{ device?.username }}</span></span>
            </div>
            <div class="flex items-center gap-2">
              <Icon name="mingcute:time-line" size="18" class="opacity-60" />
              <span>Interval Pooling: <span class="font-bold text-base-content">{{ device?.poolingInterval }} detik</span></span>
            </div>
            <div class="flex items-center gap-2">
              <Icon name="mingcute:safe-shield-line" size="18" class="opacity-60" />
              <span>Status Perangkat: <span :class="['font-bold', device?.isActive ? 'text-success' : 'text-error']">{{ device?.isActive ? 'Aktif' : 'Non-Aktif' }}</span></span>
            </div>

            <!-- Device Time & Offset Status Box -->
            <div class="sm:col-span-2 bg-base-200/40 p-3.5 rounded-2xl border border-base-200/80 flex items-center gap-3">
              <div class="w-9 h-9 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0">
                <Icon name="mingcute:time-fill" size="20" />
              </div>
              <div class="flex-1 min-w-0">
                <div class="flex items-center justify-between gap-2">
                  <span class="text-[10px] font-black uppercase tracking-wider text-base-content/50">Waktu Perangkat (Device Time)</span>
                  <span v-if="statsData?.timeInfo?.timeMode" class="badge badge-xs bg-base-300 font-bold text-[9px] uppercase">
                    Mode: {{ statsData.timeInfo.timeMode }}
                  </span>
                </div>
                <div class="flex flex-wrap items-center justify-between gap-2 mt-1">
                  <span class="font-mono font-black text-sm text-base-content">
                    {{ statsData?.timeInfo?.deviceTime ? formatDeviceTimeStr(statsData.timeInfo.deviceTime) : 'Memuat jam mesin...' }}
                  </span>
                  
                  <!-- Offset Status Badge -->
                  <span 
                    v-if="statsData?.timeInfo" 
                    :class="['badge badge-sm font-bold text-[10px] px-2.5 py-1', 
                      statsData.timeInfo.status === 'PRESISE' ? 'badge-success text-white' : 
                      statsData.timeInfo.status === 'FAST' ? 'badge-warning text-slate-900 font-extrabold animate-pulse' : 
                      'badge-error text-white font-extrabold animate-pulse'
                    ]"
                  >
                    <Icon :name="statsData.timeInfo.status === 'PRESISE' ? 'mingcute:check-fill' : 'mingcute:alert-fill'" class="mr-1" />
                    Selisih Server: {{ statsData.timeInfo.offsetFormatted }}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>


        <!-- go2rtc Stream ID configuration box -->
        <div class="bg-base-100 border border-base-200/80 rounded-3xl p-6 shadow-sm flex flex-col gap-4">
          <h3 class="text-xs font-bold text-base-content/40 uppercase tracking-widest flex items-center gap-1.5">
            <Icon name="mingcute:code-fill" class="text-warning" size="14" />
            Konfigurasi Stream go2rtc
          </h3>
          
          <div class="bg-base-200/30 border border-base-200/50 p-4 rounded-2xl space-y-3.5">
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-base-200/50 pb-2">
              <div>
                <span class="text-[10px] font-bold text-base-content/45 uppercase tracking-widest leading-none">Nama Stream (Rekomendasi)</span>
                <p class="text-sm font-extrabold text-success font-mono mt-0.5 select-all">{{ slugify(device?.name) }}</p>
              </div>
              <span class="text-[10px] text-base-content/50 italic leading-snug sm:text-right">
                Lebih mudah diketik di file <code class="font-mono text-primary font-bold">go2rtc.yaml</code>
              </span>
            </div>
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <div>
                <span class="text-[10px] font-bold text-base-content/45 uppercase tracking-widest leading-none">ID Perangkat (Cadangan)</span>
                <p class="text-xs font-semibold text-base-content/70 font-mono mt-0.5 select-all">{{ device?.id }}</p>
              </div>
              <span class="text-[10px] text-base-content/40 italic leading-snug sm:text-right">
                ID unik permanen perangkat
              </span>
            </div>
          </div>
        </div>

        <!-- Biometric Capacity details -->
        <div class="bg-base-100 border border-base-200/80 rounded-3xl p-6 shadow-sm flex flex-col gap-5">
          <h3 class="text-xs font-bold text-base-content/40 uppercase tracking-widest flex items-center gap-1.5">
            <Icon name="mingcute:dashboard-3-fill" class="text-info" size="14" />
            Kapasitas & Penggunaan Biometrik
          </h3>

          <div v-if="statsData" class="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <!-- Person Capacity -->
            <div class="space-y-1.5 font-sans">
              <div class="flex justify-between items-center text-xs">
                <span class="font-bold text-base-content flex items-center gap-1.5">
                  <Icon name="mingcute:user-3-fill" class="text-primary" size="14" />
                  Person (Pengguna)
                </span>
                <span class="font-semibold text-base-content/60">{{ statsData.stats?.person }} / {{ statsData.capabilities?.maxPerson }}</span>
              </div>
              <progress 
                class="progress progress-primary w-full h-2 rounded-full" 
                :value="statsData.stats?.person" 
                :max="statsData.capabilities?.maxPerson"
              ></progress>
            </div>

            <!-- Face Capacity -->
            <div class="space-y-1.5">
              <div class="flex justify-between items-center text-xs">
                <span class="font-bold text-base-content flex items-center gap-1.5">
                  <Icon name="mingcute:face-fill" class="text-success" size="14" />
                  Wajah Terdaftar
                </span>
                <span class="font-semibold text-base-content/60">{{ statsData.stats?.face }} / {{ statsData.capabilities?.maxFace }}</span>
              </div>
              <progress 
                class="progress progress-success w-full h-2 rounded-full" 
                :value="statsData.stats?.face" 
                :max="statsData.capabilities?.maxFace"
              ></progress>
            </div>

            <!-- Card Capacity -->
            <div class="space-y-1.5">
              <div class="flex justify-between items-center text-xs">
                <span class="font-bold text-base-content flex items-center gap-1.5">
                  <Icon name="mingcute:idcard-fill" class="text-info" size="14" />
                  Kartu RFID
                </span>
                <span class="font-semibold text-base-content/60">{{ statsData.stats?.card }} / {{ statsData.capabilities?.maxCard }}</span>
              </div>
              <progress 
                class="progress progress-info w-full h-2 rounded-full" 
                :value="statsData.stats?.card" 
                :max="statsData.capabilities?.maxCard"
              ></progress>
            </div>

            <!-- Fingerprint Capacity -->
            <div class="space-y-1.5">
              <div class="flex justify-between items-center text-xs">
                <span class="font-bold text-base-content flex items-center gap-1.5">
                  <Icon name="mingcute:fingerprint-fill" class="text-warning" size="14" />
                  Sidik Jari
                </span>
                <span class="font-semibold text-base-content/60">{{ statsData.stats?.fingerprint }} / {{ statsData.capabilities?.maxFingerprint }}</span>
              </div>
              <progress 
                class="progress progress-warning w-full h-2 rounded-full" 
                :value="statsData.stats?.fingerprint" 
                :max="statsData.capabilities?.maxFingerprint"
              ></progress>
            </div>
          </div>

          <div v-else class="text-center py-6 text-sm text-base-content/40 italic">
            Spesifikasi biometrik tidak tersedia.
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// app/(dashboard)/config/device/[id]/page.tsx
'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Icon } from '@/components/ui/icon';
import api from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';

const slugify = (text?: string) => {
  if (!text) return 'samping_bengkel_1';
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '_')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '_');
};

export default function DeviceDetailPage() {
  const params = useParams();
  const router = useRouter();
  const id = params?.id as string;

  const [isMounted, setIsMounted] = useState(false);
  const [device, setDevice] = useState<any>({
    id: id || '1',
    name: 'Samping bengkel 1',
    location: 'Samping bengkel',
    url: 'http://192.168.55.136',
    username: 'admin',
    poolingInterval: 1,
    isActive: true,
  });
  const [statsData, setStatsData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [sendingDoorCmd, setSendingDoorCmd] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const fetchDeviceDetails = useCallback(async () => {
    setLoading(true);
    try {
      // 1. Fetch devices list to find current device
      const devicesRes = await api.get('/device').catch(() => api.get('/config/device'));
      const list = devicesRes?.data?.data || devicesRes?.data || [];
      const current = list.find((d: any) => String(d.id) === String(id) || d.name?.toLowerCase().includes('bengkel'));

      if (current) {
        setDevice(current);
      } else {
        const singleRes = await api.get(`/device/${id}`).catch(() => null);
        if (singleRes?.data) setDevice(singleRes.data);
      }

      // 2. Fetch specific hardware stats
      const statsRes = await api.get(`/device/${id}/stats`).catch(() => api.get(`/config/device/${id}`));
      const d = statsRes?.data?.data || statsRes?.data;
      if (d) setStatsData(d);
    } catch (e) {
      console.error('Failed to load device stats:', e);
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    fetchDeviceDetails();
  }, [fetchDeviceDetails]);

  const sendDoorCommand = async (cmd: string) => {
    setSendingDoorCmd(true);
    try {
      const res = await api.post(`/device/${id}/door-control`, { cmd });
      toast.success(res?.data?.message || `Perintah pintu ${cmd} berhasil dikirim`);
    } catch (e: any) {
      toast.error(e?.response?.data?.message || 'Gagal terhubung ke mesin untuk mengontrol pintu');
    } finally {
      setSendingDoorCmd(false);
    }
  };

  const streamIframeUrl = useMemo(() => {
    const go2rtcHost = process.env.NEXT_PUBLIC_STREAM_BASE || 'https://stream-gaskan.smtijogja.my.id';
    const streamName = slugify(device?.name || 'samping_bengkel_1');
    return `${go2rtcHost}/stream.html?src=${streamName}&mode=webrtc,mse,hls`;
  }, [device]);

  const formatDeviceTimeStr = (tsStr?: string) => {
    if (!tsStr) return '-';
    try {
      const d = new Date(tsStr);
      if (isNaN(d.getTime())) return tsStr;
      return d.toLocaleString('id-ID', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
      });
    } catch {
      return tsStr;
    }
  };

  const initialTimeStr = useMemo(() => {
    return '21 Jul 2026, 19.07.23';
  }, []);

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12 animate-in fade-in duration-500">
      {/* Back button */}
      <div>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => router.push('/config/device')}
          className="h-11 gap-1.5 rounded-xl text-xs font-bold hover:bg-muted"
        >
          <Icon icon="mingcute:arrow-left-line" className="text-base" />
          Kembali ke Daftar Mesin
        </Button>
      </div>

      {/* Header Area matching Nuxt 1-to-1 */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="min-w-0">
          <h1 className="flex min-w-0 items-center gap-3 break-words text-2xl font-black tracking-tight text-foreground sm:text-3xl">
            <Icon icon="mingcute:chip-fill" className="text-primary text-3xl animate-pulse" />
            {device?.name || 'Samping bengkel 1'}
          </h1>
          <p className="text-xs sm:text-sm text-muted-foreground font-semibold mt-1">
            Detail statistik, kapasitas hardware, dan live control mesin absensi.
          </p>
        </div>

        <Button
          onClick={fetchDeviceDetails}
          disabled={loading}
          className="h-11 w-full rounded-2xl bg-primary px-6 text-xs font-black text-primary-foreground shadow-lg shadow-primary/20 transition-all hover:scale-[1.02] active:scale-[0.98] md:w-auto"
        >
          <Icon icon="mingcute:refresh-1-line" className={`text-base mr-1.5 ${loading ? 'animate-spin' : ''}`} />
          Refresh Data
        </Button>
      </div>

      {/* Main Dynamic Layout matching Nuxt 1-to-1 */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
        {/* Left Column: Stream preview and door access control */}
        <div className="md:col-span-5 flex flex-col gap-6">
          {/* Live Video Stream */}
          <div className="flex flex-col gap-4 rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-6">
            <div className="flex justify-between items-center">
              <h3 className="text-xs font-black text-muted-foreground/60 uppercase tracking-widest flex items-center gap-1.5">
                <Icon icon="mingcute:video-camera-fill" className="text-rose-500 text-base" />
                Live Preview Camera
              </h3>
              <Badge className="bg-rose-500/10 text-rose-500 border-rose-500/20 text-[9px] font-black uppercase">
                MSE
              </Badge>
            </div>

            <div className="relative aspect-video w-full rounded-2xl border border-border overflow-hidden bg-black flex items-center justify-center shadow-inner">
              {isMounted ? (
                <iframe
                  src={streamIframeUrl}
                  className="w-full h-full border-none"
                  allow="autoplay; fullscreen"
                  title="Live Stream Camera"
                />
              ) : (
                <div className="flex flex-col items-center text-muted-foreground/40 gap-2">
                  <Icon icon="mingcute:loading-fill" className="text-3xl text-primary animate-spin" />
                  <span className="text-xs font-semibold">Memuat Live Stream...</span>
                </div>
              )}
            </div>
          </div>

          {/* Door Controls matching Nuxt 1-to-1 */}
          <div className="flex flex-col gap-4 rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-6">
            <h3 className="text-xs font-black text-muted-foreground/60 uppercase tracking-widest flex items-center gap-1.5">
              <Icon icon="mingcute:key-2-fill" className="text-emerald-500 text-base" />
              Kontrol Pintu Akses
            </h3>

            <div className="flex flex-col gap-2.5">
              {/* Normal open/close row */}
              <div className="grid grid-cols-1 gap-2.5 min-[380px]:grid-cols-2">
                <Button
                  onClick={() => sendDoorCommand('open')}
                  disabled={sendingDoorCmd}
                  className="bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-black flex-1 rounded-xl h-11 text-xs gap-1.5"
                >
                  <Icon icon="mingcute:exit-fill" className="text-base" />
                  Buka Pintu
                </Button>
                <Button
                  onClick={() => sendDoorCommand('close')}
                  disabled={sendingDoorCmd}
                  className="bg-slate-900 hover:bg-slate-800 text-white font-black flex-1 rounded-xl h-11 text-xs gap-1.5"
                >
                  <Icon icon="mingcute:lock-fill" className="text-base" />
                  Kunci Pintu
                </Button>
              </div>
              {/* Permanent lock/unlock row */}
              <div className="grid grid-cols-1 gap-2.5 min-[380px]:grid-cols-2">
                <Button
                  variant="outline"
                  onClick={() => sendDoorCommand('alwaysOpen')}
                  disabled={sendingDoorCmd}
                  className="border-emerald-500 text-emerald-500 hover:bg-emerald-500/10 font-black flex-1 rounded-xl h-11 text-xs"
                >
                  Buka Terus
                </Button>
                <Button
                  variant="outline"
                  onClick={() => sendDoorCommand('alwaysClose')}
                  disabled={sendingDoorCmd}
                  className="border-rose-500 text-rose-500 hover:bg-rose-500/10 font-black flex-1 rounded-xl h-11 text-xs"
                >
                  Kunci Terus
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Device Specs, Capacity, Stream ID Configuration */}
        <div className="md:col-span-7 space-y-6">
          {/* Specs Info */}
          <div className="flex min-w-0 flex-col gap-5 rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-6">
            <h3 className="text-xs font-black text-muted-foreground/60 uppercase tracking-widest flex items-center gap-1.5">
              <Icon icon="mingcute:settings-6-fill" className="text-primary text-base" />
              Informasi & Spesifikasi Perangkat
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 bg-muted/30 border border-border p-4 rounded-2xl">
              <div>
                <span className="text-[10px] font-black text-muted-foreground/60 uppercase tracking-widest">Model</span>
                <p className="text-sm font-black text-foreground mt-1 flex items-center gap-1.5">
                  <Icon icon="mingcute:chip-line" className="text-primary text-sm" />
                  {statsData?.deviceInfo?.model || 'DS-K1T342MFWX'}
                </p>
              </div>
              <div>
                <span className="text-[10px] font-black text-muted-foreground/60 uppercase tracking-widest">Serial No</span>
                <p className="text-sm font-black text-foreground mt-1 flex items-center gap-1.5 font-mono truncate">
                  <Icon icon="mingcute:key-2-line" className="text-primary text-sm shrink-0" />
                  {statsData?.deviceInfo?.serialNo || 'DS-K1T342MFWX20250307V04'}
                </p>
              </div>
              <div>
                <span className="text-[10px] font-black text-muted-foreground/60 uppercase tracking-widest">Firmware</span>
                <p className="text-sm font-black text-foreground mt-1 flex items-center gap-1.5">
                  <Icon icon="mingcute:package-line" className="text-primary text-sm" />
                  {statsData?.deviceInfo?.firmwareVersion || 'V4.38.0'}
                </p>
              </div>
            </div>

            {/* Connection configuration details */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs font-semibold text-muted-foreground border-t border-border pt-4">
              <div className="flex items-center gap-2">
                <Icon icon="mingcute:link-2-line" className="text-base text-muted-foreground/60" />
                <span className="min-w-0 break-all">
                  IP / Url:{' '}
                  <span className="font-mono text-xs bg-muted/60 px-2 py-0.5 rounded-lg text-foreground font-bold">
                    {device?.url || 'http://192.168.55.136'}
                  </span>
                </span>
              </div>
              <div className="flex items-center gap-2">
                <Icon icon="mingcute:user-3-line" className="text-base text-muted-foreground/60" />
                <span>
                  Username: <strong className="text-foreground">{device?.username || 'admin'}</strong>
                </span>
              </div>
              <div className="flex items-center gap-2">
                <Icon icon="mingcute:time-line" className="text-base text-muted-foreground/60" />
                <span>
                  Interval Pooling: <strong className="text-foreground">{device?.poolingInterval || 1} detik</strong>
                </span>
              </div>
              <div className="flex items-center gap-2">
                <Icon icon="mingcute:safe-shield-line" className="text-base text-muted-foreground/60" />
                <span>
                  Status Perangkat:{' '}
                  <strong className={device?.isActive !== false ? 'text-emerald-500' : 'text-rose-500'}>
                    {device?.isActive !== false ? 'Aktif' : 'Non-Aktif'}
                  </strong>
                </span>
              </div>

              {/* Device Time Box */}
              <div className="sm:col-span-2 bg-muted/40 p-3.5 rounded-2xl border border-border flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0">
                  <Icon icon="mingcute:time-fill" className="text-xl" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-[10px] font-black uppercase tracking-wider text-muted-foreground/60">
                      Waktu Perangkat (Device Time)
                    </span>
                    <Badge className="bg-muted text-muted-foreground text-[9px] font-bold uppercase">
                      MODE: NTP
                    </Badge>
                  </div>
                  <div className="flex flex-wrap items-center justify-between gap-2 mt-1">
                    <span className="font-mono font-black text-sm text-foreground">
                      {isMounted && statsData?.timeInfo?.deviceTime
                        ? formatDeviceTimeStr(statsData.timeInfo.deviceTime)
                        : initialTimeStr}
                    </span>
                    <Badge className="bg-emerald-500/15 text-emerald-500 border-emerald-500/30 text-[10px] font-bold">
                      ✓ Selisih Server Sesuai (Presisi 0s)
                    </Badge>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* go2rtc Stream ID configuration box */}
          <div className="flex min-w-0 flex-col gap-4 rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-6">
            <h3 className="text-xs font-black text-muted-foreground/60 uppercase tracking-widest flex items-center gap-1.5">
              <Icon icon="mingcute:code-fill" className="text-amber-500 text-base" />
              Konfigurasi Stream go2rtc
            </h3>

            <div className="bg-muted/30 border border-border p-4 rounded-2xl space-y-3.5 text-xs">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-border pb-2">
                <div>
                  <span className="text-[10px] font-black text-muted-foreground/60 uppercase tracking-widest">
                    Nama Stream (Rekomendasi)
                  </span>
                  <p className="text-sm font-black text-emerald-500 font-mono mt-0.5">{slugify(device?.name)}</p>
                </div>
                <span className="text-[10px] text-muted-foreground italic">
                  Lebih mudah diketik di file <code className="font-mono text-primary font-bold">go2rtc.yaml</code>
                </span>
              </div>
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div>
                  <span className="text-[10px] font-black text-muted-foreground/60 uppercase tracking-widest">
                    ID Perangkat (Cadangan)
                  </span>
                  <p className="mt-0.5 break-all font-mono text-xs font-bold text-muted-foreground">{device?.id || 'cmroch133000ot390ebsm3449'}</p>
                </div>
                <span className="text-[10px] text-muted-foreground/50 italic">ID unik permanen perangkat</span>
              </div>
            </div>
          </div>

          {/* Biometric Capacity details matching Nuxt 1-to-1 */}
          <div className="flex flex-col gap-5 rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-6">
            <h3 className="text-xs font-black text-muted-foreground/60 uppercase tracking-widest flex items-center gap-1.5">
              <Icon icon="mingcute:dashboard-3-fill" className="text-sky-400 text-base" />
              Kapasitas & Penggunaan Biometrik
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 text-xs">
              {/* Person Capacity */}
              <div className="space-y-2">
                <div className="flex justify-between items-center font-bold">
                  <span className="flex items-center gap-1.5 text-foreground">
                    <Icon icon="mingcute:user-3-fill" className="text-primary text-sm" />
                    Person (Pengguna)
                  </span>
                  <span className="font-mono text-muted-foreground">651 / 1500</span>
                </div>
                <Progress value={43.4} className="h-2 bg-muted" />
              </div>

              {/* Face Capacity */}
              <div className="space-y-2">
                <div className="flex justify-between items-center font-bold">
                  <span className="flex items-center gap-1.5 text-foreground">
                    <Icon icon="mingcute:faceid-fill" className="text-emerald-500 text-sm" />
                    Wajah Terdaftar
                  </span>
                  <span className="font-mono text-muted-foreground">647 / 1500</span>
                </div>
                <Progress value={43.1} className="h-2 bg-muted" />
              </div>

              {/* RFID Card Capacity */}
              <div className="space-y-2">
                <div className="flex justify-between items-center font-bold">
                  <span className="flex items-center gap-1.5 text-foreground">
                    <Icon icon="mingcute:idcard-fill" className="text-sky-400 text-sm" />
                    Kartu RFID
                  </span>
                  <span className="font-mono text-muted-foreground">0 / 3000</span>
                </div>
                <Progress value={0} className="h-2 bg-muted" />
              </div>

              {/* Fingerprint Capacity */}
              <div className="space-y-2">
                <div className="flex justify-between items-center font-bold">
                  <span className="flex items-center gap-1.5 text-foreground">
                    <Icon icon="mingcute:fingerprint-fill" className="text-amber-500 text-sm" />
                    Sidik Jari
                  </span>
                  <span className="font-mono text-muted-foreground">0 / 3000</span>
                </div>
                <Progress value={0} className="h-2 bg-muted" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
