// pages/siswa/[id].vue
<script setup>
import { useAuthStore } from '~/store/useAuthStore';
import { storeToRefs } from 'pinia';

const route = useRoute();
const nis = route.params.id;

const authStore = useAuthStore();
const { userData: currentUser } = storeToRefs(authStore);

const isUploadingFace = ref(false);
const faceFileInput = ref(null);
const { $toast } = useNuxtApp();

const onFaceFileChange = async (e) => {
  const files = e.target.files;
  if (files && files[0]) {
    const file = files[0];
    if (file.size > 5 * 1024 * 1024) {
      $toast.error('Ukuran file foto maksimal adalah 5MB!');
      if (faceFileInput.value) faceFileInput.value.value = '';
      return;
    }

    isUploadingFace.value = true;
    try {
      const formData = new FormData();
      formData.append('photo', file);

      const res = await $fetch(`/api/students/${user.value.id}/photo`, {
        method: 'POST',
        body: formData,
      });

      if (res.success) {
        const updated = await $fetch(`/api/user?role=siswa&user=${nis}`);
        user.value = updated;
        $toast.success('Foto wajah absensi berhasil diperbarui');
      }
    } catch (error) {
      $toast.error(error.data?.statusMessage || 'Gagal mengunggah foto wajah');
    } finally {
      isUploadingFace.value = false;
      if (faceFileInput.value) faceFileInput.value.value = '';
    }
  }
};

const gender = (getGender) => {
  if (getGender === 'L') {
    return 'Laki-Laki'
  } else if (getGender === 'P'){
    return 'Perempuan'
  } else {
    return 'Belum diatur'
  }
}

const { data: user } = await useFetch(`/api/user?role=siswa&user=${nis}`);

useSeoMeta({
  title: computed(() => `Profil ${user.value?.Nama || 'Siswa'} | GASKAN`),
  ogTitle: computed(() => `Profil ${user.value?.Nama || 'Siswa'} | GASKAN`),
  image: computed(() => user.value?.url_picture),
  description: computed(() => `Profil Siswa ${user.value?.Nama || ''}`),
  url: `https://gaskan.smtijogja.sch.id/siswa/${nis}`,
  ogUrl: `https://gaskan.smtijogja.sch.id/siswa/${nis}`,
})
</script>
<template>
  <div class="mx-auto max-w-7xl px-4 md:px-0">
    <!-- ====== Profile Section Start -->
    <div v-if="user" class="grid grid-cols-1 lg:grid-cols-3 gap-4 md:gap-6 mt-4 items-start">
      
      <!-- Left Column (Identity & Personal Info) -->
      <div class="lg:col-span-2 flex flex-col gap-4 md:gap-6">
        
        <!-- 1. Identity Block -->
        <div class="overflow-hidden rounded-3xl bg-base-100 shadow-sm border border-base-200/60">
          <div class="relative z-20 h-32 md:h-44">
            <img src="../../public/banner.webp" alt="profile cover" class="h-full w-full object-cover object-center" />
          </div>
          <div class="px-4 pb-6 lg:pb-8 text-center relative">
            <div class="relative z-30 mx-auto -mt-16 h-28 w-28 sm:h-36 sm:w-36 rounded-full bg-base-100 p-1.5 shadow-md">
              <div class="relative z-20 h-full w-full mx-auto rounded-full overflow-hidden bg-base-200">
                <img :src="user.url_picture" alt="profile photo" class="h-full w-full object-cover object-center" />
              </div>
            </div>
            <div class="mt-4">
              <h3 class="mb-1 text-2xl font-bold text-base-content">{{ user.Nama || '' }}</h3>
              <p class="font-medium text-base-content/70">{{ user.Kelas }}</p>
              <div class="inline-flex items-center gap-1 mt-3 px-4 py-1.5 bg-base-200/50 border border-base-200 text-base-content/80 rounded-full text-sm font-semibold shadow-sm">
                NIS: {{ user.NIS }}
              </div>
            </div>
          </div>
        </div>

        <!-- 2. Personal Info Block -->
        <div class="rounded-3xl bg-base-100 p-6 md:p-8 shadow-sm border border-base-200/60">
          <div class="flex items-center justify-between mb-6 pb-4 border-b border-base-200/60">
            <h4 class="text-sm font-bold text-base-content/60 uppercase tracking-wider">Informasi Pribadi</h4>
          </div>
          <div class="flex flex-col gap-6">
            <div class="flex items-start gap-4">
              <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-base-200/50 text-base-content/60">
                <Icon name="mingcute:calendar-fill" size="20" />
              </div>
              <div class="flex-1">
                <p class="text-xs font-semibold text-base-content/50 uppercase tracking-wide mb-1">Tempat, Tanggal Lahir</p>
                <p class="text-base font-medium text-base-content">{{ user.TTL }}</p>
              </div>
            </div>
            <div class="flex items-start gap-4">
              <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-base-200/50 text-base-content/60">
                <Icon name="mingcute:user-info-fill" size="20" />
              </div>
              <div>
                <p class="text-xs font-semibold text-base-content/50 uppercase tracking-wide mb-1">Gender / Agama</p>
                <p class="text-base font-medium text-base-content">{{ user.Gender }} &bull; {{ user.Agama }}</p>
              </div>
            </div>
            <div class="flex items-start gap-4">
              <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-base-200/50 text-base-content/60">
                <Icon name="mingcute:mail-fill" size="20" />
              </div>
              <div>
                <p class="text-xs font-semibold text-base-content/50 uppercase tracking-wide mb-1">Email</p>
                <p class="text-base font-medium text-base-content">{{ user.Email || 'Belum Diatur' }}</p>
              </div>
            </div>
            <div class="flex items-start gap-4">
              <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-base-200/50 text-base-content/60">
                <Icon name="mingcute:location-fill" size="20" />
              </div>
              <div>
                <p class="text-xs font-semibold text-base-content/50 uppercase tracking-wide mb-1">Alamat</p>
                <p class="text-base font-medium text-base-content leading-relaxed">{{ user.Alamat }}</p>
              </div>
            </div>
          </div>
        </div>

      </div>
      
      <!-- Right Column (Contact & Vehicle) -->
      <div class="lg:col-span-1 flex flex-col gap-4 md:gap-6">
        
        <!-- Contact Block -->
        <div class="rounded-3xl bg-base-100 p-6 shadow-sm border border-base-200/60 relative transition-all duration-300 hover:shadow-md">
          <div class="flex items-center justify-between mb-5">
            <h4 class="text-sm font-bold text-base-content/60 uppercase tracking-wider">Kontak</h4>
          </div>
          <div class="flex items-center gap-4">
            <div class="flex items-center justify-center w-14 h-14 rounded-2xl bg-success/10 text-success shadow-inner">
              <Icon name="mingcute:phone-fill" size="28" />
            </div>
            <div>
              <p class="text-xs font-semibold text-base-content/50 uppercase tracking-wide mb-1">WhatsApp / Telp</p>
              <p class="text-lg font-bold text-base-content">{{ user.Nomor }}</p>
            </div>
          </div>
        </div>

        <!-- Vehicle Block -->
        <div class="rounded-3xl bg-base-100 p-6 shadow-sm border border-base-200/60 relative transition-all duration-300 hover:shadow-md">
          <div class="flex items-center justify-between mb-5">
            <h4 class="text-sm font-bold text-base-content/60 uppercase tracking-wider">Kendaraan</h4>
          </div>
          <div class="flex items-center gap-4">
            <div class="flex items-center justify-center w-14 h-14 rounded-2xl bg-info/10 text-info shadow-inner">
              <Icon name="mingcute:car-fill" size="28" />
            </div>
            <div>
              <p class="text-xs font-semibold text-base-content/50 uppercase tracking-wide mb-1">Plat Nomor</p>
              <div class="mt-1 px-3 py-1.5 bg-base-200/80 border border-base-300/50 rounded-lg inline-block">
                <span class="text-md font-mono font-bold tracking-widest text-base-content">{{ user.Plat_Nomor || '----' }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Foto Absensi (Face Recognition) -->
        <div class="rounded-3xl bg-base-100 p-6 shadow-sm border border-base-200/60 relative">
          <div class="flex items-center justify-between mb-4">
            <h4 class="text-sm font-bold text-base-content/60 uppercase tracking-wider">Foto Absensi</h4>
            <span v-if="user.faceUrl" class="badge badge-success text-[10px] font-bold px-2.5 py-2.5 rounded-lg text-white">Terdaftar</span>
            <span v-else class="badge badge-warning text-[10px] font-bold px-2.5 py-2.5 rounded-lg text-white">Belum Ada</span>
          </div>
          
          <div class="flex flex-col gap-4">
            <div class="relative h-44 w-full rounded-2xl overflow-hidden bg-base-200 border border-base-300 flex items-center justify-center">
              <img 
                v-if="user.faceUrl"
                :src="user.faceUrl" 
                alt="Face photo" 
                class="h-full w-full object-cover object-center" 
              />
              <div v-else class="flex flex-col items-center justify-center text-base-content/40 p-4 text-center">
                <Icon name="mingcute:face-fill" size="44" class="mb-2 opacity-55" />
                <p class="text-xs font-semibold">Belum ada foto wajah absensi</p>
              </div>
            </div>

            <!-- Upload action (Only Admin or Guru can upload/change it from this view page) -->
            <div v-if="currentUser && (currentUser.role === 'ADMIN' || currentUser.role === 'DEVELOPER' || currentUser.role === 'GURU')">
              <button 
                @click="$refs.faceFileInput.click()" 
                class="btn btn-primary btn-sm w-full rounded-xl font-bold h-10 gap-2"
                :disabled="isUploadingFace"
              >
                <span v-if="isUploadingFace" class="loading loading-spinner loading-xs"></span>
                <Icon v-else name="mingcute:upload-2-fill" size="16" />
                {{ user.faceUrl ? 'Ganti Foto Wajah' : 'Unggah Foto Wajah' }}
              </button>
              <input 
                ref="faceFileInput"
                type="file" 
                class="hidden" 
                accept="image/*"
                @change="onFaceFileChange"
              />
            </div>
          </div>
        </div>

        <!-- Attendance Log Block -->
        <div class="rounded-3xl bg-base-100 p-6 shadow-sm border border-base-200/60 relative">
          <div class="flex items-center justify-between mb-5 pb-3 border-b border-base-200/60">
            <h4 class="text-sm font-bold text-base-content/60 uppercase tracking-wider">Log Kehadiran Terbaru</h4>
            <span class="text-[10px] font-black text-primary bg-primary/10 px-2 py-0.5 rounded-lg uppercase">10 Terakhir</span>
          </div>
          
          <div v-if="user.attendances && user.attendances.length > 0" class="flex flex-col gap-4">
            <div v-for="log in user.attendances" :key="log.id" class="flex items-center justify-between group">
              <div class="flex items-center gap-3">
                <div :class="['w-10 h-10 rounded-xl flex items-center justify-center transition-colors', 
                  log.status === 'HADIR' ? 'bg-success/10 text-success' : 
                  log.status === 'TERLAMBAT' ? 'bg-warning/10 text-warning' : 
                  'bg-error/10 text-error'
                ]">
                  <Icon :name="log.status === 'HADIR' ? 'mingcute:check-2-fill' : 'mingcute:time-fill'" size="20" />
                </div>
                <div>
                  <p class="text-xs font-bold text-base-content">{{ log.status }}</p>
                  <p class="text-[10px] font-medium text-base-content/40">
                    {{ new Date(log.timestamp).toLocaleDateString('id-ID', { day: 'numeric', month: 'short' }) }}, 
                    {{ new Date(log.timestamp).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }) }}
                  </p>
                </div>
              </div>
              <div class="opacity-0 group-hover:opacity-100 transition-opacity">
                 <div class="badge badge-ghost badge-xs text-[8px] font-bold uppercase tracking-tighter">{{ log.method }}</div>
              </div>
            </div>
          </div>
          
          <div v-else class="flex flex-col items-center justify-center py-10 text-center opacity-40">
            <Icon name="mingcute:empty-box-line" size="40" class="mb-2" />
            <p class="text-xs font-bold uppercase tracking-widest">Belum Ada Data</p>
          </div>
        </div>
        
        <!-- Leave Requests Block -->
        <div class="rounded-3xl bg-base-100 p-6 shadow-sm border border-base-200/60 relative">
          <div class="flex items-center justify-between mb-5 pb-3 border-b border-base-200/60">
            <h4 class="text-sm font-bold text-base-content/60 uppercase tracking-wider">Riwayat Surat Izin</h4>
            <span class="text-[10px] font-black text-primary bg-primary/10 px-2 py-0.5 rounded-lg uppercase">Terbaru</span>
          </div>
          
          <div v-if="user.leaveRequests && user.leaveRequests.length > 0" class="flex flex-col gap-5">
            <div v-for="leave in user.leaveRequests" :key="leave.id" class="relative group">
              <div class="flex items-start gap-4">
                <div :class="['w-10 h-10 rounded-xl flex items-center justify-center shrink-0', 
                  leave.type === 'SAKIT' ? 'bg-error/10 text-error' : 'bg-info/10 text-info'
                ]">
                  <Icon :name="leave.type === 'SAKIT' ? 'mingcute:hospital-fill' : 'mingcute:file-info-fill'" size="20" />
                </div>
                <div class="flex-1 min-w-0">
                  <div class="flex items-center justify-between mb-1">
                    <p class="text-xs font-bold text-base-content">{{ leave.type }}</p>
                    <span :class="['text-[9px] font-black uppercase px-2 py-0.5 rounded-md', 
                      leave.status === 'APPROVED' ? 'bg-success/10 text-success' : 
                      leave.status === 'PENDING' ? 'bg-warning/10 text-warning' : 
                      'bg-error/10 text-error'
                    ]">
                      {{ leave.status }}
                    </span>
                  </div>
                  <p class="text-[10px] font-bold text-base-content/40 mb-2">
                    {{ new Date(leave.startDate).toLocaleDateString('id-ID', { day: 'numeric', month: 'short' }) }} 
                    - 
                    {{ new Date(leave.endDate).toLocaleDateString('id-ID', { day: 'numeric', month: 'short' }) }}
                  </p>
                  <p class="text-[10px] text-base-content/60 leading-relaxed italic line-clamp-2">"{{ leave.reason }}"</p>
                  
                  <div v-if="leave.proofs?.length" class="mt-3 flex gap-2">
                    <a v-for="proof in leave.proofs" :key="proof.id" :href="proof.fileUrl" target="_blank" class="btn btn-ghost btn-xs rounded-lg bg-base-200/50 gap-1 text-[9px] font-bold lowercase">
                      <Icon name="mingcute:attachment-2-line" />
                      bukti
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div v-else class="flex flex-col items-center justify-center py-10 text-center opacity-40">
            <Icon name="mingcute:document-fill" size="40" class="mb-2" />
            <p class="text-xs font-bold uppercase tracking-widest">Tidak Ada Izin</p>
          </div>
        </div>

      </div>
    </div>

    <!-- Loading State -->
    <div v-else class="flex items-center justify-center min-h-[50vh]">
      <span class="loading loading-spinner loading-lg text-primary"></span>
    </div>
    <!-- ====== Profile Section End -->
  </div>
</template>

// app/(dashboard)/siswa/[id]/page.tsx
'use client';

import React, { useState, useEffect, useMemo, useCallback } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { Icon } from '@/components/ui/icon';
import { format, parseISO } from 'date-fns';
import { id as localeId } from 'date-fns/locale';
import { useAuth } from '@/context/AuthContext';
import api from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { StudentHistoryModal } from '@/components/dashboard/StudentHistoryModal';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'https://api.tierkun.my.id';

const getImageUrl = (url?: string) => {
  if (!url) return '';
  if (url.startsWith('http://') || url.startsWith('https://')) return url;
  return `${API_BASE}${url.startsWith('/') ? '' : '/'}${url}`;
};

export default function StudentDetailPage() {
  const params = useParams();
  const idOrNis = params.id as string;
  const { user } = useAuth();
  const [student, setStudent] = useState<any>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [showStudentHistoryModal, setShowStudentHistoryModal] = useState<boolean>(false);

  const fetchStudentDetail = useCallback(async () => {
    setIsLoading(true);
    try {
      const res = await api.get(`/students/${idOrNis}`).catch(() => api.get(`/siswa/${idOrNis}`));
      if (res?.data) {
        setStudent(res.data.data || res.data);
      }
    } catch (e) {
      console.error('Failed to fetch student detail:', e);
    } finally {
      setIsLoading(false);
    }
  }, [idOrNis]);

  useEffect(() => {
    fetchStudentDetail();
  }, [fetchStudentDetail]);

  const nama = student?.name || student?.Nama || 'Siswa';
  const nis = student?.nis || student?.NIS || idOrNis;
  const nisn = student?.nisn || '—';
  const kelas = student?.className || student?.Kelas || student?.class?.className || 'Siswa';
  const jurusan = student?.majorAlias || student?.majorName || student?.class?.major?.name || 'Umum';
  const photoUrl = getImageUrl(student?.photoUrl || student?.url_picture || student?.faceUrl);
  const faceUrl = getImageUrl(student?.faceUrl || student?.photoUrl || student?.url_picture);
  const statusStr = (student?.status || 'AKTIF').toUpperCase();
  const isAktif = statusStr === 'AKTIF';

  const birthPlace = student?.birthPlace || student?.TempatLahir || '';
  const birthDateRaw = student?.birthDate || student?.TanggalLahir || '';

  const ttlStr = useMemo(() => {
    const dateFormatted = birthDateRaw
      ? format(parseISO(birthDateRaw), 'd MMMM yyyy', { locale: localeId })
      : '';
    if (birthPlace && dateFormatted) return `${birthPlace}, ${dateFormatted}`;
    if (dateFormatted) return dateFormatted;
    if (birthPlace) return birthPlace;
    return 'Belum Diatur';
  }, [birthPlace, birthDateRaw]);

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-3">
        <Icon icon="mingcute:loading-fill" className="text-3xl text-primary animate-spin" />
        <p className="text-xs font-semibold text-muted-foreground">Memuat detail profil siswa...</p>
      </div>
    );
  }

  if (!student) {
    return (
      <div className="max-w-4xl mx-auto py-12 text-center space-y-4">
        <div className="w-16 h-16 rounded-full bg-rose-500/10 text-rose-500 flex items-center justify-center mx-auto text-3xl">
          <Icon icon="mingcute:warning-fill" />
        </div>
        <h2 className="text-xl font-bold">Siswa Tidak Ditemukan</h2>
        <p className="text-xs text-muted-foreground">ID atau NIS siswa {idOrNis} tidak terdaftar di sistem.</p>
        <Link href="/siswa">
          <Button variant="outline" className="rounded-2xl text-xs font-bold gap-1.5">
            <Icon icon="mingcute:arrow-left-line" /> Kembali ke Daftar Siswa
          </Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto space-y-4 sm:space-y-5 pb-12 animate-in fade-in duration-500">
      {/* Top Header Back Bar */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <Link href="/siswa">
          <Button variant="outline" className="rounded-2xl gap-2 font-bold text-xs shadow-sm bg-card border-border">
            <Icon icon="mingcute:arrow-left-line" className="text-base" /> Kembali ke Daftar Siswa
          </Button>
        </Link>
        <div className="flex items-center gap-2 flex-wrap">
          <Button
            onClick={() => setShowStudentHistoryModal(true)}
            className="rounded-2xl gap-2 font-bold text-xs shadow-md bg-emerald-500 hover:bg-emerald-600 text-white cursor-pointer"
          >
            <Icon icon="mingcute:calendar-2-fill" className="text-base" /> History & Kalender Presensi
          </Button>
          <Badge className={`text-xs font-bold px-3 py-1 ${isAktif ? 'bg-emerald-500/15 text-emerald-500 border-emerald-500/30' : 'bg-rose-500/15 text-rose-500 border-rose-500/30'}`}>
            {statusStr}
          </Badge>
          <Badge variant="outline" className="bg-primary/10 text-primary border-primary/20 text-xs font-mono font-bold px-3 py-1">
            NIS: {nis}
          </Badge>
        </div>
      </div>

      {/* 2-Column Grid Layout matching Profile Card page 1-to-1 */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-5 items-start">
        {/* ── LEFT COLUMN (2-SPAN) ── */}
        <div className="lg:col-span-2 flex flex-col gap-4 sm:gap-5">
          {/* 1. Identity Card with Cover Banner & Circular Avatar */}
          <div className="overflow-hidden rounded-3xl bg-card border border-border shadow-sm">
            {/* Cover Banner */}
            <div className="relative h-28 sm:h-36 w-full overflow-hidden bg-gradient-to-r from-amber-500 via-orange-500 to-amber-600">
              <img
                src="/banner.webp"
                alt="Profile cover"
                className="w-full h-full object-cover object-center"
              />
            </div>

            {/* Avatar & Info Container */}
            <div className="px-5 pb-6 text-center relative">
              {/* Avatar Circle */}
              <div className="relative mx-auto -mt-12 sm:-mt-14 h-24 w-24 sm:h-28 sm:w-28 rounded-full bg-card p-1 shadow-lg border-4 border-card z-10">
                <div className="relative h-full w-full mx-auto rounded-full overflow-hidden bg-muted">
                  {photoUrl ? (
                    <img src={photoUrl} alt={nama} className="h-full w-full object-cover object-center" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center text-2xl font-black bg-primary/20 text-primary">
                      {nama.charAt(0)}
                    </div>
                  )}
                </div>
              </div>

              {/* User Identity Details */}
              <div className="mt-3 space-y-0.5">
                <h2 className="text-xl sm:text-2xl font-black text-foreground">{nama}</h2>
                <p className="font-bold text-xs sm:text-sm text-muted-foreground">{kelas} • {jurusan}</p>
                <div className="flex items-center justify-center gap-2 mt-2.5 flex-wrap">
                  <div className="px-3.5 py-1 bg-muted/60 border border-border text-foreground rounded-full text-xs font-mono font-bold shadow-sm">
                    NIS: {nis} {nisn !== '—' && `• NISN: ${nisn}`}
                  </div>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => setShowStudentHistoryModal(true)}
                    className="rounded-full text-xs font-bold gap-1.5 border-emerald-500/40 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-500/10 cursor-pointer"
                  >
                    <Icon icon="mingcute:calendar-2-fill" className="text-sm" /> History Presensi
                  </Button>
                </div>
              </div>
            </div>
          </div>

          {/* 2. Personal Info Card (Informasi Pribadi) */}
          <div className="rounded-3xl bg-card p-4 sm:p-5 border border-border shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-border">
              <h3 className="text-[11px] font-black text-muted-foreground uppercase tracking-widest">
                Informasi Pribadi Siswa
              </h3>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-5">
              {/* TTL */}
              <div className="flex items-start gap-3.5">
                <div className="w-9 h-9 rounded-xl bg-muted/60 text-muted-foreground flex items-center justify-center shrink-0">
                  <Icon icon="mingcute:calendar-fill" className="text-lg" />
                </div>
                <div className="min-w-0">
                  <p className="text-[10px] font-black uppercase text-muted-foreground tracking-wider mb-0.5">
                    Tempat, Tanggal Lahir
                  </p>
                  <p className="text-xs sm:text-sm font-bold text-foreground truncate">{ttlStr}</p>
                </div>
              </div>

              {/* Gender & Agama */}
              <div className="flex items-start gap-3.5">
                <div className="w-9 h-9 rounded-xl bg-muted/60 text-muted-foreground flex items-center justify-center shrink-0">
                  <Icon icon="mingcute:user-info-fill" className="text-lg" />
                </div>
                <div>
                  <p className="text-[10px] font-black uppercase text-muted-foreground tracking-wider mb-0.5">
                    Gender / Agama
                  </p>
                  <p className="text-xs sm:text-sm font-bold text-foreground">
                    {student?.gender === 'P' || student?.Gender === 'P' ? 'Perempuan' : 'Laki-Laki'} • {student?.religion || student?.Agama || 'Islam'}
                  </p>
                </div>
              </div>

              {/* Email */}
              <div className="flex items-start gap-3.5">
                <div className="w-9 h-9 rounded-xl bg-muted/60 text-muted-foreground flex items-center justify-center shrink-0">
                  <Icon icon="mingcute:mail-fill" className="text-lg" />
                </div>
                <div className="min-w-0">
                  <p className="text-[10px] font-black uppercase text-muted-foreground tracking-wider mb-0.5">
                    Email
                  </p>
                  <p className="text-xs sm:text-sm font-bold text-foreground truncate">{student?.email || student?.Email || 'Belum Diatur'}</p>
                </div>
              </div>

              {/* Alamat */}
              <div className="flex items-start gap-3.5">
                <div className="w-9 h-9 rounded-xl bg-muted/60 text-muted-foreground flex items-center justify-center shrink-0">
                  <Icon icon="mingcute:location-fill" className="text-lg" />
                </div>
                <div>
                  <p className="text-[10px] font-black uppercase text-muted-foreground tracking-wider mb-0.5">
                    Alamat
                  </p>
                  <p className="text-xs sm:text-sm font-bold text-foreground leading-relaxed">{student?.address || student?.Alamat || 'Belum Diatur'}</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ── RIGHT COLUMN (1-SPAN) ── */}
        <div className="lg:col-span-1 flex flex-col gap-4 sm:gap-5">
          {/* 1. Contact Card (Kontak) */}
          <div className="rounded-3xl bg-card p-4 sm:p-5 border border-border shadow-sm space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-[11px] font-black text-muted-foreground uppercase tracking-widest">
                Kontak
              </h3>
            </div>
            <div className="flex items-center gap-3.5">
              <div className="w-10 h-10 rounded-2xl bg-emerald-500/10 text-emerald-500 flex items-center justify-center shrink-0 shadow-inner">
                <Icon icon="mingcute:phone-fill" className="text-xl" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] font-black uppercase text-muted-foreground tracking-wider">
                  WhatsApp / Telp
                </p>
                <p className="text-sm font-bold text-foreground font-mono mt-0.5 truncate">
                  {student?.phone || student?.Nomor || 'Belum Diatur'}
                </p>
              </div>
            </div>
          </div>

          {/* 2. Vehicle Card (Kendaraan) */}
          <div className="rounded-3xl bg-card p-4 sm:p-5 border border-border shadow-sm space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-[11px] font-black text-muted-foreground uppercase tracking-widest">
                Kendaraan
              </h3>
            </div>
            <div className="flex items-center gap-3.5">
              <div className="w-10 h-10 rounded-2xl bg-sky-500/10 text-sky-500 flex items-center justify-center shrink-0 shadow-inner">
                <Icon icon="mingcute:car-fill" className="text-xl" />
              </div>
              <div>
                <p className="text-[10px] font-black uppercase text-muted-foreground tracking-wider mb-0.5">
                  Plat Nomor
                </p>
                <div className="px-2.5 py-0.5 bg-muted/80 border border-border rounded-lg inline-block">
                  <span className="text-xs font-mono font-bold tracking-widest text-foreground">
                    {student?.vehiclePlate || student?.Plat_Nomor || '----'}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* 3. Foto Absensi Card (Face Recognition) */}
          <div className="rounded-3xl bg-card p-4 sm:p-5 border border-border shadow-sm space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-[11px] font-black text-muted-foreground uppercase tracking-widest">
                Foto Biometrik Absensi
              </h3>
              {faceUrl ? (
                <Badge className="bg-emerald-500/15 text-emerald-500 border-emerald-500/30 text-[9px] font-bold px-2 py-0.5">
                  Terdaftar
                </Badge>
              ) : (
                <Badge className="bg-amber-500/15 text-amber-500 border-amber-500/30 text-[9px] font-bold px-2 py-0.5">
                  Belum Ada
                </Badge>
              )}
            </div>

            <div className="flex flex-col gap-3">
              <div className="relative w-28 h-36 mx-auto rounded-2xl overflow-hidden bg-muted border border-border flex items-center justify-center shadow-inner">
                {faceUrl ? (
                  <img src={faceUrl} alt="Foto Wajah" className="h-full w-full object-cover object-center" />
                ) : (
                  <div className="flex flex-col items-center justify-center text-muted-foreground/50 p-2 text-center">
                    <Icon icon="mingcute:face-fill" className="text-3xl mb-1 opacity-60" />
                    <p className="text-[10px] font-semibold">Belum ada foto</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      <StudentHistoryModal
        isOpen={showStudentHistoryModal}
        onClose={() => setShowStudentHistoryModal(false)}
        student={student}
      />
    </div>
  );
}
