// components/Dashboard/DashboardSiswa.vue
<script setup>
import { ref, computed, onMounted, watch } from 'vue';

const props = defineProps({
  user: Object
});

// Selected Month & Year
const selectedMonth = ref(new Date().getMonth() + 1);
const selectedYear = ref(new Date().getFullYear());

const months = [
  { value: 1, name: 'Januari' },
  { value: 2, name: 'Februari' },
  { value: 3, name: 'Maret' },
  { value: 4, name: 'April' },
  { value: 5, name: 'Mei' },
  { value: 6, name: 'Juni' },
  { value: 7, name: 'Juli' },
  { value: 8, name: 'Agustus' },
  { value: 9, name: 'September' },
  { value: 10, name: 'Oktober' },
  { value: 11, name: 'November' },
  { value: 12, name: 'Desember' }
];

const years = computed(() => {
  const current = new Date().getFullYear();
  return [current, current - 1, current - 2];
});

// Lightbox state
const activePreviewImage = ref(null);
const openImagePreview = (url) => { if (url) activePreviewImage.value = url; };
const closeImagePreview = () => { activePreviewImage.value = null; };

// Daily logs detail modal
const selectedDayLog = ref(null);
const showDetailModal = ref(false);
const openDayDetail = (day) => {
  if (day.record) {
    selectedDayLog.value = day;
    showDetailModal.value = true;
  }
};
const closeDetailModal = () => {
  showDetailModal.value = false;
  selectedDayLog.value = null;
};

// Attendance data
const attendance = ref(null);
const loading = ref(true);

const fetchAttendance = async () => {
  loading.value = true;
  try {
    const data = await $fetch(`/api/attendance/my?month=${selectedMonth.value}&year=${selectedYear.value}`);
    attendance.value = data?.data || null;
  } catch (e) {
    console.error('Failed to fetch attendance:', e);
  } finally {
    loading.value = false;
  }
};

onMounted(fetchAttendance);

// Watch filters
watch([selectedMonth, selectedYear], fetchAttendance);

// Computed
const summary = computed(() => attendance.value?.summary || { hadir: 0, terlambat: 0, izin: 0, sakit: 0, alpha: 0, total: 0 });
const todayStatus = computed(() => attendance.value?.today);

const groupedByDate = computed(() => {
  if (!attendance.value?.attendances) return [];
  
  const groups = {};
  attendance.value.attendances.forEach(att => {
    const dateStr = att.timestamp.substring(0, 10); // YYYY-MM-DD
    if (!groups[dateStr]) {
      groups[dateStr] = [];
    }
    groups[dateStr].push(att);
  });
  
  const list = Object.keys(groups).map(dateStr => {
    const atts = groups[dateStr];
    atts.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
    
    const checkIn = atts[0];
    const checkOut = atts.length > 1 ? atts[atts.length - 1] : null;
    
    const status = checkIn.status;
    const method = checkIn.method;
    
    return {
      date: dateStr,
      status,
      method,
      checkInTime: checkIn.timestamp,
      checkOutTime: checkOut ? checkOut.timestamp : null,
      photoUrl: checkIn.notes || null,
      checkOutPhotoUrl: checkOut ? checkOut.notes : null,
      logs: atts.map(a => ({
        id: a.id,
        timestamp: a.timestamp,
        status: a.status,
        method: a.method,
        notes: a.notes
      }))
    };
  });
  
  return list;
});

const calendarDays = computed(() => {
  const daysInMonth = new Date(selectedYear.value, selectedMonth.value, 0).getDate();
  const list = [];
  
  const grouped = {};
  groupedByDate.value.forEach(item => {
    const d = new Date(item.date).getDate();
    grouped[d] = item;
  });
  
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  for (let i = 1; i <= daysInMonth; i++) {
    const currentDate = new Date(selectedYear.value, selectedMonth.value - 1, i);
    const dayOfWeek = currentDate.getDay(); // 0 = Sun, 6 = Sat
    const isWeekendVal = dayOfWeek === 0 || dayOfWeek === 6;
    
    const compareDate = new Date(selectedYear.value, selectedMonth.value - 1, i);
    compareDate.setHours(0, 0, 0, 0);
    const isFuture = compareDate > today;
    
    const record = grouped[i];
    
    list.push({
      dayNum: i,
      dateObject: currentDate,
      isWeekend: isWeekendVal,
      isFuture,
      record: record || null
    });
  }
  
  return list.reverse();
});

const attendanceRate = computed(() => {
  const s = summary.value;
  if (!s.total) return 0;
  return Math.round(((s.hadir + s.terlambat) / s.total) * 100);
});

// Status helpers
const statusConfig = {
  HADIR: { color: 'text-emerald-500', bg: 'bg-emerald-500/10 border border-emerald-500/30 text-emerald-500', icon: 'mingcute:check-circle-fill', label: 'Hadir' },
  TERLAMBAT: { color: 'text-amber-500', bg: 'bg-amber-500/10 border border-amber-500/30 text-amber-500', icon: 'mingcute:time-fill', label: 'Terlambat' },
  IZIN: { color: 'text-sky-500', bg: 'bg-sky-500/10 border border-sky-500/30 text-sky-500', icon: 'mingcute:document-fill', label: 'Izin' },
  SAKIT: { color: 'text-orange-400', bg: 'bg-orange-400/10 border border-orange-400/30 text-orange-400', icon: 'mingcute:heart-fill', label: 'Sakit' },
  ALPHA: { color: 'text-rose-500', bg: 'bg-rose-500/10 border border-rose-500/30 text-rose-500', icon: 'mingcute:close-circle-fill', label: 'Alpha' },
};

const getStatus = (status) => statusConfig[status] || statusConfig.ALPHA;

const formatTime = (ts) => {
  if (!ts) return '-';
  const d = new Date(ts);
  return d.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });
};

const formatDate = (dateObj) => {
  return dateObj.toLocaleDateString('id-ID', { weekday: 'short', day: 'numeric', month: 'short' });
};

const bentoCard = "bg-base-100 rounded-3xl p-6 hover:-translate-y-1 hover:shadow-lg hover:shadow-base-300/50 transition-all duration-300 flex flex-col justify-center relative overflow-hidden";
</script>

<template>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    
    <!-- Profil Siswa (2x1) -->
    <div :class="[bentoCard, 'lg:col-span-2 bg-gradient-to-br from-primary/20 to-base-100']">
      <div class="flex items-center gap-6">
        <div class="avatar">
          <div class="w-20 rounded-full overflow-hidden bg-primary text-primary-content shadow-inner">
            <img v-if="user?.url_picture" :src="user.url_picture" :alt="user?.Nama" class="w-full h-full object-cover" />
            <div v-else class="w-full h-full flex items-center justify-center text-3xl font-bold">
              {{ user?.Nama?.charAt(0) || 'S' }}
            </div>
          </div>
        </div>
        <div>
          <h2 class="text-2xl font-bold text-base-content">Halo, {{ user?.Nama?.split(' ')[0] || 'Siswa' }}!</h2>
          <p class="text-base-content/70 mt-1">{{ user?.Kelas }} · NIS: {{ user?.NIS || '-' }}</p>
        </div>
      </div>
    </div>

    <!-- Status Hari Ini (1x1) -->
    <div :class="bentoCard">
      <p class="text-base-content/70 font-medium mb-2 text-sm">Status Hari Ini</p>
      <div v-if="loading" class="flex items-center gap-3">
        <span class="loading loading-spinner loading-md text-primary"></span>
      </div>
      <div v-else-if="todayStatus" class="flex items-center gap-3" :class="getStatus(todayStatus.status).color">
        <Icon :name="getStatus(todayStatus.status).icon" class="text-4xl" />
        <div>
          <span class="text-2xl font-bold">{{ getStatus(todayStatus.status).label }}</span>
          <p class="text-xs opacity-70">{{ formatTime(todayStatus.time) }}</p>
        </div>
      </div>
      <div v-else class="flex items-center gap-3 text-base-content/40">
        <Icon name="mingcute:time-line" class="text-4xl" />
        <span class="text-lg font-semibold">Belum Absen</span>
      </div>
    </div>

    <!-- Persentase Kehadiran (1x1) -->
    <div :class="bentoCard">
      <p class="text-base-content/70 font-medium mb-2 text-sm">Kehadiran Bulan Ini</p>
      <div class="flex items-end gap-2">
        <span class="text-4xl font-bold" :class="attendanceRate >= 80 ? 'text-success' : attendanceRate >= 60 ? 'text-warning' : 'text-error'">
          {{ attendanceRate }}%
        </span>
        <span class="text-sm text-base-content/50 pb-1">dari {{ summary.total }} hari</span>
      </div>
      <progress
        class="progress w-full mt-3"
        :class="attendanceRate >= 80 ? 'progress-success' : attendanceRate >= 60 ? 'progress-warning' : 'progress-error'"
        :value="attendanceRate"
        max="100"
      ></progress>
    </div>

    <!-- Rekap Absensi Bulan Ini (Full span) -->
    <div :class="[bentoCard, 'lg:col-span-4']">
      <p class="text-base-content/70 font-medium mb-4">Rekap Absensi Bulan Ini</p>
      <div v-if="loading" class="flex justify-center py-4">
        <span class="loading loading-spinner loading-lg text-primary"></span>
      </div>
      <div v-else class="grid grid-cols-2 md:grid-cols-5 gap-4">
        <div class="bg-success/10 p-4 rounded-2xl text-center">
          <p class="text-3xl font-bold text-success mb-1">{{ summary.hadir }}</p>
          <p class="text-xs text-base-content/70 uppercase tracking-wider">Hadir</p>
        </div>
        <div class="bg-warning/10 p-4 rounded-2xl text-center">
          <p class="text-3xl font-bold text-warning mb-1">{{ summary.terlambat }}</p>
          <p class="text-xs text-base-content/70 uppercase tracking-wider">Terlambat</p>
        </div>
        <div class="bg-info/10 p-4 rounded-2xl text-center">
          <p class="text-3xl font-bold text-info mb-1">{{ summary.izin }}</p>
          <p class="text-xs text-base-content/70 uppercase tracking-wider">Izin</p>
        </div>
        <div class="bg-orange-400/10 p-4 rounded-2xl text-center">
          <p class="text-3xl font-bold text-orange-400 mb-1">{{ summary.sakit }}</p>
          <p class="text-xs text-base-content/70 uppercase tracking-wider">Sakit</p>
        </div>
        <div class="bg-error/10 p-4 rounded-2xl text-center">
          <p class="text-3xl font-bold text-error mb-1">{{ summary.alpha }}</p>
          <p class="text-xs text-base-content/70 uppercase tracking-wider">Alpha</p>
        </div>
      </div>
    </div>

    <!-- Riwayat Kehadiran Bulanan (Full span) -->
    <div :class="[bentoCard, 'lg:col-span-4 flex flex-col min-h-0']">
      <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 shrink-0">
        <div>
          <p class="text-base-content/70 font-semibold text-lg">Riwayat Kehadiran Bulanan</p>
          <p class="text-xs text-base-content/40 font-medium">Lihat seluruh riwayat jam IN, OUT, beserta hasil foto tap absensi</p>
        </div>
        <!-- Select Month & Year -->
        <div class="flex gap-2">
          <select v-model="selectedMonth" class="select select-bordered select-sm rounded-xl font-bold">
            <option v-for="m in months" :key="m.value" :value="m.value">{{ m.name }}</option>
          </select>
          <select v-model="selectedYear" class="select select-bordered select-sm rounded-xl font-bold">
            <option v-for="y in years" :key="y" :value="y">{{ y }}</option>
          </select>
        </div>
      </div>

      <div v-if="loading" class="flex justify-center py-12 shrink-0">
        <span class="loading loading-spinner loading-lg text-primary"></span>
      </div>
      
      <div v-else class="overflow-x-auto w-full custom-scrollbar flex-1">
        <table class="table table-sm min-w-[720px] w-full">
          <thead>
            <tr class="text-base-content/30 text-[10px] font-black uppercase tracking-wider border-b border-base-200">
              <th class="w-32">Tanggal</th>
              <th class="w-36 text-center">Status</th>
              <th class="w-44 text-center">Jam IN / Masuk (Foto)</th>
              <th class="w-44 text-center">Jam OUT / Pulang (Foto)</th>
              <th class="text-right">Aksi</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-base-200/50">
            <tr v-for="day in calendarDays" :key="day.dayNum" 
                :class="[
                  'hover:bg-base-200/30 transition-colors', 
                  day.isWeekend ? 'bg-base-200/10' : '',
                  day.isFuture ? 'opacity-30 pointer-events-none' : ''
                ]">
              <!-- Tanggal -->
              <td class="font-bold text-xs">
                {{ formatDate(day.dateObject) }}
              </td>

              <!-- Status -->
              <td class="text-center">
                <!-- If has record -->
                <span v-if="day.record"
                  class="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-lg text-[10px] font-black uppercase tracking-wider"
                  :class="[getStatus(day.record.status).color, getStatus(day.record.status).bg]"
                >
                  <Icon :name="getStatus(day.record.status).icon" class="text-xs" />
                  {{ getStatus(day.record.status).label }}
                </span>
                <!-- If weekend & no record -->
                <span v-else-if="day.isWeekend" class="text-[9px] font-black uppercase text-base-content/30 tracking-widest">
                  Akhir Pekan
                </span>
                <!-- If future & no record -->
                <span v-else-if="day.isFuture" class="text-[9px] font-black uppercase text-base-content/20 tracking-widest">
                  Mendatang
                </span>
                <!-- If past/today weekday & no record -->
                <span v-else
                  class="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-lg text-[10px] font-black uppercase tracking-wider"
                  :class="[getStatus('ALPHA').color, getStatus('ALPHA').bg]"
                >
                  <Icon :name="getStatus('ALPHA').icon" class="text-xs" />
                  Tanpa Absen
                </span>
              </td>

              <!-- Jam IN (Foto) -->
              <td class="text-center">
                <div v-if="day.record" class="flex items-center justify-center gap-2">
                  <span class="text-xs font-mono font-bold text-base-content/80">{{ formatTime(day.record.checkInTime) }}</span>
                  <div class="w-8 h-8 rounded-lg overflow-hidden bg-base-200 border border-base-200 shrink-0 shadow-sm cursor-zoom-in group" @click="openImagePreview(day.record.photoUrl || props.user?.url_picture)">
                    <img v-if="day.record.photoUrl" :src="day.record.photoUrl" class="w-full h-full object-cover group-hover:scale-110 transition-transform" />
                    <img v-else-if="props.user?.url_picture" :src="props.user.url_picture" class="w-full h-full object-cover group-hover:scale-110 transition-transform opacity-30" />
                    <div v-else class="w-full h-full flex items-center justify-center text-base-content/20">
                      <Icon name="mingcute:pic-line" size="14" />
                    </div>
                  </div>
                </div>
                <span v-else class="text-base-content/20">-</span>
              </td>

              <!-- Jam OUT (Foto) -->
              <td class="text-center">
                <div v-if="day.record && day.record.checkOutTime" class="flex items-center justify-center gap-2">
                  <span class="text-xs font-mono font-bold text-base-content/80">{{ formatTime(day.record.checkOutTime) }}</span>
                  <div class="w-8 h-8 rounded-lg overflow-hidden bg-base-200 border border-base-200 shrink-0 shadow-sm cursor-zoom-in group" @click="openImagePreview(day.record.checkOutPhotoUrl || props.user?.url_picture)">
                    <img v-if="day.record.checkOutPhotoUrl" :src="day.record.checkOutPhotoUrl" class="w-full h-full object-cover group-hover:scale-110 transition-transform" />
                    <img v-else-if="props.user?.url_picture" :src="props.user.url_picture" class="w-full h-full object-cover group-hover:scale-110 transition-transform opacity-30" />
                    <div v-else class="w-full h-full flex items-center justify-center text-base-content/20">
                      <Icon name="mingcute:pic-line" size="14" />
                    </div>
                  </div>
                </div>
                <span v-else class="text-base-content/20">-</span>
              </td>

              <!-- Aksi / Detail logs -->
              <td class="text-right">
                <button v-if="day.record" @click="openDayDetail(day)" 
                        class="btn btn-ghost btn-xs rounded-lg hover:bg-primary/10 hover:text-primary font-bold">
                  {{ day.record.logs.length }} Log Tap
                </button>
                <span v-else class="text-base-content/20">-</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- ═══ DETAIL LOG TAP MODAL ═══ -->
    <Teleport to="body">
      <Transition name="modal">
        <div v-if="showDetailModal && selectedDayLog" class="fixed inset-0 z-[999] flex items-center justify-center p-4" @click.self="closeDetailModal">
          <div class="absolute inset-0 bg-black/50 backdrop-blur-sm"></div>
          <div class="relative bg-base-100 rounded-[2rem] shadow-2xl w-full max-w-md overflow-hidden z-10 max-h-[85vh] flex flex-col">
            
            <!-- Modal Header -->
            <div class="p-6 border-b border-base-200/40 flex items-center justify-between shrink-0 bg-primary/5">
              <div>
                <h3 class="text-lg font-black text-base-content">Detail Log Tap Absensi</h3>
                <p class="text-xs text-base-content/40 font-bold uppercase tracking-wider mt-0.5">Tanggal: {{ formatDate(selectedDayLog.dateObject) }}</p>
              </div>
              <button @click="closeDetailModal" class="btn btn-ghost btn-sm btn-circle"><Icon name="mingcute:close-line" size="20" /></button>
            </div>

            <!-- Modal Body -->
            <div class="p-6 space-y-4 overflow-y-auto flex-1 custom-scrollbar">
              <div class="space-y-3">
                <div v-for="(log, idx) in selectedDayLog.record.logs" :key="log.id" 
                     class="flex items-center gap-4 p-3 rounded-2xl bg-base-200/30 border border-base-200/50 hover:bg-base-200/60 transition-colors">
                  <!-- Index / Count -->
                  <div class="w-6 h-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center font-black text-[10px] shrink-0">
                    {{ idx + 1 }}
                  </div>
                  <!-- Time -->
                  <div class="flex-1 min-w-0">
                    <p class="text-sm font-mono font-bold text-base-content">{{ formatTime(log.timestamp) }}</p>
                    <p class="text-[9px] font-black uppercase tracking-wider text-base-content/30 mt-0.5">
                      Metode: {{ log.method === 'FACE_RECOGNITION' ? 'Face ID' : log.method === 'QR_CODE' ? 'QR Code' : 'Manual' }}
                    </p>
                  </div>
                  <!-- Thumbnail Photo -->
                  <div class="w-12 h-12 rounded-xl overflow-hidden bg-base-200 border border-base-200 shrink-0 shadow-sm cursor-zoom-in group" @click="openImagePreview(log.notes || props.user?.url_picture)">
                    <img v-if="log.notes" :src="log.notes" class="w-full h-full object-cover group-hover:scale-110 transition-transform" />
                    <img v-else-if="props.user?.url_picture" :src="props.user.url_picture" class="w-full h-full object-cover group-hover:scale-110 transition-transform opacity-30" />
                    <div v-else class="w-full h-full flex items-center justify-center text-base-content/20">
                      <Icon name="mingcute:pic-line" size="16" />
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Modal Footer -->
            <div class="p-6 pt-0 shrink-0">
              <button @click="closeDetailModal" class="btn btn-ghost btn-block rounded-2xl font-black">Tutup</button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>

    <!-- ═══ IMAGE PREVIEW MODAL (LIGHTBOX) ═══ -->
    <Teleport to="body">
      <Transition name="fade">
        <div v-if="activePreviewImage" class="fixed inset-0 z-[1000] flex items-center justify-center bg-black/90 p-4" @click="closeImagePreview">
          <button class="absolute top-6 right-6 text-white hover:text-gray-300 transition-colors btn btn-ghost btn-circle">
            <Icon name="mingcute:close-line" size="28" />
          </button>
          <img :src="activePreviewImage" class="max-w-full max-h-[90vh] object-contain rounded-2xl shadow-2xl border border-white/10" @click.stop />
        </div>
      </Transition>
    </Teleport>
    
  </div>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar { width: 4px; height: 4px; }
.custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
.custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(var(--bc), 0.08); border-radius: 10px; }

.modal-enter-active, .modal-leave-active { transition: all 0.2s ease; }
.modal-enter-from, .modal-leave-to { opacity: 0; transform: scale(0.95); }

.fade-enter-active, .fade-leave-active { transition: opacity 0.2s ease; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>

// components/dashboard/DashboardSiswa.tsx
'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Icon } from '@/components/ui/icon';
import api from '@/lib/api';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { CustomSelect } from '@/components/shared/CustomSelect';
import { Skeleton } from '@/components/ui/skeleton';

interface DashboardSiswaProps {
  user: any;
}

const months = [
  { value: 1, name: 'Januari' },
  { value: 2, name: 'Februari' },
  { value: 3, name: 'Maret' },
  { value: 4, name: 'April' },
  { value: 5, name: 'Mei' },
  { value: 6, name: 'Juni' },
  { value: 7, name: 'Juli' },
  { value: 8, name: 'Agustus' },
  { value: 9, name: 'September' },
  { value: 10, name: 'Oktober' },
  { value: 11, name: 'November' },
  { value: 12, name: 'Desember' },
];

const statusConfig: Record<string, { color: string; bg: string; icon: string; label: string }> = {
  HADIR: { color: 'text-emerald-500', bg: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-500', icon: 'mingcute:check-circle-fill', label: 'Hadir' },
  TERLAMBAT: { color: 'text-amber-500', bg: 'bg-amber-500/10 border-amber-500/30 text-amber-500', icon: 'mingcute:time-fill', label: 'Terlambat' },
  IZIN: { color: 'text-sky-500', bg: 'bg-sky-500/10 border-sky-500/30 text-sky-500', icon: 'mingcute:document-fill', label: 'Izin' },
  SAKIT: { color: 'text-orange-400', bg: 'bg-orange-400/10 border-orange-400/30 text-orange-400', icon: 'mingcute:heart-fill', label: 'Sakit' },
  ALPHA: { color: 'text-rose-500', bg: 'bg-rose-500/10 border-rose-500/30 text-rose-500', icon: 'mingcute:close-circle-fill', label: 'Alpha' },
};

const getStatus = (statusStr?: string) => statusConfig[statusStr || 'ALPHA'] || statusConfig.ALPHA;

const formatTime = (ts?: string) => {
  if (!ts) return '-';
  try {
    const d = new Date(ts);
    if (isNaN(d.getTime())) return '-';
    return d.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });
  } catch {
    return '-';
  }
};

const formatDate = (dateObj: Date) => {
  return dateObj.toLocaleDateString('id-ID', { weekday: 'short', day: 'numeric', month: 'short' });
};

export const DashboardSiswa: React.FC<DashboardSiswaProps> = ({ user }) => {
  const currentYear = new Date().getFullYear();
  const [selectedMonth, setSelectedMonth] = useState<number>(new Date().getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState<number>(currentYear);

  const years = useMemo(() => [currentYear, currentYear - 1, currentYear - 2], [currentYear]);

  // Attendance data
  const [attendance, setAttendance] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  // Modal Detail Log
  const [selectedDayLog, setSelectedDayLog] = useState<any>(null);
  const [activePreviewImage, setActivePreviewImage] = useState<string | null>(null);

  const fetchAttendance = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get(`/attendance/my?month=${selectedMonth}&year=${selectedYear}`).catch(() =>
        api.get(`/absensi?month=${selectedMonth}&year=${selectedYear}`)
      );
      const d = res?.data?.data || res?.data;
      if (d) setAttendance(d);
    } catch (e) {
      console.error('Failed to fetch student attendance:', e);
    } finally {
      setLoading(false);
    }
  }, [selectedMonth, selectedYear]);

  useEffect(() => {
    fetchAttendance();
  }, [fetchAttendance]);

  const summary = useMemo(() => {
    return (
      attendance?.summary || {
        hadir: 0,
        terlambat: 0,
        izin: 0,
        sakit: 0,
        alpha: 0,
        total: 0,
      }
    );
  }, [attendance]);

  const todayStatus = useMemo(() => attendance?.today, [attendance]);

  const attendanceRate = useMemo(() => {
    const s = summary;
    if (!s.total) return 100;
    return Math.round(((s.hadir + s.terlambat) / s.total) * 100);
  }, [summary]);

  const groupedByDate = useMemo(() => {
    if (!attendance?.attendances) return [];
    const groups: Record<string, any[]> = {};
    attendance.attendances.forEach((att: any) => {
      const dateStr = att.timestamp.substring(0, 10);
      if (!groups[dateStr]) groups[dateStr] = [];
      groups[dateStr].push(att);
    });

    return Object.keys(groups).map((dateStr) => {
      const atts = groups[dateStr];
      atts.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
      const checkIn = atts[0];
      const checkOut = atts.length > 1 ? atts[atts.length - 1] : null;

      return {
        date: dateStr,
        status: checkIn.status,
        method: checkIn.method,
        checkInTime: checkIn.timestamp,
        checkOutTime: checkOut ? checkOut.timestamp : null,
        photoUrl: checkIn.notes || null,
        checkOutPhotoUrl: checkOut ? checkOut.notes : null,
        logs: atts.map((a) => ({
          id: a.id,
          timestamp: a.timestamp,
          status: a.status,
          method: a.method,
          notes: a.notes,
        })),
      };
    });
  }, [attendance]);

  const calendarDays = useMemo(() => {
    const daysInMonth = new Date(selectedYear, selectedMonth, 0).getDate();
    const list: any[] = [];
    const grouped: Record<number, any> = {};

    groupedByDate.forEach((item) => {
      const d = new Date(item.date).getDate();
      grouped[d] = item;
    });

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    for (let i = 1; i <= daysInMonth; i++) {
      const currentDate = new Date(selectedYear, selectedMonth - 1, i);
      const dayOfWeek = currentDate.getDay();
      const isWeekendVal = dayOfWeek === 0 || dayOfWeek === 6;

      const compareDate = new Date(selectedYear, selectedMonth - 1, i);
      compareDate.setHours(0, 0, 0, 0);
      const isFuture = compareDate > today;
      const record = grouped[i];

      list.push({
        dayNum: i,
        dateObject: currentDate,
        isWeekend: isWeekendVal,
        isFuture,
        record: record || null,
      });
    }

    return list.reverse();
  }, [selectedYear, selectedMonth, groupedByDate]);

  // Resolve Real Kelas & NIS matching Nuxt 1-to-1
  const displayKelas = useMemo(() => {
    if (!user) return '-';
    if (user.Kelas) return user.Kelas;
    if (typeof user.kelas === 'object' && user.kelas?.nama_kelas) return user.kelas.nama_kelas;
    if (typeof user.kelas === 'string' && user.kelas.trim()) return user.kelas;
    if (user.class?.className) return user.class.className;
    if (user.className) return user.className;
    return 'Siswa Active';
  }, [user]);

  const displayNis = useMemo(() => {
    if (!user) return '-';
    if (user.NIS) return user.NIS;
    if (user.nis) return user.nis;
    if (user.nisn) return user.nisn;
    if (user.studentNis) return user.studentNis;
    if (user.nis_siswa) return user.nis_siswa;
    if (user.username) return user.username;
    return user.id ? String(user.id) : '-';
  }, [user]);

  const bentoCard = "min-w-0 bg-card border border-border rounded-3xl p-4 sm:p-6 shadow-sm hover:shadow-md transition-all duration-300 flex flex-col justify-center relative overflow-hidden";

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 animate-in fade-in duration-500">
      {/* 1. Profil Siswa */}
      {!user ? (
        <div className={`${bentoCard} lg:col-span-2 bg-muted/20 border-border`}>
          <div className="flex min-w-0 flex-col items-start gap-4 min-[360px]:flex-row min-[360px]:items-center sm:gap-6">
            <Skeleton className="w-20 h-20 rounded-full shrink-0" />
            <div className="min-w-0 space-y-2 flex-1">
              <Skeleton className="h-7 w-48 max-w-full" />
              <Skeleton className="h-4 w-32 max-w-full" />
            </div>
          </div>
        </div>
      ) : (
        <div className={`${bentoCard} lg:col-span-2 bg-gradient-to-br from-primary/20 via-card to-background border-primary/20`}>
          <div className="flex min-w-0 flex-col items-start gap-4 min-[360px]:flex-row min-[360px]:items-center sm:gap-6">
            <div className="w-20 h-20 rounded-full overflow-hidden bg-primary/20 border-2 border-primary/40 text-primary flex items-center justify-center shrink-0 shadow-inner">
              {user?.avatar || user?.url_picture ? (
                <img src={user.avatar || user.url_picture} alt={user?.Nama || user?.name} className="w-full h-full object-cover" />
              ) : (
                <span className="text-3xl font-black">{user?.Nama?.charAt(0) || user?.name?.charAt(0) || 'F'}</span>
              )}
            </div>
            <div className="min-w-0">
              <h2 className="break-words text-2xl sm:text-3xl font-black text-foreground tracking-tight">
                Halo, {user?.Nama?.split(' ')[0] || user?.name?.split(' ')[0] || 'Siswa'}!
              </h2>
              <p className="break-words text-xs sm:text-sm text-muted-foreground font-semibold mt-1">
                {displayKelas} · NIS: <span className="font-mono text-foreground font-bold">{displayNis}</span>
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 2. Status Hari Ini */}
      {loading ? (
        <div className={`${bentoCard} bg-muted/20 border-border`}>
          <Skeleton className="h-4 w-24 mb-4" />
          <div className="flex items-center gap-3">
            <Skeleton className="w-10 h-10 rounded-full" />
            <div className="space-y-2">
              <Skeleton className="h-6 w-24" />
              <Skeleton className="h-3 w-16" />
            </div>
          </div>
        </div>
      ) : (
        <div className={bentoCard}>
          <p className="text-muted-foreground font-bold mb-2 text-xs uppercase tracking-wider">Status Hari Ini</p>
          {todayStatus ? (
            <div className={`flex items-center gap-3 ${getStatus(todayStatus.status).color}`}>
              <Icon icon={getStatus(todayStatus.status).icon} className="text-4xl" />
              <div>
                <span className="text-2xl font-black">{getStatus(todayStatus.status).label}</span>
                <p className="text-xs font-mono font-bold opacity-80">{formatTime(todayStatus.time)}</p>
              </div>
            </div>
          ) : (
            <div className="flex items-center gap-3 text-muted-foreground/40">
              <Icon icon="mingcute:time-line" className="text-4xl" />
              <span className="text-lg font-bold">Belum Absen</span>
            </div>
          )}
        </div>
      )}

      {/* 3. Persentase Kehadiran */}
      {loading ? (
        <div className={`${bentoCard} bg-muted/20 border-border`}>
          <Skeleton className="h-4 w-32 mb-4" />
          <Skeleton className="h-8 w-16 mb-2" />
          <Skeleton className="h-2.5 w-full rounded-full mt-3" />
        </div>
      ) : (
        <div className={bentoCard}>
          <p className="text-muted-foreground font-bold mb-2 text-xs uppercase tracking-wider">Kehadiran Bulan Ini</p>
          <div className="flex items-end gap-2">
            <span className={`text-4xl font-black ${attendanceRate >= 80 ? 'text-emerald-500' : attendanceRate >= 60 ? 'text-amber-500' : 'text-rose-500'}`}>
              {attendanceRate}%
            </span>
            <span className="text-xs text-muted-foreground font-semibold pb-1">dari {summary.total || 1} hari</span>
          </div>
          <Progress value={attendanceRate} className="h-2.5 mt-3 bg-muted" />
        </div>
      )}

      {/* 4. Rekap Absensi Bulan Ini */}
      {loading ? (
        <div className={`${bentoCard} lg:col-span-4 bg-muted/20 border-border`}>
          <Skeleton className="h-4 w-40 mb-6" />
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3 sm:gap-4 [&>*:last-child]:col-span-2 md:[&>*:last-child]:col-span-1">
            {Array.from({ length: 5 }).map((_, i) => (
              <Skeleton key={i} className="h-24 w-full rounded-2xl" />
            ))}
          </div>
        </div>
      ) : (
        <div className={`${bentoCard} lg:col-span-4`}>
          <p className="text-muted-foreground font-bold mb-4 text-xs uppercase tracking-wider">Rekap Absensi Bulan Ini</p>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3 sm:gap-4 [&>*:last-child]:col-span-2 md:[&>*:last-child]:col-span-1">
            <div className="bg-emerald-500/10 border border-emerald-500/20 p-4 rounded-2xl text-center">
              <p className="text-3xl font-black text-emerald-500 mb-1">{summary.hadir}</p>
              <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">HADIR</p>
            </div>
            <div className="bg-amber-500/10 border border-amber-500/20 p-4 rounded-2xl text-center">
              <p className="text-3xl font-black text-amber-500 mb-1">{summary.terlambat}</p>
              <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">TERLAMBAT</p>
            </div>
            <div className="bg-sky-500/10 border border-sky-500/20 p-4 rounded-2xl text-center">
              <p className="text-3xl font-black text-sky-500 mb-1">{summary.izin}</p>
              <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">IZIN</p>
            </div>
            <div className="bg-orange-500/10 border border-orange-500/20 p-4 rounded-2xl text-center">
              <p className="text-3xl font-black text-orange-400 mb-1">{summary.sakit}</p>
              <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">SAKIT</p>
            </div>
            <div className="bg-rose-500/10 border border-rose-500/20 p-4 rounded-2xl text-center">
              <p className="text-3xl font-black text-rose-500 mb-1">{summary.alpha}</p>
              <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">ALPHA</p>
            </div>
          </div>
        </div>
      )}

      {/* 5. Riwayat Kehadiran Bulanan */}
      {loading ? (
        <div className={`${bentoCard} lg:col-span-4 flex flex-col min-h-[400px] bg-muted/20 border-border`}>
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
            <div className="space-y-2">
              <Skeleton className="h-6 w-56 max-w-full" />
              <Skeleton className="h-4 w-80 max-w-full" />
            </div>
            <div className="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto">
              <Skeleton className="h-11 w-full rounded-xl sm:h-9 sm:w-[110px]" />
              <Skeleton className="h-11 w-full rounded-xl sm:h-9 sm:w-[90px]" />
            </div>
          </div>

          <div className="space-y-4">
            <Skeleton className="h-8 w-full" />
            {Array.from({ length: 5 }).map((_, i) => (
              <Skeleton key={i} className="h-12 w-full" />
            ))}
          </div>
        </div>
      ) : (
        <div className={`${bentoCard} lg:col-span-4 flex flex-col min-h-0`}>
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 shrink-0">
            <div>
              <p className="text-foreground font-black text-lg">Riwayat Kehadiran Bulanan</p>
              <p className="text-xs text-muted-foreground font-semibold">
                Lihat seluruh riwayat jam IN, OUT, beserta hasil foto tap absensi
              </p>
            </div>
            {/* Select Month & Year */}
            <div className="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto">
              <CustomSelect
                value={String(selectedMonth)}
                onChange={(val) => setSelectedMonth(Number(val))}
                options={months.map((m) => ({ value: String(m.value), label: m.name }))}
                className="w-full sm:w-auto"
                triggerClassName="h-11 w-full font-bold text-xs rounded-xl bg-card border-border sm:h-9 sm:min-w-[110px]"
              />
              <CustomSelect
                value={String(selectedYear)}
                onChange={(val) => setSelectedYear(Number(val))}
                options={years.map((y) => ({ value: String(y), label: String(y) }))}
                className="w-full sm:w-auto"
                triggerClassName="h-11 w-full font-bold text-xs rounded-xl bg-card border-border sm:h-9 sm:min-w-[90px]"
              />
            </div>
          </div>

          <div className="overflow-x-auto w-full">
            <table className="w-full text-xs text-left">
              <thead>
                <tr className="text-muted-foreground/60 text-[10px] font-black uppercase tracking-wider border-b border-border">
                  <th className="py-3 px-3">Tanggal</th>
                  <th className="py-3 px-3 text-center">Status</th>
                  <th className="py-3 px-3 text-center">Jam IN / Masuk (Foto)</th>
                  <th className="py-3 px-3 text-center">Jam OUT / Pulang (Foto)</th>
                  <th className="py-3 px-3 text-right">Aksi</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {calendarDays.map((day) => {
                  const st = day.record ? getStatus(day.record.status) : getStatus('ALPHA');

                  return (
                    <tr
                      key={day.dayNum}
                      className={`hover:bg-muted/30 transition-colors ${
                        day.isWeekend ? 'bg-muted/20' : ''
                      } ${day.isFuture ? 'opacity-30 pointer-events-none' : ''}`}
                    >
                      {/* Tanggal */}
                      <td className="py-3 px-3 font-bold text-foreground">
                        {formatDate(day.dateObject)}
                      </td>

                      {/* Status */}
                      <td className="py-3 px-3 text-center">
                        {day.record ? (
                          <Badge className={`px-2.5 py-0.5 rounded-lg text-[10px] font-black uppercase tracking-wider border ${st.bg}`}>
                            <Icon icon={st.icon} className="mr-1 text-xs" />
                            {st.label}
                          </Badge>
                        ) : day.isWeekend ? (
                          <span className="text-[9px] font-black uppercase text-muted-foreground/40 tracking-widest">
                            Akhir Pekan
                          </span>
                        ) : day.isFuture ? (
                          <span className="text-[9px] font-black uppercase text-muted-foreground/30 tracking-widest">
                            Mendatang
                          </span>
                        ) : (
                          <Badge className="px-2.5 py-0.5 rounded-lg text-[10px] font-black uppercase tracking-wider border bg-rose-500/10 text-rose-500 border-rose-500/30">
                            <Icon icon="mingcute:close-circle-fill" className="mr-1 text-xs" />
                            Tanpa Absen
                          </Badge>
                        )}
                      </td>

                      {/* Jam IN */}
                      <td className="py-3 px-3 text-center">
                        {day.record ? (
                          <div className="flex items-center justify-center gap-2">
                            <span className="font-mono font-bold text-foreground">
                              {formatTime(day.record.checkInTime)}
                            </span>
                            {day.record.photoUrl && (
                              <div
                                onClick={() => setActivePreviewImage(day.record.photoUrl)}
                                className="w-8 h-8 rounded-lg overflow-hidden bg-muted border border-border shrink-0 cursor-pointer hover:scale-105 transition-transform"
                              >
                                <img src={day.record.photoUrl} alt="IN" className="w-full h-full object-cover" />
                              </div>
                            )}
                          </div>
                        ) : (
                          <span className="text-muted-foreground/30">-</span>
                        )}
                      </td>

                      {/* Jam OUT */}
                      <td className="py-3 px-3 text-center">
                        {day.record && day.record.checkOutTime ? (
                          <div className="flex items-center justify-center gap-2">
                            <span className="font-mono font-bold text-foreground">
                              {formatTime(day.record.checkOutTime)}
                            </span>
                            {day.record.checkOutPhotoUrl && (
                              <div
                                onClick={() => setActivePreviewImage(day.record.checkOutPhotoUrl)}
                                className="w-8 h-8 rounded-lg overflow-hidden bg-muted border border-border shrink-0 cursor-pointer hover:scale-105 transition-transform"
                              >
                                <img src={day.record.checkOutPhotoUrl} alt="OUT" className="w-full h-full object-cover" />
                              </div>
                            )}
                          </div>
                        ) : (
                          <span className="text-muted-foreground/30">-</span>
                        )}
                      </td>

                      {/* Aksi */}
                      <td className="py-3 px-3 text-right">
                        {day.record ? (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => setSelectedDayLog(day)}
                            className="rounded-xl h-7 text-[10px] font-bold hover:bg-primary/10 hover:text-primary px-2"
                          >
                            {day.record.logs.length} Log Tap
                          </Button>
                        ) : (
                          <span className="text-muted-foreground/30">-</span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* DETAIL LOG TAP MODAL */}
      {selectedDayLog && (
        <Dialog open={!!selectedDayLog} onOpenChange={() => setSelectedDayLog(null)}>
          <DialogContent className="sm:max-w-md p-6 rounded-3xl bg-card border border-border space-y-4">
            <DialogHeader className="p-0 border-none bg-transparent">
              <DialogTitle className="text-lg font-black text-foreground">
                Detail Log Tap Absensi
              </DialogTitle>
              <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mt-0.5">
                Tanggal: {formatDate(selectedDayLog.dateObject)}
              </p>
            </DialogHeader>

            <div className="space-y-3 max-h-60 overflow-y-auto">
              {selectedDayLog.record?.logs?.map((log: any, idx: number) => (
                <div
                  key={log.id || idx}
                  className="flex items-center gap-4 p-3 rounded-2xl bg-muted/30 border border-border text-xs"
                >
                  <div className="w-6 h-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center font-black text-[10px]">
                    {idx + 1}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-mono font-bold text-foreground">{formatTime(log.timestamp)}</p>
                    <p className="text-[10px] text-muted-foreground uppercase font-bold">{log.method || 'FINGERPRINT / FACE'}</p>
                  </div>
                  <Badge className={`text-[9px] font-black uppercase border ${getStatus(log.status).bg}`}>
                    {log.status}
                  </Badge>
                </div>
              ))}
            </div>

            <Button
              variant="outline"
              onClick={() => setSelectedDayLog(null)}
              className="w-full rounded-2xl font-bold text-xs h-10"
            >
              Tutup Detail
            </Button>
          </DialogContent>
        </Dialog>
      )}

      {/* IMAGE PREVIEW LIGHTBOX */}
      {activePreviewImage && (
        <Dialog open={!!activePreviewImage} onOpenChange={() => setActivePreviewImage(null)}>
          <DialogContent className="sm:max-w-3xl p-2 bg-black/90 border border-white/10 rounded-3xl text-center flex items-center justify-center">
            <img
              src={activePreviewImage}
              alt="Preview"
              className="max-w-full max-h-[85vh] object-contain rounded-2xl shadow-2xl"
            />
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
};
