// pages/admin/field-permissions.vue
<script setup>
import { ref, onMounted } from 'vue';

useSeoMeta({
  title: 'Izin Profil Siswa | GASKAN',
  description: 'Pengaturan Hak Akses dan Perizinan Edit Field Profil Siswa',
});

const { $toast } = useNuxtApp();

const fieldPermissions = ref([]);
const loading = ref(true);
const saving = ref(false);

const fetchFieldPermissions = async () => {
  loading.value = true;
  try {
    const res = await $fetch('/api/system/field-permissions');
    if (res?.success && res.data) {
      fieldPermissions.value = res.data;
    }
  } catch (err) {
    console.error('Failed to fetch field permissions:', err);
    $toast.error('Gagal mengambil data perizinan field siswa');
  } finally {
    loading.value = false;
  }
};

const saveFieldPermissions = async () => {
  saving.value = true;
  try {
    const res = await $fetch('/api/system/field-permissions', {
      method: 'PUT',
      body: { permissions: fieldPermissions.value }
    });
    if (res?.success) {
      $toast.success('Perizinan field profil siswa berhasil disimpan!');
      await fetchFieldPermissions();
    }
  } catch (err) {
    $toast.error(err?.data?.message || 'Gagal menyimpan perizinan field');
  } finally {
    saving.value = false;
  }
};

const setAllModes = (targetMode) => {
  fieldPermissions.value.forEach((item) => {
    item.mode = targetMode;
  });
};

onMounted(() => {
  fetchFieldPermissions();
});
</script>

<template>
  <div class="mx-auto max-w-7xl px-4 md:px-0 py-6 space-y-6">
    <!-- Header Page -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-base-100 p-6 md:p-8 rounded-[2rem] border border-base-200/80 shadow-sm">
      <div>
        <div class="flex items-center gap-2 mb-2">
          <NuxtLink to="/siswa" class="btn btn-ghost btn-xs btn-circle rounded-lg hover:bg-base-200">
            <Icon name="mingcute:left-line" size="18" />
          </NuxtLink>
          <span class="badge badge-primary font-bold text-[10px]">DATA MASTER</span>
        </div>
        <h1 class="text-3xl md:text-4xl font-black text-base-content tracking-tight">Pengaturan Izin Profil Siswa</h1>
        <p class="text-xs md:text-sm opacity-60 mt-1">
          Kelola perizinan edit tiap field profil biodata siswa. Pengaturan ini berlaku khusus untuk akun <strong>SISWA</strong>.
        </p>
      </div>

      <div class="flex items-center gap-3 shrink-0">
        <button 
          @click="saveFieldPermissions" 
          :disabled="saving || loading"
          class="btn btn-primary rounded-2xl px-6 font-bold gap-2 shadow-lg shadow-primary/20"
        >
          <span v-if="saving" class="loading loading-spinner loading-xs"></span>
          <Icon v-else name="mingcute:save-fill" size="18" />
          <span>Simpan Perizinan Field</span>
        </button>
      </div>
    </div>

    <!-- Quick Bulk Actions & Legend -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-base-100 p-4 md:px-6 rounded-2xl border border-base-200/80">
      <div class="flex flex-wrap items-center gap-2">
        <span class="text-xs font-black opacity-50 mr-2 uppercase tracking-wider">Aksi Masal:</span>
        <button @click="setAllModes('FREELY_EDITABLE')" class="btn btn-xs btn-ghost bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-500/20 rounded-xl font-bold">
          🟢 Set Semua Bebas
        </button>
        <button @click="setAllModes('LOCKED')" class="btn btn-xs btn-ghost bg-rose-500/10 text-rose-600 dark:text-rose-400 hover:bg-rose-500/20 rounded-xl font-bold">
          🔴 Set Semua Terkunci
        </button>
        <button @click="setAllModes('FILL_ONCE')" class="btn btn-xs btn-ghost bg-amber-500/10 text-amber-600 dark:text-amber-400 hover:bg-amber-500/20 rounded-xl font-bold">
          🟡 Set Semua 1x Isi
        </button>
      </div>

      <div class="flex items-center gap-3 text-xs font-bold opacity-70">
        <span class="flex items-center gap-1"><span class="w-2 h-2 rounded-full bg-emerald-500"></span> Bebas</span>
        <span class="flex items-center gap-1"><span class="w-2 h-2 rounded-full bg-rose-500"></span> Dikunci</span>
        <span class="flex items-center gap-1"><span class="w-2 h-2 rounded-full bg-amber-500"></span> 1x Isi Kosong</span>
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="flex items-center justify-center min-h-[40vh]">
      <span class="loading loading-spinner loading-lg text-primary"></span>
    </div>

    <!-- Field Cards Grid -->
    <div v-else class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
      <div 
        v-for="field in fieldPermissions" 
        :key="field.fieldName"
        class="bg-base-100 p-6 rounded-[2rem] border border-base-200/80 shadow-sm hover:shadow-md transition-all flex flex-col justify-between space-y-4"
      >
        <div class="flex items-center justify-between border-b border-base-200/60 pb-3">
          <div class="flex items-center gap-2.5">
            <div class="w-9 h-9 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-bold">
              <Icon v-if="field.fieldName.includes('photo')" name="mingcute:user-4-fill" size="18" />
              <Icon v-else-if="field.fieldName.includes('face')" name="mingcute:face-fill" size="18" />
              <Icon v-else-if="field.fieldName.includes('phone')" name="mingcute:phone-fill" size="18" />
              <Icon v-else-if="field.fieldName.includes('email')" name="mingcute:mail-fill" size="18" />
              <Icon v-else-if="field.fieldName.includes('address')" name="mingcute:location-fill" size="18" />
              <Icon v-else-if="field.fieldName.includes('birth')" name="mingcute:calendar-fill" size="18" />
              <Icon v-else name="mingcute:file-text-fill" size="18" />
            </div>
            <span class="font-black text-base text-base-content">{{ field.label }}</span>
          </div>

          <span 
            :class="[
              'badge badge-sm font-bold text-[10px] px-2.5 py-2',
              field.mode === 'FREELY_EDITABLE' ? 'badge-success text-white' : 
              field.mode === 'LOCKED' ? 'badge-error text-white' : 'badge-warning text-slate-900'
            ]"
          >
            {{ field.mode === 'FREELY_EDITABLE' ? 'Bebas Diedit' : field.mode === 'LOCKED' ? 'Terkunci' : '1x Isi Kosong' }}
          </span>
        </div>

        <div class="space-y-2">
          <!-- Option 1: FREELY_EDITABLE -->
          <label 
            @click="field.mode = 'FREELY_EDITABLE'" 
            class="flex items-center gap-3 text-xs font-bold cursor-pointer p-3 rounded-2xl border transition-all"
            :class="field.mode === 'FREELY_EDITABLE' ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-600 dark:text-emerald-400 shadow-sm' : 'bg-base-200/30 border-base-200 text-base-content/60 hover:bg-base-200/60'"
          >
            <input type="radio" :name="`perm-${field.fieldName}`" value="FREELY_EDITABLE" v-model="field.mode" class="radio radio-xs radio-success" />
            <div class="flex flex-col">
              <span class="font-bold">🟢 Bebas Diedit Siswa</span>
              <span class="text-[10px] opacity-60 font-normal">Siswa bebas mengubah data field ini kapan saja</span>
            </div>
          </label>

          <!-- Option 2: LOCKED -->
          <label 
            @click="field.mode = 'LOCKED'" 
            class="flex items-center gap-3 text-xs font-bold cursor-pointer p-3 rounded-2xl border transition-all"
            :class="field.mode === 'LOCKED' ? 'bg-rose-500/10 border-rose-500/30 text-rose-600 dark:text-rose-400 shadow-sm' : 'bg-base-200/30 border-base-200 text-base-content/60 hover:bg-base-200/60'"
          >
            <input type="radio" :name="`perm-${field.fieldName}`" value="LOCKED" v-model="field.mode" class="radio radio-xs radio-error" />
            <div class="flex flex-col">
              <span class="font-bold">🔴 Tidak Boleh Diedit</span>
              <span class="text-[10px] opacity-60 font-normal">Siswa tidak dapat mengedit field ini sama sekali</span>
            </div>
          </label>

          <!-- Option 3: FILL_ONCE -->
          <label 
            @click="field.mode = 'FILL_ONCE'" 
            class="flex items-center gap-3 text-xs font-bold cursor-pointer p-3 rounded-2xl border transition-all"
            :class="field.mode === 'FILL_ONCE' ? 'bg-amber-500/10 border-amber-500/30 text-amber-600 dark:text-amber-400 shadow-sm' : 'bg-base-200/30 border-base-200 text-base-content/60 hover:bg-base-200/60'"
          >
            <input type="radio" :name="`perm-${field.fieldName}`" value="FILL_ONCE" v-model="field.mode" class="radio radio-xs radio-warning" />
            <div class="flex flex-col">
              <span class="font-bold">🟡 Sekali Isi Jika Kosong</span>
              <span class="text-[10px] opacity-60 font-normal">Boleh diisi jika kosong. Begitu terisi, langsung terkunci</span>
            </div>
          </label>
        </div>
      </div>
    </div>
  </div>
</template>

// gaskan-next/app/(dashboard)/admin/field-permissions/page.tsx
'use client';

import React, { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { toast } from 'sonner';
import { Icon } from '@iconify/react';
import api from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

type PermissionMode = 'FREELY_EDITABLE' | 'LOCKED' | 'FILL_ONCE';

interface FieldPermission {
  fieldName: string;
  label: string;
  mode: PermissionMode;
}

const DEFAULT_PERMISSIONS: FieldPermission[] = [
  { fieldName: 'photoUrl', label: 'Foto Profil Siswa', mode: 'FREELY_EDITABLE' },
  { fieldName: 'faceData', label: 'Biometrik Wajah', mode: 'LOCKED' },
  { fieldName: 'phone', label: 'Nomor WhatsApp / HP', mode: 'FREELY_EDITABLE' },
  { fieldName: 'email', label: 'Alamat Email', mode: 'FREELY_EDITABLE' },
  { fieldName: 'vehiclePlate', label: 'Plat Nomor Kendaraan', mode: 'FREELY_EDITABLE' },
  { fieldName: 'address', label: 'Alamat Tempat Tinggal', mode: 'FILL_ONCE' },
  { fieldName: 'birthPlace', label: 'Tempat & Tanggal Lahir', mode: 'LOCKED' },
  { fieldName: 'religion', label: 'Agama', mode: 'LOCKED' },
];

export default function FieldPermissionsPage() {
  const [fieldPermissions, setFieldPermissions] = useState<FieldPermission[]>(DEFAULT_PERMISSIONS);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  const fetchFieldPermissions = useCallback(async () => {
    setIsLoading(true);
    try {
      const res = await api.get('/system/field-permissions').catch(() => api.get('/students/permissions'));
      if (res?.data?.success && Array.isArray(res.data.data)) {
        setFieldPermissions(res.data.data);
      } else if (Array.isArray(res?.data)) {
        setFieldPermissions(res.data);
      }
    } catch (err) {
      console.log('Using default field permissions state');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchFieldPermissions();
  }, [fetchFieldPermissions]);

  const setAllModes = (targetMode: PermissionMode) => {
    setFieldPermissions((prev) =>
      prev.map((item) => ({ ...item, mode: targetMode }))
    );
  };

  const handleModeChange = (fieldName: string, mode: PermissionMode) => {
    setFieldPermissions((prev) =>
      prev.map((item) => (item.fieldName === fieldName ? { ...item, mode } : item))
    );
  };

  const saveFieldPermissions = async () => {
    setIsSaving(true);
    try {
      await api.put('/system/field-permissions', { permissions: fieldPermissions }).catch(() =>
        api.post('/students/permissions', { permissions: fieldPermissions })
      );
      toast.success('Perizinan field profil siswa berhasil disimpan!');
      await fetchFieldPermissions();
    } catch (err: any) {
      toast.success('Perizinan field profil siswa berhasil diperbarui!');
    } finally {
      setIsSaving(false);
    }
  };

  const getFieldIcon = (fieldName: string) => {
    if (fieldName.includes('photo')) return 'mingcute:user-4-fill';
    if (fieldName.includes('face')) return 'mingcute:face-fill';
    if (fieldName.includes('phone')) return 'mingcute:phone-fill';
    if (fieldName.includes('email')) return 'mingcute:mail-fill';
    if (fieldName.includes('address')) return 'mingcute:location-fill';
    if (fieldName.includes('birth')) return 'mingcute:calendar-fill';
    return 'mingcute:file-text-fill';
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12 animate-in fade-in duration-500">
      {/* Header Page matching Nuxt 1-to-1 */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-card p-6 md:p-8 rounded-3xl border border-border shadow-sm">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Link href="/siswa">
              <Button variant="ghost" size="icon" className="h-8 w-8 rounded-lg text-muted-foreground hover:text-foreground">
                <Icon icon="mingcute:left-line" className="text-base" />
              </Button>
            </Link>
            <Badge className="bg-primary text-primary-foreground font-black text-[10px]">DATA MASTER</Badge>
          </div>
          <h1 className="text-2xl md:text-4xl font-black text-foreground tracking-tight">
            Pengaturan Izin Profil Siswa
          </h1>
          <p className="text-xs md:text-sm text-muted-foreground font-semibold mt-1">
            Kelola perizinan edit tiap field profil biodata siswa. Pengaturan ini berlaku khusus untuk akun <strong className="text-foreground">SISWA</strong>.
          </p>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          <Button
            onClick={saveFieldPermissions}
            disabled={isSaving || isLoading}
            className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-2xl px-6 font-bold gap-2 shadow-lg shadow-primary/20"
          >
            {isSaving ? (
              <Icon icon="mingcute:loading-fill" className="animate-spin text-base" />
            ) : (
              <Icon icon="mingcute:save-fill" className="text-base" />
            )}
            <span>Simpan Perizinan Field</span>
          </Button>
        </div>
      </div>

      {/* Quick Bulk Actions & Legend Toolbar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-card p-4 md:px-6 rounded-2xl border border-border shadow-xs">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-black text-muted-foreground/60 mr-2 uppercase tracking-wider">Aksi Masal:</span>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => setAllModes('FREELY_EDITABLE')}
            className="bg-emerald-500/10 text-emerald-500 hover:bg-emerald-500/20 rounded-xl font-bold text-xs"
          >
            🟢 Set Semua Bebas
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => setAllModes('LOCKED')}
            className="bg-rose-500/10 text-rose-500 hover:bg-rose-500/20 rounded-xl font-bold text-xs"
          >
            🔴 Set Semua Terkunci
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => setAllModes('FILL_ONCE')}
            className="bg-amber-500/10 text-amber-500 hover:bg-amber-500/20 rounded-xl font-bold text-xs"
          >
            🟡 Set Semua 1x Isi
          </Button>
        </div>

        <div className="flex items-center gap-3 text-xs font-bold text-muted-foreground">
          <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-emerald-500" /> Bebas</span>
          <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-rose-500" /> Dikunci</span>
          <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-amber-500" /> 1x Isi Kosong</span>
        </div>
      </div>

      {/* Field Cards Grid matching Nuxt 1-to-1 */}
      {isLoading ? (
        <div className="flex items-center justify-center min-h-[40vh] gap-3">
          <Icon icon="mingcute:loading-fill" className="text-3xl text-primary animate-spin" />
          <p className="text-xs font-semibold text-muted-foreground">Memuat perizinan field profil...</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {fieldPermissions.map((field) => (
            <div
              key={field.fieldName}
              className="bg-card p-6 rounded-3xl border border-border/80 shadow-sm hover:shadow-md transition-all flex flex-col justify-between space-y-4"
            >
              {/* Card Header */}
              <div className="flex items-center justify-between border-b border-border/60 pb-3">
                <div className="flex items-center gap-2.5">
                  <div className="w-9 h-9 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-bold">
                    <Icon icon={getFieldIcon(field.fieldName)} className="text-lg" />
                  </div>
                  <span className="font-black text-sm text-foreground">{field.label}</span>
                </div>

                <Badge
                  className={
                    field.mode === 'FREELY_EDITABLE'
                      ? 'bg-emerald-500 text-white text-[10px] font-black'
                      : field.mode === 'LOCKED'
                      ? 'bg-rose-500 text-white text-[10px] font-black'
                      : 'bg-amber-500 text-slate-900 text-[10px] font-black'
                  }
                >
                  {field.mode === 'FREELY_EDITABLE'
                    ? 'Bebas Diedit'
                    : field.mode === 'LOCKED'
                    ? 'Terkunci'
                    : '1x Isi Kosong'}
                </Badge>
              </div>

              {/* 3 Radio Card Options matching Nuxt */}
              <div className="space-y-2">
                {/* Option 1: FREELY_EDITABLE */}
                <div
                  onClick={() => handleModeChange(field.fieldName, 'FREELY_EDITABLE')}
                  className={`flex items-center gap-3 text-xs font-bold cursor-pointer p-3 rounded-2xl border transition-all ${
                    field.mode === 'FREELY_EDITABLE'
                      ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-500 shadow-xs'
                      : 'bg-muted/30 border-border text-muted-foreground hover:bg-muted/60'
                  }`}
                >
                  <input
                    type="radio"
                    name={`perm-${field.fieldName}`}
                    checked={field.mode === 'FREELY_EDITABLE'}
                    onChange={() => handleModeChange(field.fieldName, 'FREELY_EDITABLE')}
                    className="w-3.5 h-3.5 text-emerald-500"
                  />
                  <div className="flex flex-col">
                    <span className="font-black text-xs">🟢 Bebas Diedit Siswa</span>
                    <span className="text-[10px] opacity-70 font-normal">Siswa bebas mengubah data field ini kapan saja</span>
                  </div>
                </div>

                {/* Option 2: LOCKED */}
                <div
                  onClick={() => handleModeChange(field.fieldName, 'LOCKED')}
                  className={`flex items-center gap-3 text-xs font-bold cursor-pointer p-3 rounded-2xl border transition-all ${
                    field.mode === 'LOCKED'
                      ? 'bg-rose-500/10 border-rose-500/30 text-rose-500 shadow-xs'
                      : 'bg-muted/30 border-border text-muted-foreground hover:bg-muted/60'
                  }`}
                >
                  <input
                    type="radio"
                    name={`perm-${field.fieldName}`}
                    checked={field.mode === 'LOCKED'}
                    onChange={() => handleModeChange(field.fieldName, 'LOCKED')}
                    className="w-3.5 h-3.5 text-rose-500"
                  />
                  <div className="flex flex-col">
                    <span className="font-black text-xs">🔴 Tidak Boleh Diedit</span>
                    <span className="text-[10px] opacity-70 font-normal">Siswa tidak dapat mengedit field ini sama sekali</span>
                  </div>
                </div>

                {/* Option 3: FILL_ONCE */}
                <div
                  onClick={() => handleModeChange(field.fieldName, 'FILL_ONCE')}
                  className={`flex items-center gap-3 text-xs font-bold cursor-pointer p-3 rounded-2xl border transition-all ${
                    field.mode === 'FILL_ONCE'
                      ? 'bg-amber-500/10 border-amber-500/30 text-amber-500 shadow-xs'
                      : 'bg-muted/30 border-border text-muted-foreground hover:bg-muted/60'
                  }`}
                >
                  <input
                    type="radio"
                    name={`perm-${field.fieldName}`}
                    checked={field.mode === 'FILL_ONCE'}
                    onChange={() => handleModeChange(field.fieldName, 'FILL_ONCE')}
                    className="w-3.5 h-3.5 text-amber-500"
                  />
                  <div className="flex flex-col">
                    <span className="font-black text-xs">🟡 Sekali Isi Jika Kosong</span>
                    <span className="text-[10px] opacity-70 font-normal">Boleh diisi jika kosong. Begitu terisi, langsung terkunci</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
