// pages/config/device/index.vue
<script setup>
import { ref, onMounted, computed, onUnmounted } from 'vue';
const { $toast } = useNuxtApp();

useSeoMeta({
  title: 'Konfigurasi Mesin & Gerbang | GASKAN',
  description: 'Pengaturan beberapa perangkat absensi Hikvision',
});

const devices = ref([]);
const loading = ref(true);
const saving = ref(false);
const testingId = ref(null);

// Late & Minimal Out setting state
const lateHour = ref(7);
const lateMinute = ref(0);
const minOutHour = ref(12);
const minOutMinute = ref(0);
const onsiteLimitHour = ref(21);
const savingSettings = ref(false);

const lateTime = computed({
  get() {
    const h = String(lateHour.value).padStart(2, '0');
    const m = String(lateMinute.value).padStart(2, '0');
    return `${h}:${m}`;
  },
  set(val) {
    if (val) {
      const [h, m] = val.split(':');
      lateHour.value = Number(h);
      lateMinute.value = Number(m);
    }
  }
});

const minOutTime = computed({
  get() {
    const h = String(minOutHour.value).padStart(2, '0');
    const m = String(minOutMinute.value).padStart(2, '0');
    return `${h}:${m}`;
  },
  set(val) {
    if (val) {
      const [h, m] = val.split(':');
      minOutHour.value = Number(h);
      minOutMinute.value = Number(m);
    }
  }
});

// Modal state
const showModal = ref(false);
const isEdit = ref(false);
const currentId = ref(null);
const form = ref({
  name: '',
  location: '',
  url: '',
  username: '',
  password: '',
  poolingInterval: 30,
  isActive: true,
});

const fetchDevices = async () => {
  loading.value = true;
  try {
    const data = await $fetch('/api/device');
    if (data?.success) {
      devices.value = data.data || [];
    }
  } catch (e) {
    console.error('Failed to fetch devices:', e);
    $toast.error('Gagal mengambil daftar perangkat');
  } finally {
    loading.value = false;
  }
};

const fetchSettings = async () => {
  try {
    const res = await $fetch('/api/system/settings');
    if (res?.success && res.data) {
      lateHour.value = res.data.lateHour;
      lateMinute.value = res.data.lateMinute;
      minOutHour.value = res.data.minOutHour !== undefined ? res.data.minOutHour : 12;
      minOutMinute.value = res.data.minOutMinute !== undefined ? res.data.minOutMinute : 0;
      onsiteLimitHour.value = res.data.onsiteLimitHour !== undefined ? res.data.onsiteLimitHour : 21;
    }
  } catch (e) {
    console.error('Failed to fetch settings:', e);
  }
};

onMounted(async () => {
  await fetchDevices();
  await fetchSettings();
});

const openAddModal = () => {
  isEdit.value = false;
  currentId.value = null;
  form.value = {
    name: '',
    location: '',
    url: '',
    username: '',
    password: '',
    poolingInterval: 30,
    isActive: true,
  };
  showModal.value = true;
};

const openEditModal = (device) => {
  isEdit.value = true;
  currentId.value = device.id;
  form.value = {
    name: device.name,
    location: device.location,
    url: device.url,
    username: device.username,
    password: '', // Biarkan kosong
    poolingInterval: device.poolingInterval,
    isActive: device.isActive,
  };
  showModal.value = true;
};

const handleSave = async () => {
  if (!form.value.name || !form.value.location || !form.value.url || !form.value.username) {
    $toast.error('Harap isi semua kolom wajib!');
    return;
  }
  if (!isEdit.value && !form.value.password) {
    $toast.error('Password wajib diisi untuk perangkat baru!');
    return;
  }
  if (form.value.poolingInterval < 1) {
    $toast.error('Interval sinkronisasi tidak boleh kurang dari 1 detik!');
    return;
  }

  saving.value = true;
  try {
    const payload = { ...form.value };
    if (isEdit.value && !payload.password) {
      delete payload.password;
    }

    if (isEdit.value) {
      await $fetch(`/api/device/${currentId.value}`, {
        method: 'PUT',
        body: payload,
      });
      $toast.success('Perangkat berhasil diperbarui');
    } else {
      await $fetch('/api/device', {
        method: 'POST',
        body: payload,
      });
      $toast.success('Perangkat berhasil ditambahkan');
    }
    showModal.value = false;
    await fetchDevices();
  } catch (e) {
    console.error('Save failed:', e);
    $toast.error(e.data?.message || 'Gagal menyimpan perangkat');
  } finally {
    saving.value = false;
  }
};

const handleDelete = async (id) => {
  if (!confirm('Apakah Anda yakin ingin menghapus perangkat ini?')) return;
  
  try {
    await $fetch(`/api/device/${id}`, {
      method: 'DELETE',
    });
    $toast.success('Perangkat berhasil dihapus');
    await fetchDevices();
  } catch (e) {
    console.error('Delete failed:', e);
    $toast.error('Gagal menghapus perangkat');
  }
};

const testConnection = async (device) => {
  testingId.value = device.id;
  try {
    const res = await $fetch('/api/device/test-connection', {
      method: 'POST',
      body: {
        url: device.url,
        username: device.username,
        password: 'mock-password',
      },
    });
    if (res?.success) {
      $toast.success(`${device.name}: ${res.message}`);
    } else {
      $toast.error(`${device.name}: ${res.message || 'Koneksi gagal'}`);
    }
  } catch (e) {
    $toast.error(`${device.name}: ${e.data?.message || 'Gagal terhubung'}`);
  } finally {
    testingId.value = null;
  }
};

const testFormConnection = async () => {
  if (!form.value.url || !form.value.username) {
    $toast.error('Harap isi URL dan Username untuk tes koneksi');
    return;
  }
  if (form.value.poolingInterval < 1) {
    $toast.error('Interval sinkronisasi tidak boleh kurang dari 1 detik!');
    return;
  }
  
  saving.value = true;
  try {
    const res = await $fetch('/api/device/test-connection', {
      method: 'POST',
      body: {
        url: form.value.url,
        username: form.value.username,
        password: form.value.password || 'mock-password',
      },
    });
    if (res?.success) {
      $toast.success('Koneksi berhasil!');
    } else {
      $toast.error(res?.message || 'Koneksi gagal');
    }
  } catch (e) {
    $toast.error(e.data?.message || 'Gagal menghubungkan perangkat');
  } finally {
    saving.value = false;
  }
};

const settingPushId = ref(null);

const handleSetupPush = async (device) => {
  const guessedBackend = `${window.location.protocol}//${window.location.hostname}:5000`;
  const serverUrl = prompt(
    `Masukkan Alamat IP/Port Server GASKAN (IP Backend) agar perangkat bisa mengirim data presensi secara real-time (Push Mode):`,
    guessedBackend
  );
  
  if (!serverUrl) return;
  
  settingPushId.value = device.id;
  try {
    const res = await $fetch(`/api/device/${device.id}`, {
      method: 'POST',
      body: { serverUrl }
    });
    
    if (res?.success) {
      $toast.success(res.message);
    } else {
      $toast.error(res.message || 'Gagal konfigurasi push mode');
    }
  } catch (e) {
    console.error('Setup push failed:', e);
    $toast.error(e.data?.message || 'Gagal terhubung ke mesin untuk setup push');
  } finally {
    settingPushId.value = null;
  }
};

const toggleDeviceStatus = async (device) => {
  try {
    await $fetch(`/api/device/${device.id}`, {
      method: 'PUT',
      body: { isActive: !device.isActive },
    });
    device.isActive = !device.isActive;
    $toast.success(`Status ${device.name} berhasil diperbarui`);
  } catch (e) {
    $toast.error('Gagal mengubah status perangkat');
  }
};

const saveLateSettings = async () => {
  savingSettings.value = true;
  try {
    const res = await $fetch('/api/system/settings', {
      method: 'PUT',
      body: {
        lateHour: Number(lateHour.value),
        lateMinute: Number(lateMinute.value),
        minOutHour: Number(minOutHour.value),
        minOutMinute: Number(minOutMinute.value),
        onsiteLimitHour: Number(onsiteLimitHour.value)
      }
    });
    if (res?.success) {
      $toast.success('Pengaturan parameter kehadiran berhasil disimpan');
    }
  } catch (e) {
    console.error('Save settings failed:', e);
    $toast.error(e.data?.message || 'Gagal menyimpan pengaturan');
  } finally {
    savingSettings.value = false;
  }
};

const router = useRouter();

const showDeviceStats = (device) => {
  router.push(`/config/device/${device.id}`);
};
</script>

<template>
  <div class="max-w-7xl mx-auto px-4 md:px-0 py-6">
    <!-- Header -->
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
      <div>
        <h1 class="text-3xl font-extrabold tracking-tight text-base-content mb-2 flex items-center gap-3">
          Mesin & Gerbang Presensi
          <span class="px-2.5 py-1 text-xs font-bold bg-primary/10 text-primary border border-primary/20 rounded-full">
            {{ devices.length }} Perangkat
          </span>
        </h1>
        <p class="text-base-content/60 text-sm">Kelola beberapa mesin absensi Hikvision beserta nama dan lokasinya untuk pelacakan gerbang pintu masuk.</p>
      </div>

      <button @click="openAddModal" class="btn btn-primary rounded-2xl px-6 h-12 shadow-lg shadow-primary/25 hover:scale-[1.02] active:scale-[0.98] transition-all">
        <Icon name="mingcute:plus-fill" size="20" class="mr-1.5" />
        Tambah Perangkat
      </button>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div v-for="n in 3" :key="n" class="bg-base-100/60 border border-base-200 rounded-3xl p-6 shadow-sm space-y-4 animate-pulse">
        <div class="h-6 w-1/2 bg-base-300 rounded-lg"></div>
        <div class="h-4 w-1/3 bg-base-200 rounded-lg"></div>
        <div class="space-y-2 pt-4">
          <div class="h-4 bg-base-200 rounded"></div>
          <div class="h-4 bg-base-200 rounded w-5/6"></div>
        </div>
        <div class="h-10 bg-base-300 rounded-2xl w-full pt-4"></div>
      </div>
    </div>

    <!-- Empty State -->
    <div v-else-if="devices.length === 0" class="bg-base-100/60 border border-base-200/80 backdrop-blur-md rounded-3xl p-16 text-center max-w-lg mx-auto shadow-sm">
      <div class="w-16 h-16 rounded-2xl bg-base-200/50 border border-base-300 flex items-center justify-center mx-auto mb-5">
        <Icon name="mingcute:chip-line" size="32" class="text-base-content/40" />
      </div>
      <h3 class="text-xl font-bold text-base-content mb-2">Belum ada perangkat terdaftar</h3>
      <p class="text-base-content/50 text-sm mb-6">Tambahkan mesin sidik jari/wajah Hikvision pertama Anda untuk mulai sinkronisasi data kehadiran siswa secara otomatis.</p>
      <button @click="openAddModal" class="btn btn-primary rounded-xl px-5 btn-sm h-10">
        <Icon name="mingcute:plus-fill" size="16" class="mr-1" />
        Daftarkan Mesin
      </button>
    </div>

    <!-- Grid of Devices -->
    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div v-for="d in devices" :key="d.id" class="bg-base-100 border border-base-200/80 hover:border-primary/30 rounded-3xl p-6 shadow-sm hover:shadow-lg transition-all duration-300 flex flex-col justify-between group relative overflow-hidden">
        <!-- Decoration light glow -->
        <div class="absolute -top-12 -right-12 w-28 h-28 rounded-full bg-primary/5 blur-2xl group-hover:bg-primary/10 transition-colors duration-500 pointer-events-none"></div>

        <div>
          <!-- Header Card -->
          <div class="flex justify-between items-start mb-4">
            <div>
              <h2 class="text-xl font-bold text-base-content group-hover:text-primary transition-colors">{{ d.name }}</h2>
              <div class="flex items-center gap-1 text-xs text-base-content/50 mt-1 font-medium">
                <Icon name="mingcute:location-fill" class="text-primary/70 shrink-0" size="14" />
                <span>{{ d.location }}</span>
              </div>
            </div>
            <!-- Toggle switch to activate/deactivate -->
            <input 
              type="checkbox" 
              class="toggle toggle-primary toggle-sm" 
              :checked="d.isActive" 
              @change="toggleDeviceStatus(d)"
            />
          </div>

          <!-- Divider -->
          <div class="border-t border-base-200/60 my-4"></div>

          <!-- Connection Stats -->
          <div class="space-y-2.5 text-sm font-medium text-base-content/70">
            <div class="flex items-center gap-2">
              <Icon name="mingcute:link-2-line" size="16" class="opacity-60" />
              <span class="font-mono text-xs truncate bg-base-200/50 px-2 py-0.5 rounded-lg">{{ d.url }}</span>
            </div>
            <div class="flex items-center gap-2">
              <Icon name="mingcute:user-3-line" size="16" class="opacity-60" />
              <span>Username: <span class="font-semibold text-base-content">{{ d.username }}</span></span>
            </div>
            <div class="flex items-center gap-2">
              <Icon name="mingcute:signal-fill" size="16" class="opacity-60" />
              <span>Mode: <span class="font-semibold text-primary">Push Webhook (Real-time)</span></span>
            </div>
            <div class="flex items-center gap-2">
              <Icon name="mingcute:time-line" size="16" class="opacity-60" />
              <span>Interval: <span class="font-semibold text-base-content">{{ d.poolingInterval }} detik</span></span>
            </div>
          </div>
        </div>

        <!-- Footer Actions -->
        <div class="mt-6 pt-4 border-t border-base-200/60 space-y-3">
          <div class="flex gap-2">
            <button 
              @click="testConnection(d)" 
              :disabled="testingId === d.id"
              class="btn btn-outline btn-primary btn-sm rounded-xl px-3 flex-1 h-9"
            >
              <span v-if="testingId === d.id" class="loading loading-spinner loading-xs mr-1"></span>
              <Icon v-else name="mingcute:radar-fill" size="14" class="mr-1" />
              Test Koneksi
            </button>
            <button 
              @click="handleSetupPush(d)" 
              :disabled="settingPushId === d.id"
              class="btn btn-primary btn-sm rounded-xl px-3 flex-1 h-9 text-xs"
            >
              <span v-if="settingPushId === d.id" class="loading loading-spinner loading-xs mr-1"></span>
              <Icon v-else name="mingcute:upload-2-fill" size="14" class="mr-1" />
              Setup Push
            </button>
          </div>
          
          <div class="flex items-center justify-between">
            <span class="text-xs text-base-content/40 font-medium">Aksi Perangkat:</span>
            <div class="flex items-center gap-1.5">
              <NuxtLink :to="`/config/device/${d.id}`" class="btn btn-square btn-ghost btn-sm rounded-xl border border-base-200 hover:border-success/20 hover:text-success" title="Statistik & Kapasitas Alat">
                <Icon name="mingcute:chart-bar-fill" size="16" />
              </NuxtLink>
              <button @click="openEditModal(d)" class="btn btn-square btn-ghost btn-sm rounded-xl border border-base-200 hover:border-primary/20 hover:text-primary">
                <Icon name="mingcute:pencil-fill" size="16" />
              </button>
              <button @click="handleDelete(d.id)" class="btn btn-square btn-ghost btn-sm rounded-xl border border-base-200 hover:border-error/20 hover:text-error">
                <Icon name="mingcute:delete-2-fill" size="16" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Attendance Parameters Configuration Card -->
    <div class="mt-12 max-w-xl bg-base-100 border border-base-200/80 rounded-3xl p-6 md:p-8 shadow-md relative overflow-hidden group">
      <!-- Glow decoration -->
      <div class="absolute -top-12 -right-12 w-28 h-28 rounded-full bg-primary/5 blur-2xl group-hover:bg-primary/10 transition-colors duration-500"></div>

      <div class="flex items-start gap-4 mb-6">
        <div class="w-12 h-12 rounded-2xl bg-warning/10 border border-warning/20 flex items-center justify-center text-warning shrink-0">
          <Icon name="mingcute:time-fill" size="24" />
        </div>
        <div>
          <h2 class="text-xl font-bold text-base-content">Parameter Kehadiran & On-Site</h2>
          <p class="text-xs text-base-content/50 mt-1">Konfigurasi batas waktu keterlambatan presensi masuk dan jam batas pembersihan otomatis daftar siswa aktif di area (On-Site).</p>
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <div class="form-control">
          <label class="label"><span class="label-text font-bold text-base-content/80">Batas Waktu Masuk <span class="text-error">*</span></span></label>
          <input 
            v-model="lateTime" 
            type="time" 
            class="input input-bordered w-full rounded-xl font-bold text-sm h-10 border-base-300"
          />
          <span class="text-[10px] text-base-content/40 mt-1 pl-1">Masuk setelah jam ini otomatis "TERLAMBAT"</span>
        </div>

        <div class="form-control">
          <label class="label"><span class="label-text font-bold text-base-content/80">Batas Minimal Jam Pulang <span class="text-error">*</span></span></label>
          <input 
            v-model="minOutTime" 
            type="time" 
            class="input input-bordered w-full rounded-xl font-bold text-sm h-10 border-base-300"
          />
          <span class="text-[10px] text-base-content/40 mt-1 pl-1">Scan sebelum jam ini tidak dianggap pulang (lastOut)</span>
        </div>

        <div class="form-control">
          <label class="label"><span class="label-text font-bold text-base-content/80">Batas Jam Auto-Flush On-Site <span class="text-error">*</span></span></label>
          <select v-model.number="onsiteLimitHour" class="select select-bordered w-full rounded-xl font-bold text-sm bg-base-100 border-base-300 h-10 focus:outline-none focus:border-primary">
            <option v-for="h in 24" :key="h-1" :value="h-1">
              Jam {{ String(h-1).padStart(2, '0') }}:00 WIB
            </option>
          </select>
          <span class="text-[10px] text-base-content/40 mt-1 pl-1">Siswa otomatis dihapus dari On-Site setelah jam ini</span>
        </div>
      </div>

      <div class="flex justify-end pt-4 border-t border-base-200/60">
        <button 
          @click="saveLateSettings" 
          :disabled="savingSettings" 
          class="btn btn-primary rounded-xl px-5 h-10 shadow-lg shadow-primary/25 hover:scale-[1.02] active:scale-[0.98] transition-all text-sm font-bold"
        >
          <span v-if="savingSettings" class="loading loading-spinner loading-xs mr-1"></span>
          <Icon v-else name="mingcute:check-fill" size="16" class="mr-1" />
          Simpan Pengaturan
        </button>
      </div>
    </div>

    <!-- Frosted Glass CRUD Modal -->
    <Teleport to="body">
      <div v-if="showModal" class="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
        <div class="bg-base-100 border border-base-200/80 rounded-[2rem] p-6 md:p-8 w-full max-w-lg shadow-2xl relative animate-scale-in max-h-[90vh] overflow-y-auto">
          <!-- Close Button -->
          <button @click="showModal = false" class="btn btn-square btn-ghost btn-sm rounded-xl absolute top-6 right-6">
            <Icon name="mingcute:close-line" size="20" />
          </button>

          <h3 class="text-xl font-extrabold text-base-content mb-1 flex items-center gap-2">
            <Icon :name="isEdit ? 'mingcute:pencil-fill' : 'mingcute:plus-fill'" class="text-primary" />
            {{ isEdit ? 'Edit Perangkat' : 'Daftarkan Perangkat Baru' }}
          </h3>
          <p class="text-xs text-base-content/50 mb-6">Atur rincian mesin absensi Anda untuk diletakkan pada gerbang penyeberangan masuk siswa.</p>

          <!-- Form fields -->
          <div class="space-y-4">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="form-control">
                <label class="label"><span class="label-text font-bold text-base-content/80">Nama Perangkat <span class="text-error">*</span></span></label>
                <input v-model="form.name" type="text" placeholder="Misal: Gerbang Depan" class="input input-bordered w-full rounded-xl font-bold text-sm bg-base-100 border-base-300 h-10" />
              </div>
              <div class="form-control">
                <label class="label"><span class="label-text font-bold text-base-content/80">Lokasi / Gate <span class="text-error">*</span></span></label>
                <input v-model="form.location" type="text" placeholder="Misal: Lobi Depan" class="input input-bordered w-full rounded-xl font-bold text-sm bg-base-100 border-base-300 h-10" />
              </div>
            </div>

            <div class="form-control">
              <label class="label"><span class="label-text font-bold text-base-content/80">Base URL Mesin <span class="text-error">*</span></span></label>
              <input v-model="form.url" type="text" placeholder="http://192.168.1.64" class="input input-bordered w-full rounded-xl font-mono text-sm bg-base-100 border-base-300 h-10" />
              <span class="text-[10px] text-base-content/40 mt-1 italic pl-1">Gunakan alamat IP lokal mesin yang statis</span>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="form-control">
                <label class="label"><span class="label-text font-bold text-base-content/80">Username <span class="text-error">*</span></span></label>
                <input v-model="form.username" type="text" placeholder="admin" class="input input-bordered w-full rounded-xl font-bold text-sm bg-base-100 border-base-300 h-10" />
              </div>
              <div class="form-control">
                <label class="label"><span class="label-text font-bold text-base-content/80">Password <span v-if="!isEdit" class="text-error">*</span></span></label>
                <input v-model="form.password" type="password" :placeholder="isEdit ? '•••••••• (Biarkan kosong)' : 'Password mesin'" class="input input-bordered w-full rounded-xl font-bold text-sm bg-base-100 border-base-300 h-10" />
              </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 items-center pt-2">
              <div class="form-control">
                <label class="label"><span class="label-text font-bold text-base-content/80">Interval Sinkronisasi (Detik) <span class="text-error">*</span></span></label>
                <input v-model.number="form.poolingInterval" type="number" min="1" class="input input-bordered w-full rounded-xl font-bold text-sm bg-base-100 border-base-300 h-10" />
              </div>
              <div class="form-control flex flex-row items-center justify-between border border-base-200 rounded-xl px-4 py-2 mt-8">
                <div class="flex flex-col">
                  <span class="text-sm font-bold text-base-content">Status Aktif</span>
                  <span class="text-xs text-base-content/50">Aktifkan sinkronisasi wajah dan event</span>
                </div>
                <input type="checkbox" class="toggle toggle-primary toggle-sm" v-model="form.isActive" />
              </div>
            </div>
          </div>

          <!-- Action buttons inside modal -->
          <div class="flex flex-col sm:flex-row gap-3 pt-6">
            <button @click="testFormConnection" :disabled="saving" class="btn btn-outline btn-primary rounded-xl px-5 flex-1 h-10 font-bold text-sm">
              <Icon name="mingcute:radar-line" size="18" class="mr-1" />
              Test Koneksi
            </button>
            <div class="flex gap-2 flex-1">
              <button @click="showModal = false" class="btn btn-ghost rounded-xl px-4 flex-1 h-10 font-bold text-sm">Batal</button>
              <button @click="handleSave" :disabled="saving" class="btn btn-primary rounded-xl px-5 flex-1 h-10 shadow-lg shadow-primary/25 font-bold text-sm">
                <span v-if="saving" class="loading loading-spinner loading-xs mr-1"></span>
                <Icon v-else name="mingcute:check-fill" size="18" class="mr-1" />
                Simpan
              </button>
            </div>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
.animate-scale-in {
  animation: scaleIn 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
}
@keyframes scaleIn {
  from {
    opacity: 0;
    transform: scale(0.95) translateY(10px);
  }
  to {
    opacity: 1;
    transform: scale(1) translateY(0);
  }
}
</style>

// app/(dashboard)/config/device/page.tsx
'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Icon } from '@/components/ui/icon';
import api from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import {
  DeviceCardsSkeleton,
  DeviceConfigPageSkeleton,
} from '@/components/shared/SystemPageSkeletons';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { CustomSelect } from '@/components/shared/CustomSelect';

export default function ConfigDevicePage() {
  const router = useRouter();
  const [devices, setDevices] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [testingId, setTestingId] = useState<string | null>(null);
  const [settingPushId, setSettingPushId] = useState<string | null>(null);

  // Parameter Kehadiran State
  const [lateHour, setLateHour] = useState(7);
  const [lateMinute, setLateMinute] = useState(0);
  const [minOutHour, setMinOutHour] = useState(12);
  const [minOutMinute, setMinOutMinute] = useState(0);
  const [onsiteLimitHour, setOnsiteLimitHour] = useState(21);
  const [savingSettings, setSavingSettings] = useState(false);

  // Modal State
  const [showModal, setShowModal] = useState(false);
  const [isEdit, setIsEdit] = useState(false);
  const [currentId, setCurrentId] = useState<string | null>(null);
  const [form, setForm] = useState({
    name: '',
    location: '',
    url: '',
    username: '',
    password: '',
    poolingInterval: 30,
    isActive: true,
  });

  const lateTime = useMemo(() => {
    const h = String(lateHour).padStart(2, '0');
    const m = String(lateMinute).padStart(2, '0');
    return `${h}:${m}`;
  }, [lateHour, lateMinute]);

  const minOutTime = useMemo(() => {
    const h = String(minOutHour).padStart(2, '0');
    const m = String(minOutMinute).padStart(2, '0');
    return `${h}:${m}`;
  }, [minOutHour, minOutMinute]);

  const fetchDevices = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get('/device').catch(() => api.get('/config/device'));
      const d = res?.data?.data || res?.data || [];
      if (Array.isArray(d)) setDevices(d);
    } catch (e) {
      console.error(e);
      toast.error('Gagal mengambil daftar perangkat');
    } finally {
      setLoading(false);
    }
  }, []);

  const fetchSettings = useCallback(async () => {
    try {
      const res = await api.get('/system/settings').catch(() => api.get('/system'));
      const d = res?.data?.data || res?.data;
      if (d) {
        if (d.lateHour !== undefined) setLateHour(d.lateHour);
        if (d.lateMinute !== undefined) setLateMinute(d.lateMinute);
        if (d.minOutHour !== undefined) setMinOutHour(d.minOutHour);
        if (d.minOutMinute !== undefined) setMinOutMinute(d.minOutMinute);
        if (d.onsiteLimitHour !== undefined) setOnsiteLimitHour(d.onsiteLimitHour);
      }
    } catch (e) {
      console.error(e);
    }
  }, []);

  useEffect(() => {
    fetchDevices();
    fetchSettings();
  }, [fetchDevices, fetchSettings]);

  const openAddModal = () => {
    setIsEdit(false);
    setCurrentId(null);
    setForm({
      name: '',
      location: '',
      url: '',
      username: '',
      password: '',
      poolingInterval: 30,
      isActive: true,
    });
    setShowModal(true);
  };

  const openEditModal = (device: any) => {
    setIsEdit(true);
    setCurrentId(device.id);
    setForm({
      name: device.name || '',
      location: device.location || '',
      url: device.url || '',
      username: device.username || '',
      password: '',
      poolingInterval: device.poolingInterval || 30,
      isActive: device.isActive !== false,
    });
    setShowModal(true);
  };

  const handleSave = async () => {
    if (!form.name || !form.location || !form.url || !form.username) {
      toast.error('Harap isi semua kolom wajib!');
      return;
    }
    if (!isEdit && !form.password) {
      toast.error('Password wajib diisi untuk perangkat baru!');
      return;
    }
    setSaving(true);
    try {
      const payload: any = { ...form };
      if (isEdit && !payload.password) delete payload.password;

      if (isEdit && currentId) {
        await api.put(`/device/${currentId}`, payload);
        toast.success('Perangkat berhasil diperbarui');
      } else {
        await api.post('/device', payload);
        toast.success('Perangkat berhasil ditambahkan');
      }
      setShowModal(false);
      await fetchDevices();
    } catch (e: any) {
      toast.error(e?.response?.data?.message || 'Gagal menyimpan perangkat');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Apakah Anda yakin ingin menghapus perangkat ini?')) return;
    try {
      await api.delete(`/device/${id}`);
      toast.success('Perangkat berhasil dihapus');
      await fetchDevices();
    } catch (e) {
      toast.error('Gagal menghapus perangkat');
    }
  };

  const testConnection = async (device: any) => {
    setTestingId(device.id);
    try {
      const res = await api.post('/device/test-connection', {
        url: device.url,
        username: device.username,
        password: 'mock-password',
      });
      if (res?.data?.success) {
        toast.success(`${device.name}: ${res.data.message || 'Koneksi Berhasil'}`);
      } else {
        toast.error(`${device.name}: ${res?.data?.message || 'Koneksi gagal'}`);
      }
    } catch (e: any) {
      toast.error(`${device.name}: ${e?.response?.data?.message || 'Gagal terhubung'}`);
    } finally {
      setTestingId(null);
    }
  };

  const handleSetupPush = async (device: any) => {
    const guessedBackend = `${window.location.protocol}//${window.location.hostname}:5000`;
    const serverUrl = prompt(
      `Masukkan Alamat IP/Port Server GASKAN (IP Backend) agar perangkat bisa mengirim data presensi secara real-time (Push Mode):`,
      guessedBackend
    );
    if (!serverUrl) return;

    setSettingPushId(device.id);
    try {
      const res = await api.post(`/device/${device.id}`, { serverUrl });
      toast.success(res?.data?.message || 'Push Mode berhasil dikonfigurasi');
    } catch (e: any) {
      toast.error(e?.response?.data?.message || 'Gagal terhubung ke mesin untuk setup push');
    } finally {
      setSettingPushId(null);
    }
  };

  const toggleDeviceStatus = async (device: any) => {
    try {
      await api.put(`/device/${device.id}`, { isActive: !device.isActive });
      setDevices((prev) =>
        prev.map((d) => (d.id === device.id ? { ...d, isActive: !d.isActive } : d))
      );
      toast.success(`Status ${device.name} berhasil diperbarui`);
    } catch (e) {
      toast.error('Gagal mengubah status perangkat');
    }
  };

  const saveLateSettings = async () => {
    setSavingSettings(true);
    try {
      await api.put('/system/settings', {
        lateHour: Number(lateHour),
        lateMinute: Number(lateMinute),
        minOutHour: Number(minOutHour),
        minOutMinute: Number(minOutMinute),
        onsiteLimitHour: Number(onsiteLimitHour),
      });
      toast.success('Pengaturan parameter kehadiran berhasil disimpan');
    } catch (e: any) {
      toast.error(e?.response?.data?.message || 'Gagal menyimpan pengaturan');
    } finally {
      setSavingSettings(false);
    }
  };

  if (loading && devices.length === 0) {
    return <DeviceConfigPageSkeleton />;
  }

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-12 animate-in fade-in duration-500">
      {/* Header Area matching Nuxt 1-to-1 */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="flex flex-wrap items-center gap-3 text-2xl font-black tracking-tight text-foreground sm:text-3xl">
            Mesin & Gerbang Presensi
            <Badge className="bg-primary/15 text-primary border-primary/30 text-xs font-black">
              {devices.length} Perangkat
            </Badge>
          </h1>
          <p className="text-xs sm:text-sm text-muted-foreground font-semibold mt-0.5">
            Kelola beberapa mesin absensi Hikvision beserta nama dan lokasinya untuk pelacakan gerbang pintu masuk.
          </p>
        </div>

        <Button
          onClick={openAddModal}
          className="h-11 w-full rounded-2xl bg-primary px-6 text-xs font-black text-primary-foreground shadow-lg shadow-primary/20 transition-all hover:scale-[1.02] active:scale-[0.98] md:w-auto"
        >
          <Icon icon="mingcute:plus-fill" className="mr-1.5 text-lg" />
          Tambah Perangkat
        </Button>
      </div>

      {/* Loading Grid */}
      {loading ? (
        <DeviceCardsSkeleton />
      ) : devices.length === 0 ? (
        <div className="bg-card border border-border rounded-3xl p-6 sm:p-16 text-center max-w-lg mx-auto shadow-sm space-y-3">
          <div className="w-16 h-16 rounded-2xl bg-muted/50 border border-border flex items-center justify-center mx-auto">
            <Icon icon="mingcute:chip-line" className="text-3xl text-muted-foreground/40" />
          </div>
          <h3 className="text-xl font-bold text-foreground">Belum ada perangkat terdaftar</h3>
          <p className="text-muted-foreground text-xs font-medium">
            Tambahkan mesin sidik jari/wajah Hikvision pertama Anda untuk mulai sinkronisasi data kehadiran siswa secara otomatis.
          </p>
          <Button onClick={openAddModal} className="w-full rounded-xl px-5 text-xs font-bold sm:w-auto">
            <Icon icon="mingcute:plus-fill" className="mr-1 text-sm" />
            Daftarkan Mesin
          </Button>
        </div>
      ) : (
        /* Grid of Devices matching Nuxt 1-to-1 */
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {devices.map((d) => (
            <div
              key={d.id}
              className="group relative flex min-w-0 flex-col justify-between overflow-hidden rounded-3xl border border-border bg-card p-4 shadow-sm transition-all duration-300 hover:border-primary/30 hover:shadow-lg sm:p-6"
            >
              <div>
                {/* Header Card */}
                <div className="flex justify-between items-start mb-4">
                  <div className="min-w-0">
                    <h2 className="break-words text-xl font-bold text-foreground transition-colors group-hover:text-primary">
                      {d.name}
                    </h2>
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground mt-1 font-semibold">
                      <Icon icon="mingcute:location-fill" className="text-primary text-sm shrink-0" />
                      <span>{d.location}</span>
                    </div>
                  </div>

                  {/* Toggle switch to activate/deactivate */}
                  <Switch
                    checked={d.isActive !== false}
                    onCheckedChange={() => toggleDeviceStatus(d)}
                  />
                </div>

                {/* Divider */}
                <div className="border-t border-border my-4" />

                {/* Connection Stats matching Nuxt 1-to-1 */}
                <div className="space-y-2.5 text-xs font-medium text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Icon icon="mingcute:link-2-line" className="text-base text-muted-foreground/60" />
                    <span className="font-mono text-xs truncate bg-muted/60 px-2 py-0.5 rounded-lg text-foreground font-bold">
                      {d.url}
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Icon icon="mingcute:user-3-line" className="text-base text-muted-foreground/60" />
                    <span>
                      Username: <strong className="text-foreground">{d.username}</strong>
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Icon icon="mingcute:signal-fill" className="text-base text-muted-foreground/60" />
                    <span>
                      Mode: <strong className="text-primary">Push Webhook (Real-time)</strong>
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Icon icon="mingcute:time-line" className="text-base text-muted-foreground/60" />
                    <span>
                      Interval: <strong className="text-foreground">{d.poolingInterval || 1} detik</strong>
                    </span>
                  </div>
                </div>
              </div>

              {/* Footer Actions matching Nuxt 1-to-1 */}
              <div className="mt-6 pt-4 border-t border-border space-y-3">
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => testConnection(d)}
                    disabled={testingId === d.id}
                    className="h-11 flex-1 rounded-xl border-primary text-xs font-bold text-primary hover:bg-primary/10 sm:h-9"
                  >
                    {testingId === d.id ? (
                      <Icon icon="mingcute:loading-fill" className="animate-spin mr-1 text-sm" />
                    ) : (
                      <Icon icon="mingcute:radar-fill" className="mr-1 text-sm" />
                    )}
                    Test Koneksi
                  </Button>

                  <Button
                    size="sm"
                    onClick={() => handleSetupPush(d)}
                    disabled={settingPushId === d.id}
                    className="h-11 flex-1 rounded-xl bg-primary text-xs font-bold text-primary-foreground sm:h-9"
                  >
                    {settingPushId === d.id ? (
                      <Icon icon="mingcute:loading-fill" className="animate-spin mr-1 text-sm" />
                    ) : (
                      <Icon icon="mingcute:upload-2-fill" className="mr-1 text-sm" />
                    )}
                    Setup Push
                  </Button>
                </div>

                <div className="flex items-center justify-between pt-1">
                  <span className="text-xs text-muted-foreground font-semibold">Aksi Perangkat:</span>
                  <div className="flex items-center gap-1.5">
                    {/* Link to detail page /config/device/[id] */}
                    <Link
                      href={`/config/device/${d.id}`}
                      className="flex h-11 w-11 items-center justify-center rounded-xl border border-border text-muted-foreground transition-colors hover:border-emerald-500/30 hover:text-emerald-500 sm:h-8 sm:w-8"
                      title="Statistik & Kapasitas Alat"
                    >
                      <Icon icon="mingcute:chart-bar-fill" className="text-base" />
                    </Link>
                    <button
                      onClick={() => openEditModal(d)}
                      className="flex h-11 w-11 items-center justify-center rounded-xl border border-border text-muted-foreground transition-colors hover:border-primary/30 hover:text-primary sm:h-8 sm:w-8"
                      aria-label={`Edit ${d.name}`}
                    >
                      <Icon icon="mingcute:pencil-fill" className="text-base" />
                    </button>
                    <button
                      onClick={() => handleDelete(d.id)}
                      className="flex h-11 w-11 items-center justify-center rounded-xl border border-border text-muted-foreground transition-colors hover:border-rose-500/30 hover:text-rose-500 sm:h-8 sm:w-8"
                      aria-label={`Hapus ${d.name}`}
                    >
                      <Icon icon="mingcute:delete-2-fill" className="text-base" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Attendance Parameters Card matching Nuxt 1-to-1 */}
      <div className="relative mt-12 max-w-2xl overflow-hidden rounded-3xl border border-border bg-card p-4 shadow-md sm:p-8">
        <div className="flex items-start gap-4 mb-6">
          <div className="w-12 h-12 rounded-2xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-500 shrink-0">
            <Icon icon="mingcute:time-fill" className="text-2xl" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-foreground">Parameter Kehadiran & On-Site</h2>
            <p className="text-xs text-muted-foreground mt-1 font-medium">
              Konfigurasi batas waktu keterlambatan presensi masuk dan jam batas pembersihan otomatis daftar siswa aktif di area (On-Site).
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
          <div className="space-y-1.5">
            <Label className="text-xs font-bold text-foreground">
              Batas Waktu Masuk <span className="text-rose-500">*</span>
            </Label>
            <Input
              type="time"
              value={lateTime}
              onChange={(e) => {
                const [h, m] = e.target.value.split(':');
                if (h) setLateHour(Number(h));
                if (m) setLateMinute(Number(m));
              }}
              className="rounded-xl font-bold text-xs h-10 bg-muted/30"
            />
            <span className="text-[10px] text-muted-foreground block">Masuk setelah jam ini otomatis &quot;TERLAMBAT&quot;</span>
          </div>

          <div className="space-y-1.5">
            <Label className="text-xs font-bold text-foreground">
              Batas Minimal Pulang <span className="text-rose-500">*</span>
            </Label>
            <Input
              type="time"
              value={minOutTime}
              onChange={(e) => {
                const [h, m] = e.target.value.split(':');
                if (h) setMinOutHour(Number(h));
                if (m) setMinOutMinute(Number(m));
              }}
              className="rounded-xl font-bold text-xs h-10 bg-muted/30"
            />
            <span className="text-[10px] text-muted-foreground block">Scan sebelum jam ini diabaikan</span>
          </div>

          <div className="space-y-1.5">
            <Label className="text-xs font-bold text-foreground">
              Batas Jam Log Onsite <span className="text-rose-500">*</span>
            </Label>
            <CustomSelect
              value={String(onsiteLimitHour)}
              onChange={(val) => setOnsiteLimitHour(Number(val))}
              options={Array.from({ length: 24 }).map((_, i) => ({
                value: String(i),
                label: `Jam ${String(i).padStart(2, '0')}:00 WIB`,
              }))}
              triggerClassName="w-full h-10 rounded-xl bg-muted/30 border-border font-bold text-xs"
            />
            <span className="text-[10px] text-muted-foreground block">Auto-flush log onsite harian</span>
          </div>
        </div>

        <Button
          onClick={saveLateSettings}
          disabled={savingSettings}
          className="h-11 w-full rounded-2xl bg-primary px-6 text-xs font-bold text-primary-foreground sm:w-auto"
        >
          {savingSettings ? 'Memproses...' : 'Simpan Parameter Presensi'}
        </Button>
      </div>

      {/* CREATE / EDIT DEVICE MODAL */}
      {showModal && (
        <Dialog open={showModal} onOpenChange={setShowModal}>
          <DialogContent className="flex max-h-[calc(100dvh-1rem)] flex-col overflow-hidden rounded-3xl border-border bg-card p-0 shadow-2xl sm:max-w-md">
            <DialogHeader className="shrink-0 border-b border-border bg-card p-4 pb-4 sm:p-6 sm:pb-4">
              <DialogTitle className="text-xl font-black text-foreground">
                {isEdit ? 'Edit Perangkat Absensi' : 'Daftarkan Perangkat Baru'}
              </DialogTitle>
            </DialogHeader>

            <div className="flex-1 space-y-4 overflow-y-auto p-4 text-xs sm:p-6">
              <div className="space-y-2">
                <div className="flex items-center justify-between mb-2">
                  <Label className="mb-0">Nama Perangkat</Label>
                </div>
                <Input
                  type="text"
                  placeholder="Contoh: Samping bengkel 1"
                  value={form.name}
                  onChange={(e) => setForm({ ...form, name: e.target.value })}
                  className="rounded-2xl h-11 bg-muted/30 font-bold text-xs"
                />
              </div>

              <div className="space-y-2">
                <div className="flex items-center justify-between mb-2">
                  <Label className="mb-0">Lokasi Perangkat</Label>
                </div>
                <Input
                  type="text"
                  placeholder="Contoh: Samping bengkel"
                  value={form.location}
                  onChange={(e) => setForm({ ...form, location: e.target.value })}
                  className="rounded-2xl h-11 bg-muted/30 font-bold text-xs"
                />
              </div>

              <div className="space-y-2">
                <div className="flex items-center justify-between mb-2">
                  <Label className="mb-0">URL IP Perangkat</Label>
                </div>
                <Input
                  type="text"
                  placeholder="http://192.168.55.136"
                  value={form.url}
                  onChange={(e) => setForm({ ...form, url: e.target.value })}
                  className="rounded-2xl h-11 bg-muted/30 font-bold text-xs font-mono"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <div className="flex items-center justify-between mb-2">
                    <Label className="mb-0">Username Hikvision</Label>
                  </div>
                  <Input
                    type="text"
                    value={form.username}
                    onChange={(e) => setForm({ ...form, username: e.target.value })}
                    className="rounded-2xl h-11 bg-muted/30 font-bold text-xs"
                  />
                </div>
                <div className="space-y-2">
                  <div className="flex items-center justify-between mb-2">
                    <Label className="mb-0">Password</Label>
                  </div>
                  <Input
                    type="password"
                    placeholder={isEdit ? 'Biarkan kosong' : 'Password'}
                    value={form.password}
                    onChange={(e) => setForm({ ...form, password: e.target.value })}
                    className="rounded-2xl h-11 bg-muted/30 font-bold text-xs"
                  />
                </div>
              </div>
            </div>

            <DialogFooter className="shrink-0 gap-3 border-t border-border bg-card/90 p-4 pt-4 backdrop-blur-md sm:gap-4 sm:p-6 sm:pt-4">
              <Button variant="ghost" className="rounded-2xl font-bold flex-1 text-xs" onClick={() => setShowModal(false)}>
                Batal
              </Button>
              <Button onClick={handleSave} disabled={saving} className="rounded-2xl font-bold flex-1 text-xs bg-primary text-primary-foreground shadow-lg shadow-primary/20">
                {saving ? 'Memproses...' : isEdit ? 'Simpan Perubahan' : 'Daftarkan'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
}
