// gaskan-next/app/(dashboard)/admin/team/page.tsx
'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { toast } from 'sonner';
import { Icon } from '@iconify/react';
import api from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { CustomSelect } from '@/components/shared/CustomSelect';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'https://api.tierkun.my.id';

const resolvePhoto = (url?: string) => {
  if (!url) return null;
  if (url.startsWith('http')) return url;
  if (url.startsWith('/uploads/team/')) return `${API_BASE}${url}`;
  return `${API_BASE}${url.startsWith('/') ? '' : '/'}${url}`;
};

const getRoleColor = (roleStr: string) => {
  if (!roleStr) return 'text-muted-foreground';
  if (roleStr.includes('Backend')) return 'text-sky-400';
  if (roleStr.includes('Frontend')) return 'text-emerald-400';
  if (roleStr.includes('Hardware') || roleStr.includes('Electrical') || roleStr.includes('Mechanical')) return 'text-amber-500';
  if (roleStr.includes('PEMBIMBING') || roleStr.includes('Pembimbing')) return 'text-primary';
  return 'text-purple-400';
};

export default function AdminTeamPage() {
  const [members, setMembers] = useState<any[]>([]);
  const [availableUsers, setAvailableUsers] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  // Modals
  const [showModal, setShowModal] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [deleteId, setDeleteId] = useState<string | null>(null);

  // Form
  const [form, setForm] = useState({
    id: '',
    name: '',
    role: '',
    photoUrl: '',
    github: '',
    linkedin: '',
    instagram: '',
    email: '',
    bio: '',
    userId: '',
    startYear: new Date().getFullYear(),
    endYear: new Date().getFullYear(),
    isUntilNow: true,
    order: 0,
    isActive: true,
  });

  const fetchMembers = useCallback(async () => {
    setIsLoading(true);
    try {
      const [resTeam, resUsers] = await Promise.allSettled([
        api.get('/team'),
        api.get('/team/available-users').catch(() => api.get('/users')),
      ]);

      if (resTeam.status === 'fulfilled' && resTeam.value?.data) {
        const d = resTeam.value.data.data || resTeam.value.data;
        if (Array.isArray(d)) setMembers(d);
      }
      if (resUsers.status === 'fulfilled' && resUsers.value?.data) {
        const u = resUsers.value.data.data || resUsers.value.data;
        if (Array.isArray(u)) setAvailableUsers(u);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchMembers();
  }, [fetchMembers]);

  const filteredMembers = useMemo(() => {
    if (!searchQuery.trim()) return members;
    const q = searchQuery.toLowerCase();
    return members.filter(
      (m) =>
        (m.name || '').toLowerCase().includes(q) ||
        (m.role || '').toLowerCase().includes(q)
    );
  }, [members, searchQuery]);

  const openCreate = () => {
    setEditMode(false);
    setForm({
      id: '',
      name: '',
      role: '',
      photoUrl: '',
      github: '',
      linkedin: '',
      instagram: '',
      email: '',
      bio: '',
      userId: '',
      startYear: 2023,
      endYear: new Date().getFullYear(),
      isUntilNow: true,
      order: members.length,
      isActive: true,
    });
    setShowModal(true);
  };

  const openEdit = (member: any) => {
    setEditMode(true);
    let startY = 2023;
    let endY = new Date().getFullYear();
    let untilNow = true;

    if (member.year) {
      const parts = member.year.split('-').map((s: string) => s.trim());
      if (parts.length === 2) {
        startY = parseInt(parts[0]) || 2023;
        if (parts[1].toLowerCase() === 'sekarang') {
          untilNow = true;
        } else {
          untilNow = false;
          endY = parseInt(parts[1]) || new Date().getFullYear();
        }
      } else {
        startY = parseInt(parts[0]) || 2023;
        endY = startY;
        untilNow = false;
      }
    }

    setForm({
      id: member.id,
      name: member.name || '',
      role: member.role || '',
      photoUrl: member.photoUrl || '',
      github: member.github || '',
      linkedin: member.linkedin || '',
      instagram: member.instagram || '',
      email: member.email || '',
      bio: member.bio || '',
      userId: member.userId || '',
      startYear: startY,
      endYear: endY,
      isUntilNow: untilNow,
      order: member.order || 0,
      isActive: member.isActive !== false,
    });
    setShowModal(true);
  };

  const saveMember = async () => {
    if (!form.name.trim() || !form.role.trim()) {
      toast.error('Nama lengkap dan Peran wajib diisi');
      return;
    }

    setIsSaving(true);
    try {
      const yearStr = form.isUntilNow
        ? `${form.startYear} - Sekarang`
        : form.startYear === form.endYear
        ? `${form.startYear}`
        : `${form.startYear} - ${form.endYear}`;

      const payload = {
        name: form.name,
        role: form.role,
        bio: form.bio,
        github: form.github,
        linkedin: form.linkedin,
        instagram: form.instagram,
        email: form.email,
        userId: form.userId || null,
        year: yearStr,
        order: form.order,
        isActive: form.isActive,
      };

      if (editMode && form.id) {
        await api.put(`/team/${form.id}`, payload);
        toast.success('Anggota tim diperbarui');
      } else {
        await api.post('/team', payload);
        toast.success('Anggota tim ditambahkan');
      }
      setShowModal(false);
      await fetchMembers();
    } catch (e: any) {
      toast.error(e?.response?.data?.message || 'Gagal menyimpan data anggota tim');
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteMember = async () => {
    if (!deleteId) return;
    setIsSaving(true);
    try {
      await api.delete(`/team/${deleteId}`);
      toast.success('Anggota tim dihapus');
      setDeleteId(null);
      await fetchMembers();
    } catch (e: any) {
      toast.error(e?.response?.data?.message || 'Gagal menghapus anggota tim');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12 animate-in fade-in duration-500">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-black text-foreground tracking-tight">
            Manajemen Tim
          </h1>
          <p className="text-xs sm:text-sm text-muted-foreground font-semibold mt-0.5">
            Kelola orang-orang di balik GASKAN & sambungkan ke akun siswa/user
          </p>
        </div>
        <Button
          onClick={openCreate}
          className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-2xl gap-2 font-black text-xs h-12 shadow-lg shadow-primary/20"
        >
          <Icon icon="mingcute:user-add-fill" className="text-lg" />
          <span>Tambah Anggota</span>
        </Button>
      </div>

      {/* Filter Toolbar */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 bg-card p-4 rounded-3xl border border-border shadow-sm">
        <div className="md:col-span-2 relative">
          <Icon icon="mingcute:search-line" className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground text-base" />
          <Input
            type="text"
            placeholder="Cari Nama atau Peran..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-11 h-11 bg-background rounded-2xl text-xs font-bold border-border"
          />
        </div>
        <div className="flex items-center justify-center font-black text-xs text-muted-foreground/60 uppercase tracking-widest">
          TOTAL: {filteredMembers.length} ORANG
        </div>
      </div>

      {/* Bento Grid matching Nuxt 1-to-1 */}
      {isLoading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <div key={i} className="bg-card rounded-3xl p-6 border border-border/60 shadow-sm animate-pulse space-y-4">
              <div className="flex items-start gap-4">
                <div className="w-16 h-16 rounded-2xl bg-muted shrink-0" />
                <div className="flex-1 space-y-2">
                  <div className="h-4 bg-muted rounded w-3/4" />
                  <div className="h-3 bg-muted rounded w-1/2" />
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : filteredMembers.length === 0 ? (
        <div className="bg-card border border-border rounded-3xl p-20 text-center text-xs font-bold text-muted-foreground/40 italic">
          Belum ada data anggota tim
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredMembers.map((m) => {
            const photo = resolvePhoto(m.photoUrl);
            const colorClass = getRoleColor(m.role);

            return (
              <div
                key={m.id}
                className="bg-card rounded-3xl p-6 border border-border/60 shadow-sm hover:border-primary/40 transition-all group flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-start gap-4">
                    {/* Avatar */}
                    <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center text-primary shrink-0 overflow-hidden border border-primary/10">
                      {photo ? (
                        <img src={photo} alt={m.name} className="w-full h-full object-cover" />
                      ) : (
                        <Icon icon="mingcute:user-4-fill" className="text-2xl text-primary/40" />
                      )}
                    </div>

                    {/* Member Info */}
                    <div className="flex-1 min-w-0">
                      <h3 className="font-black text-foreground truncate text-base">{m.name}</h3>
                      <p className={`text-xs font-black uppercase tracking-wider mt-0.5 ${colorClass}`}>
                        {m.role}
                      </p>

                      {/* User account connection tag */}
                      {m.user ? (
                        <div className="inline-flex items-center gap-1 mt-2 px-2 py-0.5 rounded-md bg-primary/10 border border-primary/20 text-primary text-[10px] font-bold">
                          <Icon icon="mingcute:user-check-fill" className="text-xs" />
                          <span className="truncate max-w-[120px]">{m.user.name}</span>
                        </div>
                      ) : (
                        <div className="text-[10px] text-muted-foreground/40 italic mt-1 font-semibold">
                          Belum terhubung akun
                        </div>
                      )}
                    </div>

                    {/* Action buttons */}
                    <div className="flex flex-col gap-1">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-muted-foreground hover:text-primary rounded-lg"
                        onClick={() => openEdit(m)}
                      >
                        <Icon icon="mingcute:edit-2-line" className="text-sm" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-muted-foreground hover:text-rose-500 rounded-lg"
                        onClick={() => setDeleteId(m.id)}
                      >
                        <Icon icon="mingcute:delete-2-line" className="text-sm" />
                      </Button>
                    </div>
                  </div>

                  {m.bio && (
                    <p className="text-xs text-muted-foreground mt-3 italic line-clamp-2 bg-muted/40 p-2.5 rounded-2xl border border-border">
                      "{m.bio}"
                    </p>
                  )}
                </div>

                {/* Bottom Bar */}
                <div className="mt-4 pt-4 border-t border-border flex items-center justify-between">
                  <div className="flex items-center gap-1.5">
                    <div className={`w-2 h-2 rounded-full ${m.isActive !== false ? 'bg-emerald-500' : 'bg-muted'}`} />
                    <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground/60">
                      {m.isActive !== false ? 'Aktif' : 'Nonaktif'}
                    </span>
                  </div>
                  <div className="flex items-center gap-3">
                    <Badge variant="outline" className="text-[10px] font-bold py-0.5 px-2 text-muted-foreground">
                      Periode {m.year || '2023 - Sekarang'}
                    </Badge>
                    <span className="text-[10px] font-black text-muted-foreground/30">
                      Order: {m.order ?? 0}
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* ═══ CREATE / EDIT MODAL ═══ */}
      <Dialog open={showModal} onOpenChange={setShowModal}>
        <DialogContent className="sm:max-w-xl max-h-[85vh] flex flex-col p-0 overflow-hidden border-border bg-card rounded-3xl shadow-2xl">
          <DialogHeader className="p-6 pb-4 border-b border-border shrink-0 bg-card">
            <DialogTitle className="text-xl font-black text-foreground">
              {editMode ? 'Edit Anggota Tim' : 'Tambah Anggota Tim'}
            </DialogTitle>
          </DialogHeader>

          <div className="flex-1 overflow-y-auto p-6 space-y-4 text-xs sm:text-sm">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="memberName">Nama Lengkap</Label>
                <Input
                  id="memberName"
                  value={form.name}
                  onChange={(e) => setForm({ ...form, name: e.target.value })}
                  placeholder="Contoh: Fahreza Pasha Haikal"
                  className="rounded-2xl bg-muted/30 font-bold h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="memberRole">Peran / Role</Label>
                <Input
                  id="memberRole"
                  value={form.role}
                  onChange={(e) => setForm({ ...form, role: e.target.value })}
                  placeholder="Contoh: FRONTEND DEVELOPER"
                  className="rounded-2xl bg-muted/30 font-bold h-11 uppercase"
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="memberBio">Bio / Deskripsi Profil</Label>
              <textarea
                id="memberBio"
                value={form.bio}
                onChange={(e) => setForm({ ...form, bio: e.target.value })}
                rows={2}
                placeholder="Tuliskan bio singkat..."
                className="w-full p-3 rounded-2xl bg-muted/30 border border-border text-xs font-medium focus:outline-none"
              />
            </div>

            {/* Connect User Account */}
            <div className="space-y-2">
              <Label>Sambungkan ke Akun Siswa/User</Label>
              <CustomSelect
                options={[
                  { value: '', label: 'Belum Terhubung Akun' },
                  ...availableUsers.map((u) => ({ value: u.id, label: `${u.name} (${u.role})` })),
                ]}
                value={form.userId}
                onChange={(val) => setForm({ ...form, userId: val })}
                placeholder="Pilih Akun User"
              />
            </div>

            {/* Year Range Picker */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="startYr">Tahun Mulai</Label>
                <Input
                  id="startYr"
                  type="number"
                  value={form.startYear}
                  onChange={(e) => setForm({ ...form, startYear: parseInt(e.target.value) })}
                  className="rounded-2xl bg-muted/30 font-bold h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="endYr">Tahun Selesai</Label>
                <Input
                  id="endYr"
                  type="number"
                  disabled={form.isUntilNow}
                  value={form.endYear}
                  onChange={(e) => setForm({ ...form, endYear: parseInt(e.target.value) })}
                  className="rounded-2xl bg-muted/30 font-bold h-11 disabled:opacity-50"
                />
              </div>
            </div>

            <div className="flex items-center gap-2 pt-1">
              <input
                type="checkbox"
                id="untilNowCheck"
                checked={form.isUntilNow}
                onChange={(e) => setForm({ ...form, isUntilNow: e.target.checked })}
                className="w-4 h-4 rounded border-border text-primary"
              />
              <Label htmlFor="untilNowCheck" className="cursor-pointer mb-0">
                Masih Aktif Sampai Sekarang ("Sekarang")
              </Label>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="orderNum">Urutan Tampilan (Order)</Label>
                <Input
                  id="orderNum"
                  type="number"
                  value={form.order}
                  onChange={(e) => setForm({ ...form, order: parseInt(e.target.value) })}
                  className="rounded-2xl bg-muted/30 font-bold h-11"
                />
              </div>
            </div>
          </div>

          <DialogFooter className="p-6 pt-4 border-t border-border shrink-0 bg-card/90 backdrop-blur-md gap-3">
            <Button variant="ghost" className="rounded-2xl flex-1 font-bold" onClick={() => setShowModal(false)}>
              Batal
            </Button>
            <Button
              className="rounded-2xl flex-1 font-bold bg-primary text-primary-foreground shadow-lg shadow-primary/20"
              disabled={isSaving}
              onClick={saveMember}
            >
              {isSaving ? 'Memproses...' : editMode ? 'Simpan Perubahan' : 'Tambah Anggota'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ═══ CONFIRM DELETE MODAL ═══ */}
      <Dialog open={!!deleteId} onOpenChange={(open) => !open && setDeleteId(null)}>
        <DialogContent className="sm:max-w-md p-6 text-center">
          <div className="w-16 h-16 bg-rose-500/10 text-rose-500 rounded-2xl flex items-center justify-center mx-auto mb-3">
            <Icon icon="mingcute:delete-2-fill" className="text-3xl" />
          </div>
          <DialogHeader className="p-0 border-none bg-transparent">
            <DialogTitle className="text-2xl font-black text-foreground text-center">
              Hapus Anggota Tim?
            </DialogTitle>
          </DialogHeader>
          <p className="text-xs text-muted-foreground font-semibold leading-relaxed my-2">
            Data anggota tim ini akan dihapus dari daftar.
          </p>
          <DialogFooter className="p-0 border-none bg-transparent gap-3 flex-row justify-center mt-4">
            <Button variant="ghost" className="rounded-2xl flex-1 font-bold" onClick={() => setDeleteId(null)}>
              Batal
            </Button>
            <Button variant="destructive" className="rounded-2xl flex-1 font-bold shadow-lg shadow-rose-500/20" disabled={isSaving} onClick={handleDeleteMember}>
              {isSaving ? 'Menghapus...' : 'Ya, Hapus'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// pages/admin/team/index.vue
<script setup>
import { ref, onMounted, computed } from 'vue';
import { useAuthStore } from '~/store/useAuthStore';
import { storeToRefs } from 'pinia';

const { $toast } = useNuxtApp();
const { role } = storeToRefs(useAuthStore());

useSeoMeta({
  title: 'Manajemen Tim | GASKAN',
  description: 'Kelola anggota tim pengembang GASKAN',
});

// State
const members = ref([]);
const loading = ref(true);
const showModal = ref(false);
const editMode = ref(false);
const saving = ref(false);
const searchQuery = ref('');
const showDeleteModal = ref(false);
const deleteId = ref(null);

const form = ref({
  id: null,
  name: '',
  role: '',
  photoUrl: '',
  github: '',
  linkedin: '',
  instagram: '',
  email: '',
  year: '',
  order: 0,
  isActive: true,
});

// Year Picker Helpers
const startYear = ref(new Date().getFullYear());
const endYear = ref(new Date().getFullYear());
const isUntilNow = ref(false);

const yearOptions = computed(() => {
  const current = new Date().getFullYear();
  const list = [];
  for (let y = current - 6; y <= current + 6; y++) {
    list.push(y);
  }
  return list;
});

const parseYearFromForm = (yearStr) => {
  if (!yearStr) {
    startYear.value = new Date().getFullYear();
    endYear.value = new Date().getFullYear();
    isUntilNow.value = false;
    return;
  }

  const parts = yearStr.split('-').map(s => s.trim());
  if (parts.length === 2) {
    const start = parseInt(parts[0]);
    startYear.value = isNaN(start) ? new Date().getFullYear() : start;
    
    if (parts[1].toLowerCase() === 'sekarang') {
      isUntilNow.value = true;
      endYear.value = new Date().getFullYear();
    } else {
      isUntilNow.value = false;
      const end = parseInt(parts[1]);
      endYear.value = isNaN(end) ? new Date().getFullYear() : end;
    }
  } else {
    const val = parseInt(parts[0]);
    const yr = isNaN(val) ? new Date().getFullYear() : val;
    startYear.value = yr;
    endYear.value = yr;
    isUntilNow.value = false;
  }
};

const syncYearToForm = () => {
  if (isUntilNow.value) {
    form.value.year = `${startYear.value} - Sekarang`;
  } else {
    if (startYear.value === endYear.value) {
      form.value.year = `${startYear.value}`;
    } else {
      form.value.year = `${startYear.value} - ${endYear.value}`;
    }
  }
};

// Helper for Photo
const resolvePhoto = (url) => {
  if (!url) return null;
  if (url.startsWith('http')) return url;
  if (url.startsWith('/uploads/team/')) {
    return `/api${url}`;
  }
  return url;
};

// Fetch data
const fetchMembers = async () => {
  loading.value = true;
  try {
    const res = await $fetch('/api/team');
    members.value = Array.isArray(res?.data) ? res.data : [];
  } catch (e) {
    console.error('Failed to fetch team members:', e);
    $toast.error('Gagal mengambil data tim');
  } finally {
    loading.value = false;
  }
};

onMounted(fetchMembers);

const filteredMembers = computed(() => {
  if (!searchQuery.value) return members.value;
  const q = searchQuery.value.toLowerCase();
  return members.value.filter(m => 
    m.name.toLowerCase().includes(q) || 
    m.role.toLowerCase().includes(q)
  );
});

const photoFile = ref(null);
const photoPreview = ref(null);

const handleFileChange = (e) => {
  const file = e.target.files[0];
  if (file) {
    photoFile.value = file;
    photoPreview.value = URL.createObjectURL(file);
  }
};

const openCreate = () => {
  editMode.value = false;
  photoFile.value = null;
  photoPreview.value = null;
  form.value = {
    id: null,
    name: '',
    role: '',
    photoUrl: '',
    github: '',
    linkedin: '',
    instagram: '',
    email: '',
    year: '',
    order: members.value.length,
    isActive: true,
  };
  startYear.value = new Date().getFullYear();
  endYear.value = new Date().getFullYear();
  isUntilNow.value = false;
  syncYearToForm();
  showModal.value = true;
};

const openEdit = (member) => {
  editMode.value = true;
  photoFile.value = null;
  photoPreview.value = member.photoUrl;
  form.value = { ...member };
  parseYearFromForm(member.year);
  showModal.value = true;
};

const saveMember = async () => {
  syncYearToForm();
  saving.value = true;
  try {
    const formData = new FormData();
    Object.keys(form.value).forEach(key => {
      if (form.value[key] !== null && form.value[key] !== undefined) {
        formData.append(key, form.value[key]);
      }
    });
    if (photoFile.value) {
      formData.append('photo', photoFile.value);
    }

    if (editMode.value) {
      await $fetch(`/api/team/${form.value.id}`, { method: 'PUT', body: formData });
      $toast.success('Anggota tim diperbarui');
    } else {
      await $fetch('/api/team', { method: 'POST', body: formData });
      $toast.success('Anggota tim ditambahkan');
    }
    showModal.value = false;
    await fetchMembers();
  } catch (e) {
    $toast.error('Gagal menyimpan data');
  } finally {
    saving.value = false;
  }
};

const confirmDelete = (id) => {
  deleteId.value = id;
  showDeleteModal.value = true;
};

const deleteMember = async () => {
  try {
    await $fetch(`/api/team/${deleteId.value}`, { method: 'DELETE' });
    $toast.success('Anggota tim dihapus');
    showDeleteModal.value = false;
    await fetchMembers();
  } catch (e) {
    $toast.error('Gagal menghapus anggota');
  }
};

const bentoCard = "bg-base-100 rounded-[2rem] p-6 border border-base-200/60 shadow-sm transition-all duration-300";

const roleColor = (role) => {
  if (!role) return 'text-base-content/40';
  if (role.includes('Backend')) return 'text-blue-400';
  if (role.includes('Frontend')) return 'text-green-400';
  if (role.includes('Hardware') || role.includes('Electrical') || role.includes('Mechanical')) return 'text-orange-400';
  if (role.includes('Pembimbing')) return 'text-primary';
  return 'text-secondary';
};
</script>

<template>
  <div class="space-y-6 max-w-7xl mx-auto px-4 pb-12 text-left">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 py-4">
      <div>
        <h1 class="text-2xl md:text-3xl font-black text-base-content tracking-tight">Manajemen Tim</h1>
        <p class="text-sm text-base-content/60 mt-1">Kelola orang-orang di balik GASKAN</p>
      </div>
      <button @click="openCreate" class="btn btn-primary rounded-2xl gap-2 h-12 shadow-lg shadow-primary/20">
        <Icon name="mingcute:user-add-fill" size="18" />
        <span>Tambah Anggota</span>
      </button>
    </div>

    <!-- Filters -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-3 bg-base-100 p-4 rounded-[2rem] border border-base-200/60 shadow-sm">
      <div class="md:col-span-2 relative">
        <Icon name="mingcute:search-line" class="absolute left-4 top-1/2 -translate-y-1/2 text-base-content/30" />
        <input 
          v-model="searchQuery" 
          type="text" 
          placeholder="Cari Nama atau Peran..." 
          class="input input-bordered w-full pl-11 rounded-2xl bg-base-200/30" 
        />
      </div>
      <div class="flex items-center justify-center font-bold text-xs text-base-content/40 uppercase tracking-widest">
        Total: {{ filteredMembers.length }} Orang
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
      <div v-for="i in 6" :key="i" :class="[bentoCard, 'flex flex-col animate-pulse']">
        <div class="flex items-start gap-4">
          <div class="skeleton w-16 h-16 rounded-2xl shrink-0"></div>
          <div class="flex-1 space-y-2.5">
            <div class="skeleton h-4 w-3/4"></div>
            <div class="skeleton h-2 w-1/2 opacity-40"></div>
            <div class="flex gap-2 mt-2">
              <div class="skeleton w-5 h-5 rounded-full opacity-30"></div>
              <div class="skeleton w-5 h-5 rounded-full opacity-30"></div>
              <div class="skeleton w-5 h-5 rounded-full opacity-30"></div>
            </div>
          </div>
          <div class="flex flex-col gap-2">
            <div class="skeleton w-6 h-6 rounded-lg opacity-20"></div>
            <div class="skeleton w-6 h-6 rounded-lg opacity-20"></div>
          </div>
        </div>
        <div class="mt-6 pt-4 border-t border-base-200/60 flex items-center justify-between">
          <div class="flex items-center gap-1.5">
            <div class="skeleton w-2 h-2 rounded-full"></div>
            <div class="skeleton h-2 w-12 opacity-30"></div>
          </div>
          <div class="skeleton h-2 w-10 opacity-20"></div>
        </div>
      </div>
    </div>

    <!-- Team List -->
    <div v-else class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
      <div v-for="m in filteredMembers" :key="m.id" :class="[bentoCard, 'group hover:border-primary/40']">
        <div class="flex items-start gap-4">
          <div class="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center text-primary shrink-0 overflow-hidden border border-primary/10">
            <img v-if="m.photoUrl" :src="resolvePhoto(m.photoUrl)" class="w-full h-full object-cover" />
            <Icon v-else name="mingcute:user-4-fill" size="24" class="opacity-40" />
          </div>
          <div class="flex-1 min-w-0">
            <h3 class="font-bold text-base-content truncate">{{ m.name }}</h3>
            <p class="text-xs font-bold uppercase tracking-wider mt-0.5" :class="roleColor(m.role)">{{ m.role }}</p>
            <div class="flex gap-2 mt-3">
              <a v-if="m.github" :href="m.github" target="_blank" class="text-base-content/40 hover:text-primary transition-colors">
                <Icon name="mdi:github" size="18" />
              </a>
              <a v-if="m.linkedin" :href="m.linkedin" target="_blank" class="text-base-content/40 hover:text-primary transition-colors">
                <Icon name="entypo-social:linkedin-with-circle" size="18" />
              </a>
              <a v-if="m.instagram" :href="m.instagram" target="_blank" class="text-base-content/40 hover:text-primary transition-colors">
                <Icon name="mage:instagram-circle" size="18" />
              </a>
            </div>
          </div>
          <div class="flex-1 min-w-0">
            <!-- Space for actions -->
          </div>
          <div class="flex flex-col gap-2">
            <button @click="openEdit(m)" class="btn btn-ghost btn-xs rounded-lg hover:bg-primary/10 hover:text-primary">
              <Icon name="mingcute:edit-2-line" />
            </button>
            <button @click="confirmDelete(m.id)" class="btn btn-ghost btn-xs rounded-lg hover:bg-error/10 hover:text-error">
              <Icon name="mingcute:delete-2-line" />
            </button>
          </div>
        </div>
        <div class="mt-4 pt-4 border-t border-base-200/60 flex items-center justify-between">
          <div class="flex items-center gap-1.5">
            <div :class="['w-2 h-2 rounded-full', m.isActive ? 'bg-success' : 'bg-base-300']"></div>
            <span class="text-[10px] font-bold uppercase tracking-widest text-base-content/40">{{ m.isActive ? 'Aktif' : 'Nonaktif' }}</span>
          </div>
          <div class="flex items-center gap-3">
            <span class="badge badge-sm badge-outline text-[10px] py-2 opacity-60">Periode {{ m.year || '2024' }}</span>
            <span class="text-[10px] font-bold text-base-content/20">Order: {{ m.order }}</span>
          </div>
        </div>
      </div>

      <div v-if="filteredMembers.length === 0" class="col-span-full text-center py-20 text-base-content/30 italic bg-base-100 rounded-[2rem] border border-base-200/60">
        Belum ada data anggota tim
      </div>
    </div>

    <!-- Modal Form -->
    <dialog :class="['modal modal-bottom sm:modal-middle', showModal ? 'modal-open' : '']">
      <div class="modal-box bg-base-100 border border-base-200 rounded-t-[2.5rem] sm:rounded-[2.5rem] p-6 md:p-8 max-w-2xl max-h-[85vh] overflow-y-auto">
        <h3 class="text-xl md:text-2xl font-black text-base-content mb-6">
          {{ editMode ? 'Edit Anggota Tim' : 'Tambah Anggota Tim' }}
        </h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="form-control">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Nama Lengkap</span></label>
            <input v-model="form.name" type="text" placeholder="Contoh: John Doe" class="input input-bordered w-full rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Peran / Role</span></label>
            <input v-model="form.role" type="text" placeholder="Contoh: Backend Developer" class="input input-bordered w-full rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control md:col-span-2">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Foto Anggota</span></label>
            <div class="flex items-center gap-4 p-4 bg-base-200/30 rounded-2xl border border-dashed border-base-300">
              <div class="w-20 h-20 rounded-2xl bg-base-300 flex items-center justify-center overflow-hidden shrink-0">
                <img v-if="photoPreview" :src="photoPreview" class="w-full h-full object-cover" />
                <Icon v-else name="mingcute:photo-album-line" size="24" class="opacity-20" />
              </div>
              <div class="flex-1">
                <input type="file" accept="image/*" @change="handleFileChange" class="file-input file-input-bordered file-input-primary file-input-sm w-full rounded-xl" />
                <p class="text-[9px] mt-2 opacity-40">Rekomendasi: Persegi (1:1), Max 2MB (JPG, PNG, WebP)</p>
              </div>
            </div>
          </div>
          <div class="form-control">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">GitHub URL</span></label>
            <input v-model="form.github" type="text" placeholder="https://github.com/..." class="input input-bordered w-full rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">LinkedIn URL</span></label>
            <input v-model="form.linkedin" type="text" placeholder="https://linkedin.com/in/..." class="input input-bordered w-full rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Instagram URL</span></label>
            <input v-model="form.instagram" type="text" placeholder="https://instagram.com/..." class="input input-bordered w-full rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Email</span></label>
            <input v-model="form.email" type="email" placeholder="email@example.com" class="input input-bordered w-full rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control">
            <label class="label">
              <span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Tahun / Periode</span>
            </label>
            <div class="flex flex-col gap-2 bg-base-200/20 p-3 rounded-2xl border border-base-200/60">
              <div class="flex items-center gap-2">
                <select v-model="startYear" class="select select-bordered select-sm rounded-xl bg-base-100 flex-1 font-semibold">
                  <option v-for="yr in yearOptions" :key="yr" :value="yr">{{ yr }}</option>
                </select>
                <span class="text-xs opacity-50 font-bold">s/d</span>
                <select 
                  v-model="endYear" 
                  :disabled="isUntilNow" 
                  class="select select-bordered select-sm rounded-xl bg-base-100 flex-1 font-semibold disabled:bg-base-200/50 disabled:opacity-50"
                >
                  <option v-for="yr in yearOptions" :key="yr" :value="yr">{{ yr }}</option>
                </select>
              </div>
              <label class="label cursor-pointer justify-start gap-2.5 py-1 px-1">
                <input v-model="isUntilNow" type="checkbox" class="checkbox checkbox-primary checkbox-xs rounded-md" />
                <span class="label-text text-[11px] font-bold opacity-60">Masih Aktif Sampai Sekarang</span>
              </label>
            </div>
          </div>
          <div class="form-control">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Urutan Tampil</span></label>
            <input v-model.number="form.order" type="number" class="input input-bordered w-full rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control md:col-span-2">
            <label class="label cursor-pointer justify-start gap-3 px-1">
              <input v-model="form.isActive" type="checkbox" class="toggle toggle-primary toggle-sm" />
              <span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-60">Aktif & Tampilkan</span>
            </label>
          </div>
        </div>
        <div class="modal-action mt-8 gap-2">
          <button @click="showModal = false" class="btn btn-ghost rounded-2xl px-6">Batal</button>
          <button @click="saveMember" class="btn btn-primary rounded-2xl px-8 shadow-lg shadow-primary/20" :disabled="saving || !form.name || !form.role">
            <span v-if="saving" class="loading loading-spinner loading-xs"></span> Simpan
          </button>
        </div>
      </div>
    </dialog>

    <!-- Delete Confirmation -->
    <dialog :class="['modal modal-bottom sm:modal-middle', showDeleteModal ? 'modal-open' : '']">
      <div class="modal-box max-w-sm text-center bg-base-100 border border-base-200 rounded-t-[2.5rem] sm:rounded-[2.5rem] p-8">
        <div class="w-16 h-16 rounded-3xl bg-error/10 flex items-center justify-center text-error mx-auto mb-4">
          <Icon name="mingcute:alert-line" size="32" />
        </div>
        <h3 class="text-xl font-black text-base-content">Hapus Anggota</h3>
        <p class="py-4 text-base-content/60 text-sm">Hapus anggota tim ini secara permanen?</p>
        <div class="flex gap-2 justify-center mt-2 w-full">
          <button @click="showDeleteModal = false" class="btn btn-ghost rounded-2xl flex-1">Batal</button>
          <button @click="deleteMember" class="btn btn-error rounded-2xl flex-1">Hapus</button>
        </div>
      </div>
    </dialog>
  </div>
</template>
