// pages/login.vue
<script setup>
definePageMeta({ layout: false })

import { storeToRefs } from 'pinia';
import { useAuthStore } from '~/store/useAuthStore';
const { authenticateUser } = useAuthStore()
const { authenticated } = storeToRefs(useAuthStore())
const router = useRouter()

const user = ref({ NIS: '', Password: '', force: false })
const error = ref(false)
const errorMessage = ref('')
const isLoading = ref(false)
const showPassword = ref(false)

const login = async () => {
  error.value = false
  isLoading.value = true
  try {
    await authenticateUser(user.value)
    if (authenticated.value) {
      router.push('/home')
    }
  } catch (err) {
    error.value = true
    // Robust error message extraction
    const rawError = err.data?.data || err.data || err
    if (typeof rawError === 'string') {
      errorMessage.value = { error: rawError }
    } else if (rawError.message && !rawError.error) {
      errorMessage.value = { error: rawError.message, ...rawError }
    } else {
      errorMessage.value = rawError
    }
  } finally {
    isLoading.value = false
  }
}

const forceLogin = async () => {
  user.value.force = true
  await authenticateUser(user.value)
  if (authenticated.value) {
    router.push('/home')
  }
}

useSeoMeta({
  title: 'Login | GASKAN',
  ogTitle: 'Login | GASKAN',
  description: 'Login ke Gerbang Akses Pintar dan Kehadiran',
  image: '/banner.webp',
  url: 'https://gaskan.smtijogja.sch.id/login',
  ogUrl: 'https://gaskan.smtijogja.sch.id/login',
  ogDescription: 'Login ke Gerbang Akses Pintar dan Kehadiran',
  ogImage: '/banner.webp',
  ogType: 'website',
  ogSiteName: 'GASKAN',
  ogLocale: 'id_ID',
  twitterCard: 'summary_large_image',
  twitterTitle: 'Login | GASKAN',
  twitterDescription: 'Login ke Gerbang Akses Pintar dan Kehadiran',
  twitterImage: '/banner.webp',
  twitterUrl: 'https://gaskan.smtijogja.sch.id/login',
})
</script>

<template>
  <div class="min-h-screen flex items-stretch">
    <!-- Left panel: Branding -->
    <div class="hidden lg:flex lg:w-1/2 bg-primary/10 border-r border-base-300 relative overflow-hidden flex-col items-center justify-center p-12 gap-8">
      <!-- Background blobs -->
      <div class="absolute top-0 left-0 w-72 h-72 bg-primary/20 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2 pointer-events-none" />
      <div class="absolute bottom-0 right-0 w-96 h-96 bg-primary/10 rounded-full blur-3xl translate-x-1/3 translate-y-1/3 pointer-events-none" />

      <div class="relative z-10 text-center space-y-6 max-w-sm">
        <!-- Logo -->
        <div class="flex items-center justify-center gap-3 mb-4">
          <div class="w-14 h-14 rounded-2xl bg-primary/15 border border-primary/30 flex items-center justify-center">
            <Icon name="mingcute:key-2-fill" class="text-3xl text-primary" />
          </div>
          <span class="text-3xl font-extrabold">GASKAN</span>
        </div>

        <h2 class="text-2xl font-bold leading-tight">
          Sistem Absensi Digital<br />
          <span class="text-primary">SMTI Jogja</span>
        </h2>
        <p class="opacity-50 text-sm leading-relaxed">
          Kelola dan pantau kehadiran siswa secara real-time dengan mudah, cepat, dan akurat.
        </p>

        <!-- Stats preview -->
        <div class="grid grid-cols-3 gap-3 pt-4">
          <div class="bg-base-100/60 rounded-xl p-3 border border-base-300">
            <p class="text-xl font-bold text-primary">500+</p>
            <p class="text-xs opacity-50 mt-0.5">Siswa</p>
          </div>
          <div class="bg-base-100/60 rounded-xl p-3 border border-base-300">
            <p class="text-xl font-bold text-primary">3</p>
            <p class="text-xs opacity-50 mt-0.5">Role</p>
          </div>
          <div class="bg-base-100/60 rounded-xl p-3 border border-base-300">
            <p class="text-xl font-bold text-primary">99.9%</p>
            <p class="text-xs opacity-50 mt-0.5">Uptime</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Right panel: Login form -->
    <div class="w-full lg:w-1/2 flex items-center justify-center p-6">
      <div class="w-full max-w-md space-y-8">
        <!-- Mobile logo -->
        <div class="flex lg:hidden items-center gap-2 mb-2">
          <Icon name="mingcute:key-2-fill" class="text-primary text-2xl" />
          <span class="text-xl font-extrabold">GASKAN</span>
        </div>

        <!-- Heading -->
        <div class="space-y-1">
          <h1 class="text-3xl font-extrabold">Selamat Datang</h1>
          <p class="opacity-50 text-sm">Masuk dengan NIS / Email dan password kamu</p>
        </div>

        <!-- Error alert -->
        <Transition name="fade">
          <div v-if="error" class="alert alert-error rounded-xl text-sm py-3 px-4 flex items-start gap-3 border-none shadow-lg shadow-error/20 bg-error text-error-content">
            <Icon name="mingcute:warning-fill" class="text-xl shrink-0 mt-0.5" />
            <div class="flex-1 flex flex-col gap-1 text-left">
              <span class="font-bold">Login Gagal</span>
              <span class="opacity-90 leading-tight">{{ errorMessage.error || errorMessage.message || 'Email/NIS atau password salah' }}</span>
            </div>
            <button
              v-if="errorMessage.code === 400"
              @click.prevent="forceLogin"
              class="btn btn-xs btn-ghost bg-white/20 hover:bg-white/30"
            >
              Paksa Masuk
            </button>
          </div>
        </Transition>

        <!-- Form -->
        <form class="space-y-5" @submit.prevent="login">
          <!-- NIS / Email field -->
          <div class="space-y-2">
            <label for="nis" class="block text-sm font-semibold">NIS / Email</label>
            <div class="relative">
              <div class="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none">
                <Icon name="mingcute:user-4-line" class="text-lg opacity-40" />
              </div>
              <input
                type="text"
                id="nis"
                v-model="user.NIS"
                placeholder="Masukkan NIS / Email kamu"
                required
                class="input input-bordered w-full pl-10 rounded-xl bg-base-200 border-base-300 focus:border-primary focus:outline-none"
              />
            </div>
          </div>

          <!-- Password field -->
          <div class="space-y-2">
            <div class="flex items-center justify-between">
              <label for="password" class="block text-sm font-semibold">Password</label>
              <NuxtLink to="/forgot-password" class="text-xs font-bold text-primary hover:opacity-80 transition-opacity">
                Lupa Password?
              </NuxtLink>
            </div>
            <div class="relative">
              <div class="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none">
                <Icon name="mingcute:lock-line" class="text-lg opacity-40" />
              </div>
              <input
                :type="showPassword ? 'text' : 'password'"
                id="password"
                v-model="user.Password"
                placeholder="••••••••"
                required
                class="input input-bordered w-full pl-10 pr-12 rounded-xl bg-base-200 border-base-300 focus:border-primary focus:outline-none"
              />
              <button
                type="button"
                @click="showPassword = !showPassword"
                class="absolute inset-y-0 right-0 pr-3.5 flex items-center opacity-40 hover:opacity-80 transition-opacity"
              >
                <Icon :name="showPassword ? 'mingcute:eye-close-line' : 'mingcute:eye-line'" class="text-lg" />
              </button>
            </div>
          </div>

          <!-- Submit -->
          <button
            id="login-submit"
            type="submit"
            :disabled="isLoading"
            class="btn btn-primary w-full rounded-xl font-bold text-base shadow-lg hover:shadow-primary/30 transition-shadow"
          >
            <Icon v-if="isLoading" name="mingcute:loading-3-line" class="animate-spin mr-2" />
            <span>{{ isLoading ? 'Memproses...' : 'Masuk ke GASKAN' }}</span>
          </button>
        </form>

        <p class="text-center text-sm opacity-40">
          <NuxtLink to="/" class="hover:opacity-80 transition-opacity hover:text-primary">
            ← Kembali ke halaman utama
          </NuxtLink>
        </p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active, .fade-leave-active { transition: opacity 0.3s, transform 0.3s; }
.fade-enter-from, .fade-leave-to { opacity: 0; transform: translateY(-8px); }
</style>

// app/(auth)/login/page.tsx
'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { goeyToast as toast } from 'goey-toast';
import { Icon } from '@/components/ui/icon';
import api from '@/lib/api';
import { useAuth } from '@/context/AuthContext';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';

export default function LoginPage() {
  const router = useRouter();
  const { login } = useAuth();
  const [identifier, setIdentifier] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [errorData, setErrorData] = useState<{ message?: string; code?: number; canForce?: boolean; is502?: boolean } | null>(null);

  const performLogin = async (force: boolean = false) => {
    if (!identifier || !password) {
      toast.error('Silakan isi NIS / Email dan Password');
      return;
    }

    setIsLoading(true);
    setErrorData(null);

    const loginPayload = {
      NIS: identifier.trim(),
      Password: password,
      force: force,
    };

    try {
      let resData: any = null;

      try {
        const response = await api.post('/auth/login', loginPayload);
        resData = response.data;
      } catch (err1: any) {
        if (err1?.response?.status === 404) {
          const fallbackRes = await api.post('/login', loginPayload);
          resData = fallbackRes.data;
        } else {
          throw err1;
        }
      }

      const token =
        resData?.token ||
        resData?.data?.token ||
        resData?.sessionId ||
        resData?.access_token ||
        'session_' + Date.now();

      const userData = resData?.user || resData?.data?.user || resData?.data || {
        id: resData?.NIS || identifier,
        nis: resData?.NIS || identifier,
        name: resData?.Nama || resData?.name || identifier,
        role: (resData?.Kelas || resData?.role || 'siswa').toLowerCase(),
        email: identifier.includes('@') ? identifier : `${identifier}@smtijogja.sch.id`,
      };

      if (token && userData) {
        const formattedUser = {
          id: String(userData.id || userData.nis || identifier),
          name: userData.name || userData.nama || userData.Nama || identifier,
          email: userData.email || (identifier.includes('@') ? identifier : `${identifier}@smtijogja.sch.id`),
          role: String(userData.role || 'siswa').toLowerCase() as 'admin' | 'guru' | 'siswa',
          avatar: userData.photoUrl || userData.url_picture,
        };

        login(token, formattedUser);
        toast.success('Login berhasil! Selamat datang.');
        
        window.location.href = '/home';
      } else {
        throw new Error('Respon login dari server tidak valid');
      }
    } catch (err: any) {
      console.error('[LOGIN] API Error:', err?.response?.data || err);

      const errResponseData = err?.response?.data;
      const statusCode = err?.response?.status;
      const is502Error = statusCode === 502 || errResponseData?.status === 502 || errResponseData?.error_code === 502;
      
      let apiMessage = 'NIS/Email atau password yang Anda masukkan salah.';
      if (is502Error) {
        apiMessage = 'Server Backend sedang mengalami gangguan 502 Bad Gateway (Server sedang mati / dalam pemeliharaan).';
      } else if (err?.code === 'ERR_NETWORK') {
        apiMessage = 'Koneksi jaringan terputus (Network Error). Silakan periksa jaringan Anda.';
      } else if (errResponseData?.message) {
        apiMessage = errResponseData.message;
      } else if (errResponseData?.error) {
        apiMessage = errResponseData.error;
      }

      const canForceLogin = statusCode === 400 || errResponseData?.code === 400 || errResponseData?.forceAvailable;

      setErrorData({
        message: apiMessage,
        code: statusCode,
        canForce: canForceLogin,
        is502: is502Error,
      });

      toast.error(apiMessage);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDemoLogin = () => {
    const mockToken = 'demo-token-' + Date.now();
    const isDevRole = identifier.toLowerCase().includes('admin') || identifier.toLowerCase().includes('dev');
    const mockUser = {
      id: identifier || '12345',
      name: identifier ? (identifier.includes('@') ? identifier.split('@')[0] : identifier) : 'Pengguna Demo',
      email: identifier.includes('@') ? identifier : `${identifier || 'user'}@smtijogja.sch.id`,
      role: (isDevRole ? 'admin' : 'siswa') as 'admin' | 'guru' | 'siswa',
    };
    login(mockToken, mockUser);
    toast.success('Login Mode Demo Berhasil!');
    window.location.href = '/home';
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    performLogin(false);
  };

  const handleForceLogin = () => {
    performLogin(true);
  };

  return (
    <div className="flex min-h-dvh items-stretch bg-background lg:h-dvh lg:overflow-hidden">
      {/* Left panel: Branding */}
      <div className="relative hidden overflow-hidden border-r border-border bg-primary/10 p-8 lg:flex lg:w-1/2 lg:flex-col lg:items-center lg:justify-center lg:gap-8 xl:p-12">
        <div className="absolute top-0 left-0 w-72 h-72 bg-primary/20 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2 pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-96 h-96 bg-primary/10 rounded-full blur-3xl translate-x-1/3 translate-y-1/3 pointer-events-none" />

        <div className="relative z-10 text-center space-y-6 max-w-sm">
          <div className="flex items-center justify-center gap-3 mb-4">
            <div className="w-14 h-14 rounded-2xl bg-primary/15 border border-primary/30 flex items-center justify-center text-primary">
              <Icon icon="mingcute:key-2-fill" className="text-3xl" />
            </div>
            <span className="text-3xl font-extrabold tracking-tight">GASKAN</span>
          </div>

          <h2 className="text-2xl font-bold leading-tight">
            Sistem Absensi Digital<br />
            <span className="text-primary">SMTI Jogja</span>
          </h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            Kelola dan pantau kehadiran siswa secara real-time dengan mudah, cepat, dan akurat.
          </p>

          <div className="grid grid-cols-3 gap-3 pt-4">
            <div className="bg-card/80 rounded-xl p-3 border border-border">
              <p className="text-xl font-bold text-primary">500+</p>
              <p className="text-xs text-muted-foreground mt-0.5">Siswa</p>
            </div>
            <div className="bg-card/80 rounded-xl p-3 border border-border">
              <p className="text-xl font-bold text-primary">3</p>
              <p className="text-xs text-muted-foreground mt-0.5">Role</p>
            </div>
            <div className="bg-card/80 rounded-xl p-3 border border-border">
              <p className="text-xl font-bold text-primary">99.9%</p>
              <p className="text-xs text-muted-foreground mt-0.5">Uptime</p>
            </div>
          </div>
        </div>
      </div>

      {/* Right panel: Login form */}
      <div className="flex min-h-dvh w-full items-center justify-center overflow-y-auto overscroll-contain p-4 py-6 sm:p-8 lg:h-dvh lg:min-h-0 lg:w-1/2 lg:p-10 xl:p-12">
        <div className="w-full max-w-md space-y-4 sm:space-y-6">
          <div className="flex lg:hidden items-center gap-2 mb-2">
            <Icon icon="mingcute:key-2-fill" className="text-primary text-2xl" />
            <span className="text-xl font-extrabold">GASKAN</span>
          </div>

          <Card className="border-border shadow-md">
            <CardHeader className="space-y-1 px-4 sm:px-6">
              <CardTitle className="text-2xl font-bold">Selamat Datang</CardTitle>
              <CardDescription>
                Masuk dengan NIS / Email dan password kamu
              </CardDescription>
            </CardHeader>
            <CardContent className="px-4 sm:px-6">
              {errorData && (
                <div className="mb-4 flex min-w-0 flex-col gap-2 rounded-xl border border-destructive/30 bg-destructive/15 p-3.5 text-sm text-destructive">
                  <div className="flex min-w-0 items-start gap-2">
                    <Icon icon="mingcute:warning-fill" className="text-lg shrink-0 mt-0.5" />
                    <div className="min-w-0 flex-1">
                      <p className="font-bold text-sm">
                        {errorData.is502 ? 'Server Error (502 Bad Gateway)' : 'Login Gagal'}
                      </p>
                      <p className="break-words text-xs leading-snug opacity-90 [overflow-wrap:anywhere]">{errorData.message}</p>
                    </div>
                  </div>

                  {errorData.canForce && (
                    <Button
                      type="button"
                      size="sm"
                      variant="outline"
                      onClick={handleForceLogin}
                      className="mt-1 w-full self-end bg-destructive/20 text-xs font-bold text-destructive border-destructive/40 hover:bg-destructive/30 min-[420px]:w-auto"
                    >
                      Paksa Masuk
                    </Button>
                  )}

                  {errorData.is502 && (
                    <div className="flex flex-col gap-2 border-t border-destructive/20 pt-2 min-[420px]:flex-row min-[420px]:items-center min-[420px]:justify-between">
                      <span className="min-w-0 break-words text-[11px] opacity-80">Gunakan backend lokal atau mode demo:</span>
                      <Button
                        type="button"
                        size="sm"
                        onClick={handleDemoLogin}
                        className="w-full shrink-0 bg-primary text-xs font-bold text-primary-foreground min-[420px]:w-auto"
                      >
                        Masuk Mode Demo
                      </Button>
                    </div>
                  )}
                </div>
              )}

              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="nis">NIS / Email</Label>
                  <div className="relative">
                    <Icon icon="mingcute:user-4-line" className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-lg pointer-events-none" />
                    <Input
                      id="nis"
                      type="text"
                      placeholder="Masukkan NIS / Email kamu"
                      value={identifier}
                      onChange={(e) => setIdentifier(e.target.value)}
                      className="pl-9"
                      required
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="password">Password</Label>
                    <Link
                      href="/forgot-password"
                      className="text-xs font-semibold text-primary hover:underline"
                    >
                      Lupa Password?
                    </Link>
                  </div>
                  <div className="relative">
                    <Icon icon="mingcute:lock-line" className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-lg pointer-events-none" />
                    <Input
                      id="password"
                      type={showPassword ? 'text' : 'password'}
                      placeholder="••••••••"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      className="pl-9 pr-10"
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                      aria-label={showPassword ? 'Sembunyikan password' : 'Tampilkan password'}
                    >
                      <Icon icon={showPassword ? 'mingcute:eye-close-line' : 'mingcute:eye-line'} className="text-lg" />
                    </button>
                  </div>
                </div>

                <Button type="submit" className="w-full font-bold" disabled={isLoading}>
                  {isLoading && <Icon icon="mingcute:loading-3-line" className="animate-spin mr-2 text-lg" />}
                  {isLoading ? 'Memproses...' : 'Masuk ke GASKAN'}
                </Button>
              </form>
            </CardContent>
          <CardFooter className="flex justify-center border-t border-border px-4 pt-4 sm:px-6">
              <Link href="/" className="text-xs text-muted-foreground hover:text-primary transition-colors">
                ← Kembali ke halaman utama
              </Link>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  );
}
