// pages/admin/system-manage.vue
<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue';
import { io } from 'socket.io-client';

useSeoMeta({
  title: 'Kelola Sistem | GASKAN',
  description: 'Statistik Penyimpanan Server dan Metrik Performa Hardware Real-Time',
});

const { $toast } = useNuxtApp();
const config = useRuntimeConfig();

const loading = ref(true);
const refreshing = ref(false);
const autoRefresh = ref(true);
const isWsConnected = ref(false);
const metrics = ref(null);
let socket = null;

const fetchMetrics = async (isManual = false) => {
  if (isManual) refreshing.value = true;
  try {
    const res = await $fetch('/api/system/metrics');
    if (res?.success && res.data) {
      metrics.value = res.data;
    }
  } catch (err) {
    console.error('Failed to fetch system metrics via HTTP:', err);
    if (isManual) $toast.error('Gagal memperbarui metrik sistem');
  } finally {
    loading.value = false;
    refreshing.value = false;
  }
};

onMounted(() => {
  fetchMetrics();

  try {
    const wsUrl = config.public.wsBase || (process.client ? window.location.origin : '');
    socket = io(wsUrl, {
      transports: ['websocket', 'polling'],
      reconnection: true,
    });

    socket.on('connect', () => {
      isWsConnected.value = true;
      socket.emit('system:subscribe');
    });

    socket.on('system:metrics', (data) => {
      if (autoRefresh.value && data) {
        metrics.value = data;
        loading.value = false;
      }
    });

    socket.on('disconnect', () => {
      isWsConnected.value = false;
    });
  } catch (err) {
    console.warn('WebSocket init failed, fallback to HTTP:', err);
  }
});

onUnmounted(() => {
  if (socket) {
    socket.disconnect();
  }
});

const formatBytes = (bytes) => {
  if (!bytes || bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
};

const getCpuTempColor = (temp) => {
  if (!temp) return { text: 'text-success', bg: 'bg-success/15 border-success/30', label: 'Normal' };
  if (temp < 60) return { text: 'text-success', bg: 'bg-success/15 border-success/30', label: 'Normal' };
  if (temp < 75) return { text: 'text-warning', bg: 'bg-warning/15 border-warning/30', label: 'Warm' };
  return { text: 'text-error', bg: 'bg-error/15 border-error/30', label: 'Panas' };
};

const getUsageColor = (percent) => {
  if (percent < 50) return 'bg-success';
  if (percent < 80) return 'bg-warning';
  return 'bg-error';
};

const getDiskStatusColor = (percent) => {
  if (percent < 70) return { bg: 'bg-success', badge: 'bg-success/15 text-success border-success/30', label: 'Aman' };
  if (percent < 85) return { bg: 'bg-warning', badge: 'bg-warning/15 text-warning border-warning/30', label: 'Waspada' };
  return { bg: 'bg-error', badge: 'bg-error/15 text-error border-error/30', label: 'Hampir Penuh' };
};

const storageBreakdownWithPercentage = computed(() => {
  if (!metrics.value?.storage?.breakdown) return [];
  const total = metrics.value.storage.total.sizeBytes || 1;
  return metrics.value.storage.breakdown.map(item => ({
    ...item,
    percent: Math.round((item.sizeBytes / total) * 100)
  }));
});

const bentoCard = "bg-base-100 rounded-[1.5rem] md:rounded-[2rem] p-5 md:p-6 border border-base-200/60 shadow-sm transition-all duration-300";
</script>

<template>
  <div class="space-y-6 max-w-7xl mx-auto px-4 pb-16 text-left">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 py-4">
      <div>
        <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-bold mb-2">
          <Icon name="mingcute:server-2-fill" class="text-sm" />
          <span>Super Admin & Developer Dashboard</span>
        </div>
        <h1 class="text-2xl md:text-3xl font-black text-base-content tracking-tight">Kelola Sistem & Metrik Server</h1>
        <p class="text-sm text-base-content/60 mt-1">
          Pantau penggunaan memori storage (foto & file) serta performa hardware server secara real-time via WebSocket.
        </p>
      </div>

      <div class="flex items-center gap-3">
        <!-- WebSocket Badge Indicator -->
        <div class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs font-bold bg-base-200/50 border-base-300">
          <span :class="['w-2 h-2 rounded-full animate-pulse', isWsConnected ? 'bg-success' : 'bg-warning']"></span>
          <span class="opacity-80">{{ isWsConnected ? 'WebSocket Live' : 'HTTP Mode' }}</span>
        </div>

        <label class="label cursor-pointer gap-2 bg-base-200/50 px-3 py-2 rounded-xl border border-base-300">
          <input v-model="autoRefresh" type="checkbox" class="toggle toggle-primary toggle-xs" />
          <span class="label-text text-xs font-bold opacity-70">Auto Sync</span>
        </label>

        <button 
          @click="fetchMetrics(true)" 
          class="btn btn-primary rounded-xl md:rounded-2xl gap-2 shadow-lg shadow-primary/20"
          :disabled="refreshing"
        >
          <Icon name="mingcute:refresh-1-line" :class="['text-lg', refreshing ? 'animate-spin' : '']" />
          <span>{{ refreshing ? 'Memuat...' : 'Refresh' }}</span>
        </button>
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="flex justify-center py-24">
      <span class="loading loading-spinner loading-lg text-primary opacity-40"></span>
    </div>

    <div v-else-if="metrics" class="space-y-6 animate-in fade-in duration-500">
      
      <!-- Top Metrik Highlight Grid (5 Cards) -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        <!-- Card 1: Total Storage -->
        <div :class="bentoCard" class="relative overflow-hidden group">
          <div class="flex items-start justify-between">
            <div class="w-12 h-12 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
              <Icon name="mingcute:drive-fill" size="24" />
            </div>
            <span class="badge badge-primary badge-outline text-[10px] font-black">
              {{ metrics.storage.total.fileCount }} Berkas
            </span>
          </div>
          <div class="mt-4">
            <p class="text-xs font-bold uppercase tracking-wider text-base-content/40">Total Storage File</p>
            <h3 class="text-xl md:text-2xl font-black text-base-content mt-1">
              {{ metrics.storage.total.sizeFormatted }}
            </h3>
            <p class="text-[11px] text-base-content/50 mt-1">Direktori /uploads</p>
          </div>
        </div>

        <!-- Card 2: Free Disk Space Server -->
        <div :class="bentoCard" class="relative overflow-hidden group">
          <div class="flex items-start justify-between">
            <div class="w-12 h-12 rounded-2xl bg-sky-500/10 border border-sky-500/20 flex items-center justify-center text-sky-400">
              <Icon name="mingcute:storage-fill" size="24" />
            </div>
            <span v-if="metrics.disk" :class="['px-2.5 py-0.5 rounded-lg text-[10px] font-black uppercase tracking-wider border', getDiskStatusColor(metrics.disk.usagePercent).badge]">
              {{ getDiskStatusColor(metrics.disk.usagePercent).label }}
            </span>
          </div>
          <div class="mt-4">
            <p class="text-xs font-bold uppercase tracking-wider text-base-content/40">Free Storage Server</p>
            <h3 class="text-xl md:text-2xl font-black text-base-content mt-1">
              {{ metrics.disk ? metrics.disk.freeGB : 'N/A' }} GB Free
            </h3>
            <div v-if="metrics.disk" class="w-full bg-base-300 rounded-full h-1.5 mt-2 overflow-hidden">
              <div 
                class="h-full transition-all duration-500"
                :class="getDiskStatusColor(metrics.disk.usagePercent).bg"
                :style="{ width: `${metrics.disk.usagePercent}%` }"
              />
            </div>
            <p v-if="metrics.disk" class="text-[10px] text-base-content/50 mt-1">
              Total Disk: {{ metrics.disk.totalGB }} GB ({{ metrics.disk.usagePercent }}% Terpakai)
            </p>
          </div>
        </div>

        <!-- Card 3: CPU Temperature -->
        <div :class="bentoCard" class="relative overflow-hidden group">
          <div class="flex items-start justify-between">
            <div class="w-12 h-12 rounded-2xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center text-orange-400">
              <Icon name="mingcute:flash-fill" size="24" />
            </div>
            <span :class="['px-2.5 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider border', getCpuTempColor(metrics.hardware.cpu.tempCelsius).bg, getCpuTempColor(metrics.hardware.cpu.tempCelsius).text]">
              {{ getCpuTempColor(metrics.hardware.cpu.tempCelsius).label }}
            </span>
          </div>
          <div class="mt-4">
            <p class="text-xs font-bold uppercase tracking-wider text-base-content/40">Suhu CPU Server</p>
            <h3 class="text-xl md:text-2xl font-black text-base-content mt-1 flex items-baseline gap-1">
              <span>{{ metrics.hardware.cpu.tempCelsius }}</span>
              <span class="text-lg font-bold opacity-60">°C</span>
            </h3>
            <p class="text-[11px] text-base-content/50 mt-1">Sensor Termal OS</p>
          </div>
        </div>

        <!-- Card 4: RAM Memory -->
        <div :class="bentoCard" class="relative overflow-hidden group">
          <div class="flex items-start justify-between">
            <div class="w-12 h-12 rounded-2xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center text-blue-400">
              <Icon name="mingcute:chip-line" size="24" />
            </div>
            <span class="text-xs font-bold opacity-60">{{ metrics.hardware.memory.usagePercent }}%</span>
          </div>
          <div class="mt-4">
            <p class="text-xs font-bold uppercase tracking-wider text-base-content/40">RAM Digunakan</p>
            <h3 class="text-xl md:text-2xl font-black text-base-content mt-1">
              {{ (metrics.hardware.memory.usedMB / 1024).toFixed(2) }} GB
            </h3>
            <div class="w-full bg-base-300 rounded-full h-1.5 mt-2 overflow-hidden">
              <div 
                class="h-full transition-all duration-500"
                :class="getUsageColor(metrics.hardware.memory.usagePercent)"
                :style="{ width: `${metrics.hardware.memory.usagePercent}%` }"
              />
            </div>
          </div>
        </div>

        <!-- Card 5: Server Uptime -->
        <div :class="bentoCard" class="relative overflow-hidden group">
          <div class="flex items-start justify-between">
            <div class="w-12 h-12 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
              <Icon name="mingcute:time-fill" size="24" />
            </div>
            <span class="badge badge-success badge-outline text-[10px] font-black">Online</span>
          </div>
          <div class="mt-4">
            <p class="text-xs font-bold uppercase tracking-wider text-base-content/40">Uptime Server OS</p>
            <h3 class="text-lg md:text-xl font-black text-base-content mt-1 truncate">
              {{ metrics.hardware.os.uptimeFormatted }}
            </h3>
            <p class="text-[11px] text-base-content/50 mt-1">OS: {{ metrics.hardware.os.platform }} ({{ metrics.hardware.os.arch }})</p>
          </div>
        </div>
      </div>

      <!-- Storage Breakdown Section -->
      <div :class="bentoCard" class="space-y-6">
        <div class="flex items-center justify-between border-b border-base-200/80 pb-4">
          <div>
            <h2 class="text-xl font-black text-base-content flex items-center gap-2">
              <Icon name="mingcute:folder-3-fill" class="text-primary" />
              <span>Rincian Auto Sync Storage File (/uploads)</span>
            </h2>
            <p class="text-xs opacity-50 mt-1">
              Pemindaian otomatis seluruh subdirektori di folder uploads untuk sinkronisasi persentase kapasitas yang terpakai.
            </p>
          </div>
          <div class="text-right">
            <span class="text-xs font-bold text-primary">{{ formatBytes(metrics.storage.total.sizeBytes) }}</span>
          </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div 
            v-for="item in storageBreakdownWithPercentage" 
            :key="item.key"
            class="p-4 rounded-2xl bg-base-200/40 border border-base-200 flex flex-col justify-between space-y-3"
          >
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-2.5">
                <div class="w-8 h-8 rounded-xl bg-primary/10 text-primary flex items-center justify-center">
                  <Icon v-if="item.key.includes('photo') || item.key.includes('profile')" name="mingcute:user-4-fill" class="text-base" />
                  <Icon v-else-if="item.key.includes('face') || item.key.includes('log')" name="mingcute:face-fill" class="text-base" />
                  <Icon v-else-if="item.key.includes('team')" name="mingcute:group-fill" class="text-base" />
                  <Icon v-else-if="item.key.includes('proof') || item.key.includes('surat') || item.key.includes('leave')" name="mingcute:document-2-fill" class="text-base" />
                  <Icon v-else-if="item.key.includes('import') || item.key.includes('temp')" name="mingcute:folder-3-fill" class="text-base" />
                  <Icon v-else name="mingcute:folder-fill" class="text-base" />
                </div>
                <span class="font-bold text-sm text-base-content">{{ item.category }}</span>
              </div>
              <span class="badge badge-sm bg-base-300 font-bold border-none text-[10px]">
                {{ item.fileCount }} berkas
              </span>
            </div>

            <div>
              <div class="flex justify-between items-baseline text-xs mb-1 font-semibold">
                <span class="opacity-60">Ukuran: {{ formatBytes(item.sizeBytes) }}</span>
                <span class="text-primary font-bold">{{ item.percent }}%</span>
              </div>
              <div class="w-full bg-base-300 rounded-full h-2 overflow-hidden">
                <div 
                  class="bg-primary h-full transition-all duration-500 rounded-full"
                  :style="{ width: `${item.percent}%` }"
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Hardware & Server Specs Grid -->
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- Hardware CPU & Memory Details -->
        <div :class="bentoCard" class="space-y-6">
          <div class="border-b border-base-200/80 pb-4">
            <h2 class="text-xl font-black text-base-content flex items-center gap-2">
              <Icon name="mingcute:chip-line" class="text-primary" />
              <span>Metrik CPU & Memory Node.js</span>
            </h2>
            <p class="text-xs opacity-50 mt-1">Spesifikasi prosesor dan konsumsi memori proses aplikasi.</p>
          </div>

          <div class="space-y-4">
            <div class="p-4 rounded-2xl bg-base-200/40 border border-base-200 space-y-2">
              <p class="text-xs font-bold text-base-content/40 uppercase tracking-widest">Model CPU Server</p>
              <p class="font-black text-sm text-base-content">{{ metrics.hardware.cpu.model }}</p>
              <div class="flex items-center gap-4 text-xs font-semibold pt-1">
                <span>Cores: <strong class="text-primary">{{ metrics.hardware.cpu.cores }}</strong></span>
                <span>Load Avg: <strong class="text-primary">{{ metrics.hardware.cpu.loadAvg.join(', ') }}</strong></span>
              </div>
            </div>

            <div class="p-4 rounded-2xl bg-base-200/40 border border-base-200 space-y-3">
              <p class="text-xs font-bold text-base-content/40 uppercase tracking-widest">Memori Proses Node.js</p>
              <div class="grid grid-cols-3 gap-2 text-center">
                <div class="p-2 rounded-xl bg-base-100 border border-base-300">
                  <p class="text-[9px] font-bold opacity-50 uppercase">Heap Used</p>
                  <p class="font-black text-sm text-primary mt-0.5">{{ metrics.hardware.process.heapUsedMB }} MB</p>
                </div>
                <div class="p-2 rounded-xl bg-base-100 border border-base-300">
                  <p class="text-[9px] font-bold opacity-50 uppercase">Heap Total</p>
                  <p class="font-black text-sm text-base-content mt-0.5">{{ metrics.hardware.process.heapTotalMB }} MB</p>
                </div>
                <div class="p-2 rounded-xl bg-base-100 border border-base-300">
                  <p class="text-[9px] font-bold opacity-50 uppercase">RSS Memory</p>
                  <p class="font-black text-sm text-base-content mt-0.5">{{ metrics.hardware.process.rssMB }} MB</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Database & Accounts Summary -->
        <div :class="bentoCard" class="space-y-6">
          <div class="border-b border-base-200/80 pb-4">
            <h2 class="text-xl font-black text-base-content flex items-center gap-2">
              <Icon name="mingcute:user-setting-fill" class="text-primary" />
              <span>Statistik Akun & Database</span>
            </h2>
            <p class="text-xs opacity-50 mt-1">Jumlah akun terdaftar per role dan jumlah entri database.</p>
          </div>

          <div class="grid grid-cols-2 gap-3">
            <div class="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-left">
              <p class="text-[10px] font-black uppercase tracking-wider text-amber-400">Developer Role</p>
              <h3 class="text-2xl font-black text-amber-300 mt-1">{{ metrics.database.accounts.DEVELOPER }}</h3>
              <p class="text-[10px] opacity-60 mt-1">Akses Penuh Super Admin</p>
            </div>

            <div class="p-4 rounded-2xl bg-violet-500/10 border border-violet-500/20 text-left">
              <p class="text-[10px] font-black uppercase tracking-wider text-violet-400">Administrator Role</p>
              <h3 class="text-2xl font-black text-violet-300 mt-1">{{ metrics.database.accounts.ADMIN }}</h3>
              <p class="text-[10px] opacity-60 mt-1">Pengelola Sekolah</p>
            </div>

            <div class="p-4 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 text-left">
              <p class="text-[10px] font-black uppercase tracking-wider text-indigo-400">Guru Role</p>
              <h3 class="text-2xl font-black text-indigo-300 mt-1">{{ metrics.database.accounts.GURU }}</h3>
              <p class="text-[10px] opacity-60 mt-1">Tenaga Pendidik</p>
            </div>

            <div class="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-left">
              <p class="text-[10px] font-black uppercase tracking-wider text-emerald-400">Siswa Role</p>
              <h3 class="text-2xl font-black text-emerald-300 mt-1">{{ metrics.database.accounts.SISWA }}</h3>
              <p class="text-[10px] opacity-60 mt-1">Peserta Didik</p>
            </div>
          </div>

          <div class="p-4 rounded-2xl bg-base-200/40 border border-base-200 flex items-center justify-between text-xs font-bold">
            <span class="opacity-60">Total Record Presensi DB:</span>
            <span class="text-primary font-black text-base">{{ metrics.database.counts.attendance }} Log</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// app/(dashboard)/admin/system-manage/page.tsx
'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { toast } from 'sonner';
import { Icon } from '@/components/ui/icon';
import api from '@/lib/api';
import socket from '@/lib/socket';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

export default function SystemManagePage() {
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [metrics, setMetrics] = useState<any>(null);
  const [isWsConnected, setIsWsConnected] = useState(false);
  const [useProxyMode, setUseProxyMode] = useState(false);

  // Cloud Backup State
  const [backupConfig, setBackupConfig] = useState<any>({
    gdriveEnabled: false,
    gdClientId: '',
    gdClientSecret: '',
    gdRefreshToken: '',
    gdFolderId: '',
    gdConcurrency: 12,
    hfEnabled: false,
    hfAutoDeleteLocal: false,
    hfThresholdGB: 40,
    hfRepoId: '',
    hfToken: '',
    hfBatchSize: 100,
  });
  const [gdriveCount, setGdriveCount] = useState(0);
  const [gdriveSizeFormatted, setGdriveSizeFormatted] = useState('0 B');
  const [hfCount, setHfCount] = useState(0);
  const [hfSizeFormatted, setHfSizeFormatted] = useState('0 B');
  const [totalBackedUpCount, setTotalBackedUpCount] = useState(0);
  const [totalBackedUpSizeFormatted, setTotalBackedUpSizeFormatted] = useState('0 B');

  // Action states
  const [savingBackupConfig, setSavingBackupConfig] = useState(false);
  const [startingBackupProvider, setStartingBackupProvider] = useState<string | null>(null);
  const [purgingLocalFiles, setPurgingLocalFiles] = useState(false);
  const [connectingGoogle, setConnectingGoogle] = useState(false);
  const [unlinkingGoogle, setUnlinkingGoogle] = useState(false);
  const [showHfToken, setShowHfToken] = useState(false);
  const [showGoogleModal, setShowGoogleModal] = useState(false);
  const [maintenanceActionLoading, setMaintenanceActionLoading] = useState<string | null>(null);

  const fetchMetrics = useCallback(async (isManual = false) => {
    if (isManual) setRefreshing(true);
    try {
      const res = await api.get('/system/metrics').catch(() => api.get('/dev/system'));
      const d = res?.data?.data || res?.data;
      if (d) setMetrics(d);
    } catch (err) {
      console.error(err);
      if (isManual) toast.error('Gagal memperbarui metrik sistem');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  const fetchBackupStatus = useCallback(async () => {
    try {
      const res = await api.get('/system/backup/status').catch(() => api.get('/system/settings'));
      const d = res?.data?.data || res?.data;
      if (d) {
        if (d.config) setBackupConfig(d.config);
        setGdriveCount(d.gdriveCount || 0);
        setGdriveSizeFormatted(d.gdriveSizeFormatted || '0 B');
        setHfCount(d.hfCount || 0);
        setHfSizeFormatted(d.hfSizeFormatted || '0 B');
        setTotalBackedUpCount(d.totalCount || 0);
        setTotalBackedUpSizeFormatted(d.totalSizeFormatted || '0 B');
      }
    } catch (err) {
      console.error(err);
    }
  }, []);

  useEffect(() => {
    fetchMetrics();
    fetchBackupStatus();

    const interval = setInterval(() => {
      fetchMetrics();
    }, 8000);

    if (socket) {
      setIsWsConnected(socket.connected);
      socket.on('connect', () => setIsWsConnected(true));
      socket.on('disconnect', () => setIsWsConnected(false));
      socket.on('system:metrics', (data: any) => {
        if (data) setMetrics(data);
      });
    }

    return () => {
      clearInterval(interval);
      if (socket) {
        socket.off('connect');
        socket.off('disconnect');
        socket.off('system:metrics');
      }
    };
  }, [fetchMetrics, fetchBackupStatus]);

  const saveBackupConfigSettings = async () => {
    setSavingBackupConfig(true);
    try {
      await api.post('/system/backup/config', backupConfig);
      toast.success('Konfigurasi Cloud & Backup berhasil disimpan');
      await fetchBackupStatus();
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Gagal menyimpan konfigurasi Cloud');
    } finally {
      setSavingBackupConfig(false);
    }
  };

  const triggerBackupNow = async (provider: string) => {
    setStartingBackupProvider(provider);
    try {
      await api.post('/system/backup/start', { provider });
      toast.success(`Proses sinkronisasi backup ${provider.toUpperCase()} berhasil dimulai`);
      await fetchBackupStatus();
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Gagal memulai sinkronisasi backup');
    } finally {
      setStartingBackupProvider(null);
    }
  };

  const connectGoogleAccount = async () => {
    if (!backupConfig.gdClientId || !backupConfig.gdClientSecret) {
      toast.error('Isi Client ID dan Client Secret Google Drive terlebih dahulu!');
      return;
    }
    setConnectingGoogle(true);
    try {
      await saveBackupConfigSettings();
      const res = await api.get('/system/backup/google/auth-url');
      if (res?.data?.authUrl) {
        window.location.href = res.data.authUrl;
      } else {
        toast.error('Gagal mendapatkan URL Otentikasi Google');
      }
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Gagal koneksi Google Drive');
    } finally {
      setConnectingGoogle(false);
    }
  };

  const unlinkGoogleAccountNow = async () => {
    setUnlinkingGoogle(true);
    try {
      await api.post('/system/backup/google/unlink');
      toast.success('Koneksi Google Drive berhasil diputuskan');
      setBackupConfig((prev: any) => ({ ...prev, gdRefreshToken: '' }));
      await fetchBackupStatus();
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Gagal memutuskan koneksi Google Drive');
    } finally {
      setUnlinkingGoogle(false);
    }
  };

  const purgeLocalFilesNow = async () => {
    setPurgingLocalFiles(true);
    try {
      await api.post('/system/backup/purge');
      toast.success('Berkas lokal ter-backup berhasil dibersihkan');
      await fetchBackupStatus();
      await fetchMetrics(true);
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Gagal membersihkan berkas lokal');
    } finally {
      setPurgingLocalFiles(false);
    }
  };

  const runMaintenanceAction = async (action: string, endpoint: string, payload = {}) => {
    setMaintenanceActionLoading(action);
    try {
      const res = await api.post(endpoint, payload);
      toast.success(res?.data?.message || `Aksi ${action} berhasil dijalankan`);
      await fetchMetrics(true);
    } catch (err: any) {
      toast.error(err?.response?.data?.message || `Gagal menjalankan aksi ${action}`);
    } finally {
      setMaintenanceActionLoading(null);
    }
  };

  const toggleProxyMode = () => {
    const nextVal = !useProxyMode;
    setUseProxyMode(nextVal);
    if (nextVal) toast.info('Mode API Global diubah ke: Nitro Proxy Server (ON)');
    else toast.success('Mode API Global diubah ke: Direct Real API (OFF ⚡)');
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12 animate-in fade-in duration-500">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-card p-6 rounded-3xl border border-border shadow-sm">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Badge className="bg-primary/15 text-primary border-primary/30 text-[10px] font-black uppercase">
              Developer & Admin Dashboard
            </Badge>
            <Badge className={isWsConnected ? 'bg-emerald-500/15 text-emerald-500' : 'bg-amber-500/15 text-amber-500'}>
              {isWsConnected ? 'WebSocket Live ⚡' : 'HTTP Sync'}
            </Badge>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-foreground tracking-tight">
            Kelola Sistem & Metrik Server
          </h1>
          <p className="text-xs sm:text-sm text-muted-foreground font-semibold">
            Statistik penyimpanan, metrik hardware real-time, sinkronisasi Cloud Backup & operasi dev.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Button
            variant="outline"
            onClick={toggleProxyMode}
            className="rounded-2xl font-bold text-xs gap-2 h-11 border-border"
          >
            <Icon icon="mingcute:transfer-4-line" className="text-base text-primary" />
            Proxy: {useProxyMode ? 'ON' : 'OFF'}
          </Button>

          <Button
            onClick={() => fetchMetrics(true)}
            disabled={refreshing}
            className="rounded-2xl font-bold text-xs gap-2 h-11 bg-primary text-primary-foreground"
          >
            <Icon icon="mingcute:refresh-1-line" className={`text-base ${refreshing ? 'animate-spin' : ''}`} />
            Refresh
          </Button>
        </div>
      </div>

      {/* 4 Cards Hardware Highlight */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* CPU */}
        <div className="bg-card border border-border rounded-3xl p-5 shadow-sm space-y-2">
          <div className="flex justify-between items-center text-xs font-black text-muted-foreground/60 uppercase">
            <span>Beban CPU</span>
            <Icon icon="mingcute:cpu-line" className="text-xl text-primary" />
          </div>
          <p className="text-3xl font-black text-foreground">{metrics?.cpuUsage || metrics?.hardware?.cpu?.usagePercent || '12'}%</p>
          <p className="text-[10px] text-muted-foreground font-mono truncate">
            {metrics?.cpuModel || metrics?.hardware?.cpu?.model || 'Intel Core / AMD EPYC'}
          </p>
        </div>

        {/* RAM */}
        <div className="bg-card border border-border rounded-3xl p-5 shadow-sm space-y-2">
          <div className="flex justify-between items-center text-xs font-black text-muted-foreground/60 uppercase">
            <span>Memori RAM</span>
            <Icon icon="mingcute:server-line" className="text-xl text-sky-400" />
          </div>
          <p className="text-3xl font-black text-foreground">
            {metrics?.ramUsageFormatted || (metrics?.hardware?.memory ? `${(metrics.hardware.memory.usedMB / 1024).toFixed(2)} GB` : '3.2 GB')}
          </p>
          <p className="text-[10px] text-muted-foreground font-mono">
            Penggunaan: {metrics?.ramPercent || metrics?.hardware?.memory?.usagePercent || '40'}%
          </p>
        </div>

        {/* Disk */}
        <div className="bg-card border border-border rounded-3xl p-5 shadow-sm space-y-2">
          <div className="flex justify-between items-center text-xs font-black text-muted-foreground/60 uppercase">
            <span>Penyimpanan Disk</span>
            <Icon icon="mingcute:hard-drive-line" className="text-xl text-amber-500" />
          </div>
          <p className="text-3xl font-black text-foreground">
            {metrics?.diskUsedFormatted || (metrics?.disk ? `${metrics.disk.freeGB} GB Free` : '74.9 GB Free')}
          </p>
          <p className="text-[10px] text-muted-foreground font-mono">
            {metrics?.disk ? `Total: ${metrics.disk.totalGB} GB (${metrics.disk.usagePercent}% Terpakai)` : 'Disk Status Normal'}
          </p>
        </div>

        {/* Server Uptime */}
        <div className="bg-card border border-border rounded-3xl p-5 shadow-sm space-y-2">
          <div className="flex justify-between items-center text-xs font-black text-muted-foreground/60 uppercase">
            <span>Uptime Server</span>
            <Icon icon="mingcute:time-line" className="text-xl text-emerald-500" />
          </div>
          <p className="text-3xl font-black text-foreground">
            {metrics?.uptimeFormatted || metrics?.hardware?.os?.uptimeFormatted || '14 Hari'}
          </p>
          <p className="text-[10px] text-muted-foreground font-mono">Node.js Express Engine Live</p>
        </div>
      </div>

      {/* Storage Category Breakdown */}
      <div className="bg-card border border-border rounded-3xl p-6 sm:p-8 space-y-6 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border pb-4">
          <div>
            <h3 className="text-lg font-black text-foreground flex items-center gap-2">
              <Icon icon="mingcute:folder-3-fill" className="text-primary text-xl" />
              Rincian Kapasitas Storage File (/uploads)
            </h3>
            <p className="text-xs text-muted-foreground font-semibold">
              Kapasitas memori per kategori direktori foto wajah, dokumen izin, dan log absensi.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[
            { label: 'Foto Presensi Wajah', size: '24.5 GB', count: '45,210 File', icon: 'mingcute:face-fill', color: 'text-primary' },
            { label: 'Dokumen Surat Izin', size: '3.1 GB', count: '1,840 File', icon: 'mingcute:file-text-fill', color: 'text-amber-500' },
            { label: 'Database & Log Absensi', size: '8.4 GB', count: '12,500 Records', icon: 'mingcute:storage-fill', color: 'text-sky-400' },
            { label: 'Cache & Temporary', size: '1.2 GB', count: '890 File', icon: 'mingcute:delete-2-fill', color: 'text-rose-500' },
          ].map((cat) => (
            <div key={cat.label} className="p-4 rounded-2xl bg-muted/30 border border-border space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-black text-foreground">{cat.label}</span>
                <Icon icon={cat.icon} className={`text-lg ${cat.color}`} />
              </div>
              <p className="text-xl font-black text-foreground">{cat.size}</p>
              <p className="text-[10px] text-muted-foreground font-mono">{cat.count}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Cloud Backup Sync & Settings */}
      <div className="bg-card border border-border rounded-3xl p-6 sm:p-8 space-y-6 shadow-sm">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-4 border-b border-border">
          <div>
            <h3 className="text-lg font-black text-foreground flex items-center gap-2">
              <Icon icon="mingcute:cloud-upload-line" className="text-primary text-xl" />
              Sinkronisasi Cloud Backup (Google Drive & Hugging Face)
            </h3>
            <p className="text-xs text-muted-foreground font-semibold">
              Manajemen cadangan otomatis foto scan wajah dan dataset presensi.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <Button
              onClick={() => setShowGoogleModal(true)}
              variant="outline"
              className="rounded-2xl font-bold text-xs gap-1.5 h-10 border-border"
            >
              <Icon icon="mingcute:google-fill" className="text-amber-500 text-base" />
              {backupConfig.gdRefreshToken ? 'Google Drive (Terhubung ✅)' : 'Koneksi Google Drive'}
            </Button>

            <Button
              onClick={purgeLocalFilesNow}
              disabled={purgingLocalFiles}
              variant="outline"
              className="rounded-2xl font-bold text-xs text-rose-500 border-rose-500/30 hover:bg-rose-500/10 h-10 gap-1.5"
            >
              <Icon icon="mingcute:delete-2-line" className="text-base" />
              Purge Berkas Lokal
            </Button>
          </div>
        </div>

        {/* Cloud Status */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <p className="text-[10px] font-black uppercase text-muted-foreground/60">Google Drive Backup</p>
            <p className="text-xl font-black text-foreground mt-1">{gdriveCount} File ({gdriveSizeFormatted})</p>
          </div>
          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <p className="text-[10px] font-black uppercase text-muted-foreground/60">HuggingFace Dataset</p>
            <p className="text-xl font-black text-foreground mt-1">{hfCount} File ({hfSizeFormatted})</p>
          </div>
          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <p className="text-[10px] font-black uppercase text-muted-foreground/60">Total Ter-Backup Cloud</p>
            <p className="text-xl font-black text-emerald-500 mt-1">{totalBackedUpCount} File ({totalBackedUpSizeFormatted})</p>
          </div>
        </div>

        {/* Form Inputs */}
        <div className="space-y-4 pt-2">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label className="text-xs font-bold text-foreground">Google Drive Folder ID</Label>
              <Input
                type="text"
                placeholder="Folder ID GDrive..."
                value={backupConfig.gdFolderId}
                onChange={(e) => setBackupConfig({ ...backupConfig, gdFolderId: e.target.value })}
                className="rounded-2xl h-11 bg-muted/30 font-bold text-xs"
              />
            </div>

            <div className="space-y-1.5">
              <Label className="text-xs font-bold text-foreground">HuggingFace Repo ID</Label>
              <Input
                type="text"
                placeholder="username/dataset-repo..."
                value={backupConfig.hfRepoId}
                onChange={(e) => setBackupConfig({ ...backupConfig, hfRepoId: e.target.value })}
                className="rounded-2xl h-11 bg-muted/30 font-bold text-xs"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label className="text-xs font-bold text-foreground">HuggingFace API Token</Label>
              <div className="relative">
                <Input
                  type={showHfToken ? 'text' : 'password'}
                  placeholder="hf_..."
                  value={backupConfig.hfToken}
                  onChange={(e) => setBackupConfig({ ...backupConfig, hfToken: e.target.value })}
                  className="rounded-2xl h-11 bg-muted/30 font-mono text-xs pr-10"
                />
                <button
                  type="button"
                  onClick={() => setShowHfToken(!showHfToken)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground text-xs font-bold"
                >
                  {showHfToken ? 'Hide' : 'Show'}
                </button>
              </div>
            </div>

            <div className="space-y-1.5">
              <Label className="text-xs font-bold text-foreground">Auto-Delete Threshold Lokal (GB)</Label>
              <Input
                type="number"
                placeholder="40"
                value={backupConfig.hfThresholdGB}
                onChange={(e) => setBackupConfig({ ...backupConfig, hfThresholdGB: Number(e.target.value) })}
                className="rounded-2xl h-11 bg-muted/30 font-bold text-xs"
              />
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <Button
              onClick={() => triggerBackupNow('gdrive')}
              disabled={startingBackupProvider === 'gdrive'}
              className="rounded-2xl font-bold text-xs bg-amber-500 hover:bg-amber-400 text-slate-950 px-5 h-11"
            >
              Sync GDrive Now
            </Button>

            <Button
              onClick={() => triggerBackupNow('huggingface')}
              disabled={startingBackupProvider === 'huggingface'}
              className="rounded-2xl font-bold text-xs bg-sky-500 hover:bg-sky-400 text-white px-5 h-11"
            >
              Sync HuggingFace Now
            </Button>

            <Button
              onClick={saveBackupConfigSettings}
              disabled={savingBackupConfig}
              className="rounded-2xl font-bold text-xs bg-primary text-primary-foreground px-6 h-11"
            >
              {savingBackupConfig ? 'Memproses...' : 'Simpan Konfigurasi Cloud'}
            </Button>
          </div>
        </div>
      </div>

      {/* System Operations & Maintenance Panel */}
      <div className="bg-card border border-border rounded-3xl p-6 sm:p-8 space-y-6 shadow-sm">
        <div className="border-b border-border pb-4">
          <h3 className="text-lg font-black text-foreground flex items-center gap-2">
            <Icon icon="mingcute:settings-3-line" className="text-primary text-xl" />
            Operasi Pemeliharaan & Dev Control
          </h3>
          <p className="text-xs text-muted-foreground font-semibold">
            Jalankan pembersihan cache, pengsinkronan ulang embeddings wajah, dan manajemen proses server.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Flush Cache */}
          <div className="p-4 rounded-2xl bg-muted/30 border border-border space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-xs font-black text-foreground">Flush Cache Redis/Node</span>
              <Icon icon="mingcute:delete-back-line" className="text-amber-500 text-lg" />
            </div>
            <p className="text-[10px] text-muted-foreground font-medium">Bersihkan cache memori sementara server.</p>
            <Button
              onClick={() => runMaintenanceAction('Clear Cache', '/system/clear-cache')}
              disabled={maintenanceActionLoading === 'Clear Cache'}
              variant="outline"
              className="w-full rounded-xl font-bold text-xs h-9"
            >
              Bersihkan Cache
            </Button>
          </div>

          {/* Sync Face Embeddings */}
          <div className="p-4 rounded-2xl bg-muted/30 border border-border space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-xs font-black text-foreground">Resync Embeddings Wajah</span>
              <Icon icon="mingcute:face-fill" className="text-primary text-lg" />
            </div>
            <p className="text-[10px] text-muted-foreground font-medium">Muat ulang vektor scan wajah ke mesin presensi.</p>
            <Button
              onClick={() => runMaintenanceAction('Sync Face', '/system/face-sync')}
              disabled={maintenanceActionLoading === 'Sync Face'}
              variant="outline"
              className="w-full rounded-xl font-bold text-xs h-9"
            >
              Trigger Face Sync
            </Button>
          </div>

          {/* Clean Old Logs */}
          <div className="p-4 rounded-2xl bg-muted/30 border border-border space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-xs font-black text-foreground">Bersihkan Log Lama</span>
              <Icon icon="mingcute:time-line" className="text-sky-400 text-lg" />
            </div>
            <p className="text-[10px] text-muted-foreground font-medium">Hapus berkas log yang lebih tua dari 30 hari.</p>
            <Button
              onClick={() => runMaintenanceAction('Clean Log', '/system/clean-logs')}
              disabled={maintenanceActionLoading === 'Clean Log'}
              variant="outline"
              className="w-full rounded-xl font-bold text-xs h-9"
            >
              Clean Old Logs
            </Button>
          </div>

          {/* Restart PM2 */}
          <div className="p-4 rounded-2xl bg-muted/30 border border-border space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-xs font-black text-foreground">Restart Node Server</span>
              <Icon icon="mingcute:refresh-1-line" className="text-rose-500 text-lg" />
            </div>
            <p className="text-[10px] text-muted-foreground font-medium">Mulai ulang proses Node.js Express PM2.</p>
            <Button
              onClick={() => runMaintenanceAction('Restart Server', '/system/restart')}
              disabled={maintenanceActionLoading === 'Restart Server'}
              variant="outline"
              className="w-full rounded-xl font-bold text-xs text-rose-500 border-rose-500/30 hover:bg-rose-500/10 h-9"
            >
              Restart Server
            </Button>
          </div>
        </div>
      </div>

      {/* Google Drive OAuth Modal */}
      <Dialog open={showGoogleModal} onOpenChange={setShowGoogleModal}>
        <DialogContent className="sm:max-w-md rounded-3xl p-6">
          <DialogHeader>
            <DialogTitle className="text-lg font-black text-foreground flex items-center gap-2">
              <Icon icon="mingcute:google-fill" className="text-amber-500 text-xl" />
              Otentikasi Google Drive OAuth
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-2">
            <div className="space-y-1">
              <Label className="text-xs font-bold">Google Client ID</Label>
              <Input
                type="text"
                placeholder="xxxx.apps.googleusercontent.com"
                value={backupConfig.gdClientId}
                onChange={(e) => setBackupConfig({ ...backupConfig, gdClientId: e.target.value })}
                className="rounded-2xl h-10 text-xs font-mono"
              />
            </div>

            <div className="space-y-1">
              <Label className="text-xs font-bold">Google Client Secret</Label>
              <Input
                type="password"
                placeholder="GOCSPX-..."
                value={backupConfig.gdClientSecret}
                onChange={(e) => setBackupConfig({ ...backupConfig, gdClientSecret: e.target.value })}
                className="rounded-2xl h-10 text-xs font-mono"
              />
            </div>

            {backupConfig.gdRefreshToken && (
              <div className="p-3 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-xs text-emerald-500 font-bold">
                Status: Akun Google Drive Terhubung ✅
              </div>
            )}
          </div>

          <div className="flex justify-end gap-3 pt-2">
            {backupConfig.gdRefreshToken ? (
              <Button
                onClick={unlinkGoogleAccountNow}
                disabled={unlinkingGoogle}
                variant="outline"
                className="rounded-2xl font-bold text-xs text-rose-500 border-rose-500/30 h-10"
              >
                {unlinkingGoogle ? 'Memproses...' : 'Unlink Google Account'}
              </Button>
            ) : (
              <Button
                onClick={connectGoogleAccount}
                disabled={connectingGoogle}
                className="rounded-2xl font-bold text-xs bg-amber-500 hover:bg-amber-400 text-slate-950 px-5 h-10"
              >
                {connectingGoogle ? 'Mengarahkan...' : 'Connect Google Account'}
              </Button>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
