// gaskan-next/app/team/page.tsx
'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import Link from 'next/link';
import { Icon } from '@iconify/react';
import api from '@/lib/api';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { LandingNavbar } from '@/components/landing/LandingNavbar';
import { LandingFooter } from '@/components/landing/LandingFooter';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'https://api.tierkun.my.id';

const resolvePhoto = (url?: string) => {
  if (!url) return null;
  if (url.startsWith('http')) return url;
  if (url.startsWith('/uploads/team/')) return `${API_BASE}${url}`;
  return `${API_BASE}${url.startsWith('/') ? '' : '/'}${url}`;
};

const parseCustomLinks = (raw?: any) => {
  if (!raw) return [];
  if (typeof raw === 'string') {
    try {
      const p = JSON.parse(raw);
      return Array.isArray(p) ? p : [];
    } catch {
      return [];
    }
  }
  return Array.isArray(raw) ? raw : [];
};

const roleColor = (roleStr?: string) => {
  if (!roleStr) return 'text-muted-foreground bg-muted/20 border-border';
  if (roleStr.includes('Backend')) return 'text-sky-400 bg-sky-500/10 border-sky-500/20';
  if (roleStr.includes('Frontend')) return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';
  if (roleStr.includes('Hardware') || roleStr.includes('Electrical') || roleStr.includes('Mechanical'))
    return 'text-amber-400 bg-amber-500/10 border-amber-500/20';
  if (roleStr.includes('Pembimbing')) return 'text-primary bg-primary/10 border-primary/20';
  return 'text-purple-400 bg-purple-500/10 border-purple-500/20';
};

export default function PublicTeamPage() {
  const [team, setTeam] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedMember, setSelectedMember] = useState<any>(null);

  const fetchTeam = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get('/team').catch(() => null);
      const data = res?.data?.data || res?.data;
      if (Array.isArray(data)) {
        setTeam(data.filter((m: any) => m.isActive !== false));
      }
    } catch (err) {
      console.error('Failed to fetch team members:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchTeam();
  }, [fetchTeam]);

  const groupedTeam = useMemo(() => {
    const pembimbing: any[] = [];
    const pengembang: any[] = [];

    team.forEach((m) => {
      const isPembimbing = (m.role || '').toLowerCase().includes('pembimbing');
      if (isPembimbing) {
        pembimbing.push(m);
      } else {
        pengembang.push(m);
      }
    });

    pembimbing.sort((a, b) => (a.order || 0) - (b.order || 0));
    pengembang.sort((a, b) => (a.order || 0) - (b.order || 0));

    const res: any[] = [];
    if (pembimbing.length > 0) {
      res.push({
        title: 'Pembimbing',
        icon: 'mingcute:school-fill',
        members: pembimbing,
      });
    }
    if (pengembang.length > 0) {
      res.push({
        title: 'Tim Pengembang',
        icon: 'mingcute:code-fill',
        members: pengembang,
      });
    }
    return res;
  }, [team]);

  const getSocmed = (m: any) => {
    const socmed: any[] = [];
    if (m.instagram) socmed.push({ name: 'Instagram', link: m.instagram, icon: 'mingcute:ins-line' });
    if (m.linkedin) socmed.push({ name: 'LinkedIn', link: m.linkedin, icon: 'mingcute:linkedin-line' });
    if (m.github) socmed.push({ name: 'GitHub', link: m.github, icon: 'mingcute:github-line' });

    const custom = parseCustomLinks(m.customLinks);
    custom.forEach((item: any) => {
      if (item.url) {
        socmed.push({ name: item.label || 'Link', link: item.url, icon: item.icon || 'mingcute:link-2-line' });
      }
    });

    return socmed;
  };

  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground animate-in fade-in duration-500">
      {/* Public Landing Navbar */}
      <LandingNavbar />

      <main className="flex-1 py-12 px-4 sm:px-6 max-w-5xl mx-auto w-full space-y-12">
        {/* Top Header */}
        <div className="text-center space-y-3 pt-6">
          <div className="inline-flex items-center gap-2 bg-primary/10 text-primary text-xs font-bold px-4 py-1.5 rounded-full border border-primary/20">
            <Icon icon="mingcute:group-fill" className="text-base" />
            <span>Tim GASKAN</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-black text-foreground tracking-tight">
            Orang-orang di Balik <span className="text-primary">GASKAN</span>
          </h1>
          <p className="text-muted-foreground max-w-md mx-auto text-xs sm:text-sm leading-relaxed font-semibold">
            Tim multidisiplin yang membangun dan menjaga sistem kehadiran digital SMTI Jogja.
          </p>
        </div>

        {loading ? (
          <div className="flex justify-center py-20">
            <Icon icon="mingcute:loading-fill" className="text-4xl text-primary animate-spin" />
          </div>
        ) : groupedTeam.length === 0 ? (
          <div className="text-center py-16 bg-card rounded-3xl border border-border text-muted-foreground/60 font-bold text-xs uppercase tracking-wider">
            Belum ada data anggota tim
          </div>
        ) : (
          <div className="space-y-12">
            {groupedTeam.map((group) => (
              <div key={group.title} className="space-y-6">
                {/* Section Header */}
                <div className="flex items-center justify-between border-b border-border pb-3">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-2xl bg-primary/10 text-primary flex items-center justify-center">
                      <Icon icon={group.icon} className="text-xl" />
                    </div>
                    <div>
                      <h2 className="text-xl font-black text-foreground">{group.title}</h2>
                      <p className="text-xs text-muted-foreground font-semibold">
                        {group.title === 'Pembimbing' ? 'Pembimbing dan penanggung jawab proyek GASKAN.' : 'Anggota tim pengembang dan pembuat sistem GASKAN.'}
                      </p>
                    </div>
                  </div>
                  <Badge className="bg-primary/10 text-primary border-primary/20 text-xs font-bold">
                    {group.members.length} Orang
                  </Badge>
                </div>

                {/* Team Grid */}
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
                  {group.members.map((member: any) => {
                    const photo = resolvePhoto(member.photoUrl);
                    const socmedList = getSocmed(member);

                    return (
                      <div
                        key={member.id}
                        onClick={() => setSelectedMember(member)}
                        className="bg-card rounded-2xl border border-border hover:border-primary/40 p-4 sm:p-5 flex flex-col justify-between transition-all duration-300 hover:shadow-lg hover:-translate-y-1 cursor-pointer space-y-3 group"
                      >
                        <div className="space-y-3">
                          <div className="flex items-start justify-between gap-2">
                            <div className="w-12 h-12 sm:w-14 sm:h-14 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center overflow-hidden shrink-0 group-hover:scale-105 transition-transform">
                              {photo && !photo.includes('0000') ? (
                                <img src={photo} alt={member.name} className="w-full h-full object-cover" />
                              ) : (
                                <Icon icon="mingcute:user-4-fill" className="text-2xl text-primary/60" />
                              )}
                            </div>
                            {member.year && (
                              <Badge variant="outline" className="text-[9px] font-black text-muted-foreground">
                                {member.year}
                              </Badge>
                            )}
                          </div>

                          <div className="text-left space-y-1">
                            <h3 className="font-bold text-xs sm:text-sm text-foreground group-hover:text-primary transition-colors line-clamp-2">
                              {member.name}
                            </h3>
                            <p className={`text-[11px] sm:text-xs font-semibold ${roleColor(member.role).split(' ')[0]}`}>
                              {member.role || 'Anggota Tim'}
                            </p>
                            {member.bio && (
                              <p className="text-[10px] text-muted-foreground/70 italic line-clamp-2 leading-relaxed mt-1">
                                "{member.bio}"
                              </p>
                            )}
                          </div>
                        </div>

                        {/* Social Links */}
                        {socmedList.length > 0 && (
                          <div className="flex flex-wrap gap-1.5 pt-2 border-t border-border">
                            {socmedList.map((s, idx) => (
                              <a
                                key={idx}
                                href={s.link}
                                target="_blank"
                                rel="noreferrer"
                                onClick={(e) => e.stopPropagation()}
                                className="text-muted-foreground hover:text-primary transition-colors p-1 rounded-lg hover:bg-primary/10 text-xs"
                              >
                                <Icon icon={s.icon} className="text-sm" />
                              </a>
                            ))}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        )}
      </main>

      {/* MEMBER DETAIL MODAL */}
      {selectedMember && (
        <Dialog open={!!selectedMember} onOpenChange={() => setSelectedMember(null)}>
          <DialogContent className="sm:max-w-md p-6 sm:p-8 rounded-[2.5rem] bg-card border border-border space-y-5 relative overflow-hidden">
            {/* Header Decorative Background Gradient */}
            <div className="absolute top-0 left-0 right-0 h-28 bg-gradient-to-b from-primary/15 to-transparent pointer-events-none" />

            <DialogHeader className="p-0 border-none bg-transparent text-center space-y-3 relative z-10 pt-2">
              {/* Large Avatar Frame with Glowing Siluet Border */}
              <div className="w-28 h-28 rounded-3xl bg-primary/10 border-2 border-primary/40 shadow-2xl shadow-primary/20 flex items-center justify-center mx-auto overflow-hidden shrink-0">
                {resolvePhoto(selectedMember.photoUrl) && !resolvePhoto(selectedMember.photoUrl)?.includes('0000') ? (
                  <img src={resolvePhoto(selectedMember.photoUrl)!} alt={selectedMember.name} className="w-full h-full object-cover" />
                ) : (
                  <Icon icon="mingcute:user-4-fill" className="text-5xl text-primary/60" />
                )}
              </div>

              {/* Name & Role */}
              <div>
                <DialogTitle className="text-2xl font-black text-foreground tracking-tight">
                  {selectedMember.name}
                </DialogTitle>
                <p className={`text-sm font-bold mt-1 ${roleColor(selectedMember.role).split(' ')[0]}`}>
                  {selectedMember.role || 'Anggota Tim'}
                </p>
              </div>

              {/* Period Badge */}
              <div className="pt-1">
                <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-muted/60 border border-border text-xs font-bold text-muted-foreground">
                  <Icon icon="mingcute:time-line" className="text-primary text-sm" />
                  <span>Periode {selectedMember.year || '2023 - Sekarang'}</span>
                </div>
              </div>
            </DialogHeader>

            {/* Bio Quote Box */}
            {selectedMember.bio && (
              <div className="p-3.5 rounded-2xl bg-muted/50 border border-border text-xs text-muted-foreground leading-relaxed text-left italic relative">
                <Icon icon="mingcute:quote-left-fill" className="text-primary/20 text-xl absolute top-2 left-2 pointer-events-none" />
                <p className="relative z-10 pl-4 font-medium">{selectedMember.bio}</p>
              </div>
            )}

            {/* Social & Custom Links Section */}
            <div className="pt-3 border-t border-border space-y-3">
              <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground/60 text-center">
                MEDIA SOSIAL & TAUTAN CUSTOM
              </p>

              <div className="flex flex-col gap-2 max-h-48 overflow-y-auto pr-1">
                {selectedMember.github && (
                  <a
                    href={selectedMember.github}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-3 p-3 rounded-2xl bg-muted/40 hover:bg-muted/80 border border-border transition-all font-bold text-xs text-foreground group"
                  >
                    <div className="w-8 h-8 rounded-xl bg-muted group-hover:bg-primary group-hover:text-primary-foreground flex items-center justify-center transition-colors">
                      <Icon icon="mdi:github" className="text-lg" />
                    </div>
                    <span className="flex-1 text-left truncate">GitHub</span>
                    <Icon icon="mingcute:external-link-line" className="text-sm text-muted-foreground/50 group-hover:text-foreground" />
                  </a>
                )}

                {selectedMember.linkedin && (
                  <a
                    href={selectedMember.linkedin}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-3 p-3 rounded-2xl bg-muted/40 hover:bg-muted/80 border border-border transition-all font-bold text-xs text-foreground group"
                  >
                    <div className="w-8 h-8 rounded-xl bg-muted group-hover:bg-primary group-hover:text-primary-foreground flex items-center justify-center text-sky-400 transition-colors">
                      <Icon icon="entypo-social:linkedin-with-circle" className="text-lg" />
                    </div>
                    <span className="flex-1 text-left truncate">LinkedIn</span>
                    <Icon icon="mingcute:external-link-line" className="text-sm text-muted-foreground/50 group-hover:text-foreground" />
                  </a>
                )}

                {selectedMember.instagram && (
                  <a
                    href={selectedMember.instagram}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-3 p-3 rounded-2xl bg-muted/40 hover:bg-muted/80 border border-border transition-all font-bold text-xs text-foreground group"
                  >
                    <div className="w-8 h-8 rounded-xl bg-muted group-hover:bg-primary group-hover:text-primary-foreground flex items-center justify-center text-rose-400 transition-colors">
                      <Icon icon="mage:instagram-circle" className="text-lg" />
                    </div>
                    <span className="flex-1 text-left truncate">Instagram</span>
                    <Icon icon="mingcute:external-link-line" className="text-sm text-muted-foreground/50 group-hover:text-foreground" />
                  </a>
                )}

                {parseCustomLinks(selectedMember.customLinks).map((link: any, idx: number) => (
                  <a
                    key={idx}
                    href={link.url}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-3 p-3 rounded-2xl bg-muted/40 hover:bg-muted/80 border border-border transition-all font-bold text-xs text-foreground group"
                  >
                    <div className="w-8 h-8 rounded-xl bg-muted group-hover:bg-primary group-hover:text-primary-foreground flex items-center justify-center text-primary transition-colors">
                      <Icon icon={link.icon || 'mingcute:link-2-line'} className="text-lg" />
                    </div>
                    <span className="flex-1 text-left truncate">{link.label || 'Tautan Custom'}</span>
                    <Icon icon="mingcute:external-link-line" className="text-sm text-muted-foreground/50 group-hover:text-foreground" />
                  </a>
                ))}

                {!selectedMember.github &&
                  !selectedMember.linkedin &&
                  !selectedMember.instagram &&
                  parseCustomLinks(selectedMember.customLinks).length === 0 && (
                    <p className="text-xs text-muted-foreground/50 italic text-center py-2 font-medium">
                      Tidak ada tautan kontak tambahan
                    </p>
                  )}
              </div>
            </div>

            <Button
              variant="ghost"
              onClick={() => setSelectedMember(null)}
              className="w-full rounded-2xl font-bold text-xs h-10 opacity-70 hover:opacity-100"
            >
              Tutup
            </Button>
          </DialogContent>
        </Dialog>
      )}

      {/* Public Landing Footer */}
      <LandingFooter />
    </div>
  );
}

// pages/team.vue
<script setup>
definePageMeta({ layout: 'blank' })


const team = ref([])
const loading = ref(true)

const selectedMember = ref(null)
const showDetailModal = ref(false)

const openDetail = (member) => {
  selectedMember.value = member
  showDetailModal.value = true
}

const closeDetail = () => {
  showDetailModal.value = false
  selectedMember.value = null
}

const fetchTeam = async () => {
  try {
    const res = await $fetch('/api/team')
    if (res?.data) {
      team.value = res.data.filter(m => m.isActive)
    }
  } catch (error) {
    console.error('Failed to fetch team:', error)
    // Fallback to static data if needed, or just leave empty
  } finally {
    loading.value = false;
  }
}

onMounted(fetchTeam)

const groupedTeam = computed(() => {
  const pembimbing = []
  const pengembang = []
  
  team.value.forEach(m => {
    const isPembimbing = m.role?.toLowerCase().includes('pembimbing')
    if (isPembimbing) {
      pembimbing.push(m)
    } else {
      pengembang.push(m)
    }
  })

  // Sort each group by 'order'
  pembimbing.sort((a, b) => (a.order || 0) - (b.order || 0))
  pengembang.sort((a, b) => (a.order || 0) - (b.order || 0))

  const result = []
  if (pembimbing.length > 0) {
    result.push({
      title: 'Pembimbing',
      icon: 'mingcute:school-fill',
      members: pembimbing
    })
  }
  if (pengembang.length > 0) {
    result.push({
      title: 'Tim Pengembang',
      icon: 'mingcute:code-fill',
      members: pengembang
    })
  }
  return result
})

const resolvePhoto = (url) => {
  if (!url) return null;
  if (url.startsWith('http')) return url;
  if (url.startsWith('/uploads/team/')) {
    return `/api${url}`;
  }
  return url;
};

const getSocmed = (m) => {
  const socmed = []
  if (m.instagram) socmed.push({ name: 'Instagram', link: m.instagram })
  if (m.linkedin) socmed.push({ name: 'LinkedIn', link: m.linkedin })
  if (m.github) socmed.push({ name: 'github', link: m.github })
  return socmed
}

const roleColor = (role) => {
  if (!role) return 'text-secondary'
  if (role.includes('Backend')) return 'text-blue-400'
  if (role.includes('Frontend')) return 'text-green-400'
  if (role.includes('Hardware') || role.includes('Electrical') || role.includes('Mechanical')) return 'text-orange-400'
  if (role.includes('Pembimbing')) return 'text-primary'
  return 'text-secondary'
}

useSeoMeta({
  title: 'Team | GASKAN',
  ogTitle: 'Team | GASKAN',
  description: 'Tim Pengembang Gerbang Akses Pintar dan Kehadiran',
  image: '/banner.webp',
  url: 'https://gaskan.smtijogja.sch.id/team',
  ogUrl: 'https://gaskan.smtijogja.sch.id/team',
  ogDescription: 'Tim Pengembang Gerbang Akses Pintar dan Kehadiran',
  ogImage: '/banner.webp',
  ogType: 'website',
  ogSiteName: 'GASKAN',
  ogLocale: 'id_ID',
  twitterCard: 'summary_large_image',
  twitterTitle: 'Team | GASKAN',
  twitterDescription: 'Tim Pengembang Gerbang Akses Pintar dan Kehadiran',
  twitterImage: '/banner.webp',
  twitterUrl: 'https://gaskan.smtijogja.sch.id/team',
})
</script>

<template>
  <div class="min-h-screen py-24 px-4">
    <div class="max-w-5xl mx-auto">
      <!-- Header -->
      <div class="text-center mb-16 space-y-3">
        <div class="inline-block bg-primary/10 text-primary text-sm font-semibold px-4 py-1.5 rounded-full border border-primary/20 mb-2">
          Tim GASKAN
        </div>
        <h1 class="text-3xl md:text-4xl font-bold">
          Orang-orang di Balik <span class="text-primary">GASKAN</span>
        </h1>
        <p class="opacity-50 max-w-md mx-auto text-sm leading-relaxed">
          Tim multidisiplin yang membangun dan menjaga sistem kehadiran digital SMTI Jogja.
        </p>
      </div>


      <!-- Loading State -->
      <div v-if="loading" class="flex justify-center py-20">
        <span class="loading loading-spinner loading-lg text-primary opacity-40"></span>
      </div>

      <!-- Grouped Team Sections (by Role Category) -->
      <div v-else class="space-y-16 py-4">
        <div
          v-for="group in groupedTeam"
          :key="group.title"
          class="space-y-6"
        >
          <!-- Section Header -->
          <div class="border-b border-base-200/80 pb-4 text-left">
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
                <Icon :name="group.icon" size="20" />
              </div>
              <div>
                <h2 class="text-2xl font-black tracking-tight text-base-content">
                  {{ group.title }}
                </h2>
                <p class="text-xs opacity-50 mt-0.5">
                  {{ group.title === 'Pembimbing' ? 'Pembimbing dan penanggung jawab proyek GASKAN.' : 'Anggota tim pengembang dan pembuat sistem GASKAN.' }}
                </p>
              </div>
              <span class="badge badge-primary badge-outline font-semibold px-2 py-3 text-xs ml-auto">
                {{ group.members.length }} Orang
              </span>
            </div>
          </div>

          <!-- Team grid for this category -->
          <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
            <div
              v-for="t in group.members"
              :key="t.id"
              @click="openDetail(t)"
              class="group bg-base-200 border border-base-300 hover:border-primary/40 rounded-2xl p-5 flex flex-col gap-3 transition-all duration-300 hover:shadow-xl hover:-translate-y-1 cursor-pointer relative"
            >
              <!-- Avatar + Period Badge -->
              <div class="flex items-start justify-between gap-2">
                <div class="w-14 h-14 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center overflow-hidden shrink-0">
                  <img v-if="t.photoUrl && !t.photoUrl.includes('0000')" :src="resolvePhoto(t.photoUrl)" :alt="t.name" class="w-full h-full object-cover" />
                  <Icon v-else name="mingcute:user-4-fill" class="text-2xl text-primary/60" />
                </div>
                <span v-if="t.year" class="badge badge-sm bg-base-300/60 border border-base-300/60 text-[9px] font-black py-2 rounded-lg text-base-content/60">
                  {{ t.year }}
                </span>
              </div>

              <!-- Info -->
              <div class="flex-1 text-left">
                <h3 class="font-bold text-sm leading-tight text-base-content">{{ t.name }}</h3>
                <p class="text-xs mt-1 font-medium" :class="roleColor(t.role)">{{ t.role }}</p>
              </div>

              <!-- Social links -->
              <div class="flex gap-1.5">
                <a
                  v-for="s in getSocmed(t)"
                  :key="s.name"
                  :href="s.link"
                  target="_blank"
                  @click.stop
                  class="w-7 h-7 rounded-lg bg-base-300 hover:bg-primary hover:text-dark flex items-center justify-center transition-colors duration-200"
                  :aria-label="s.name"
                >
                  <Icon v-if="s.name === 'Instagram'" name="mage:instagram-circle" class="text-sm text-base-content/60 group-hover:text-primary-content" />
                  <Icon v-else-if="s.name === 'LinkedIn'" name="entypo-social:linkedin-with-circle" class="text-sm text-base-content/60 group-hover:text-primary-content" />
                  <Icon v-else-if="s.name === 'github'" name="mdi:github" class="text-sm text-base-content/60 group-hover:text-primary-content" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Member Detail Modal -->
    <dialog :class="['modal modal-bottom sm:modal-middle', { 'modal-open': showDetailModal }]">
      <div v-if="selectedMember" class="modal-box bg-base-100 border border-base-300 rounded-t-[2.5rem] sm:rounded-[2.5rem] p-6 sm:p-8 max-w-md relative overflow-hidden">
        <!-- Close Button X -->
        <button
          @click="closeDetail"
          class="btn btn-sm btn-circle btn-ghost absolute right-4 top-4 z-10 text-base-content/60 hover:text-base-content"
        >
          <Icon name="mingcute:close-line" class="text-xl" />
        </button>

        <!-- Header Decorative Background -->
        <div class="absolute top-0 left-0 right-0 h-28 bg-gradient-to-b from-primary/15 to-transparent pointer-events-none" />

        <!-- Member Profile Content -->
        <div class="relative z-10 text-center space-y-4 pt-2">
          <!-- Large Avatar Frame -->
          <div class="w-28 h-28 rounded-3xl bg-primary/10 border-2 border-primary/30 flex items-center justify-center mx-auto overflow-hidden shadow-2xl shadow-primary/20">
            <img
              v-if="selectedMember.photoUrl && !selectedMember.photoUrl.includes('0000')"
              :src="resolvePhoto(selectedMember.photoUrl)"
              :alt="selectedMember.name"
              class="w-full h-full object-cover"
            />
            <Icon v-else name="mingcute:user-4-fill" class="text-5xl text-primary/60" />
          </div>

          <!-- Name & Role -->
          <div>
            <h3 class="text-2xl font-black text-base-content tracking-tight">{{ selectedMember.name }}</h3>
            <p class="text-sm font-bold mt-1" :class="roleColor(selectedMember.role)">{{ selectedMember.role }}</p>
          </div>

          <!-- Period Badge -->
          <div v-if="selectedMember.year" class="inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-base-200 border border-base-300 text-xs font-bold opacity-75">
            <Icon name="mingcute:time-line" class="text-primary text-sm" />
            <span>Periode {{ selectedMember.year }}</span>
          </div>

          <!-- Email Info if available -->
          <div v-if="selectedMember.email" class="pt-1">
            <a
              :href="`mailto:${selectedMember.email}`"
              class="inline-flex items-center gap-2 text-xs font-bold text-primary hover:underline bg-primary/10 px-3.5 py-2 rounded-xl border border-primary/20"
            >
              <Icon name="mingcute:mail-line" class="text-sm" />
              <span>{{ selectedMember.email }}</span>
            </a>
          </div>

          <!-- Social Links Section -->
          <div class="pt-4 border-t border-base-200/80 space-y-3">
            <p class="text-[10px] font-black uppercase tracking-widest text-base-content/40">Media Sosial & Tautan</p>
            <div class="flex flex-col gap-2">
              <a
                v-if="selectedMember.github"
                :href="selectedMember.github"
                target="_blank"
                class="flex items-center gap-3 p-3 rounded-2xl bg-base-200 hover:bg-base-300 border border-base-300 transition-all font-semibold text-xs text-base-content group"
              >
                <div class="w-8 h-8 rounded-xl bg-base-300 group-hover:bg-primary group-hover:text-dark flex items-center justify-center transition-colors">
                  <Icon name="mdi:github" class="text-lg" />
                </div>
                <span class="flex-1 text-left truncate">GitHub</span>
                <Icon name="mingcute:external-link-line" class="text-sm opacity-40 group-hover:opacity-100" />
              </a>

              <a
                v-if="selectedMember.linkedin"
                :href="selectedMember.linkedin"
                target="_blank"
                class="flex items-center gap-3 p-3 rounded-2xl bg-base-200 hover:bg-base-300 border border-base-300 transition-all font-semibold text-xs text-base-content group"
              >
                <div class="w-8 h-8 rounded-xl bg-base-300 group-hover:bg-primary group-hover:text-dark flex items-center justify-center text-blue-400 transition-colors">
                  <Icon name="entypo-social:linkedin-with-circle" class="text-lg" />
                </div>
                <span class="flex-1 text-left truncate">LinkedIn</span>
                <Icon name="mingcute:external-link-line" class="text-sm opacity-40 group-hover:opacity-100" />
              </a>

              <a
                v-if="selectedMember.instagram"
                :href="selectedMember.instagram"
                target="_blank"
                class="flex items-center gap-3 p-3 rounded-2xl bg-base-200 hover:bg-base-300 border border-base-300 transition-all font-semibold text-xs text-base-content group"
              >
                <div class="w-8 h-8 rounded-xl bg-base-300 group-hover:bg-primary group-hover:text-dark flex items-center justify-center text-pink-400 transition-colors">
                  <Icon name="mage:instagram-circle" class="text-lg" />
                </div>
                <span class="flex-1 text-left truncate">Instagram</span>
                <Icon name="mingcute:external-link-line" class="text-sm opacity-40 group-hover:opacity-100" />
              </a>

              <div v-if="!selectedMember.github && !selectedMember.linkedin && !selectedMember.instagram && !selectedMember.email" class="text-xs opacity-40 italic py-2">
                Tidak ada tautan kontak tambahan
              </div>
            </div>
          </div>

          <!-- Close Action -->
          <div class="pt-2">
            <button @click="closeDetail" class="btn btn-ghost w-full rounded-2xl text-xs font-bold opacity-60 hover:opacity-100">
              Tutup
            </button>
          </div>
        </div>
      </div>
    </dialog>
  </div>
</template>
