// gaskan-next/app/(dashboard)/reshuffle/page.tsx
'use client';

import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import Link from 'next/link';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import { toast } from 'sonner';
import { Icon } from '@iconify/react';
import api from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { CustomSelect } from '@/components/shared/CustomSelect';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';

export default function ReshufflePage() {
  const [activeTab, setActiveTab] = useState<'website' | 'excel'>('website');
  const [classes, setClasses] = useState<any[]>([]);
  const [sourceClassId, setSourceClassId] = useState('');
  const [targetClassId, setTargetClassId] = useState('');
  const [targetRombel, setTargetRombel] = useState('');
  const [students, setStudents] = useState<any[]>([]);
  const [selectedStudentIds, setSelectedStudentIds] = useState<string[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isProcessing, setIsProcessing] = useState(false);

  // Excel State
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [excelFile, setExcelFile] = useState<File | null>(null);
  const [excelRows, setExcelRows] = useState<any[]>([]);
  const [excelTargetClassId, setExcelTargetClassId] = useState('');
  const [isDragging, setIsDragging] = useState(false);

  // Modals State
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [showProgressModal, setShowProgressModal] = useState(false);
  const [showSummaryModal, setShowSummaryModal] = useState(false);
  const [summaryList, setSummaryList] = useState<any[]>([]);
  const [progressPercent, setProgressPercent] = useState(0);

  const fetchClasses = useCallback(async () => {
    setIsLoading(true);
    try {
      const res = await api.get('/classes').catch(() => api.get('/kelas'));
      const d = res?.data?.data || res?.data || [];
      setClasses(d);
      if (d.length > 0 && !sourceClassId) {
        setSourceClassId(d[0].id);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  }, [sourceClassId]);

  useEffect(() => {
    fetchClasses();
  }, [fetchClasses]);

  const fetchSourceStudents = useCallback(async (classId: string) => {
    if (!classId) {
      setStudents([]);
      return;
    }
    setIsLoading(true);
    try {
      const res = await api.get(`/students?classId=${classId}&limit=200`).catch(() => api.get(`/siswa?kelasId=${classId}`));
      setStudents(res?.data?.data || res?.data || []);
      setSelectedStudentIds([]);
    } catch (e) {
      toast.error('Gagal mengambil data siswa kelas asal');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (sourceClassId) fetchSourceStudents(sourceClassId);
  }, [sourceClassId, fetchSourceStudents]);

  const filteredStudents = useMemo(() => {
    if (!searchQuery.trim()) return students;
    const q = searchQuery.toLowerCase();
    return students.filter(
      (s) =>
        (s.name || s.Nama || '').toLowerCase().includes(q) ||
        (s.nis || s.NIS || '').includes(q) ||
        (s.nisn || s.NISN || '').includes(q) ||
        (s.rombel || '').toLowerCase().includes(q)
    );
  }, [students, searchQuery]);

  const isAllSelected = useMemo(() => {
    return filteredStudents.length > 0 && selectedStudentIds.length === filteredStudents.length;
  }, [filteredStudents, selectedStudentIds]);

  const toggleSelectAll = () => {
    if (isAllSelected) {
      setSelectedStudentIds([]);
    } else {
      setSelectedStudentIds(filteredStudents.map((s) => String(s.id)));
    }
  };

  const toggleSelectStudent = (id: string) => {
    setSelectedStudentIds((prev) =>
      prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id]
    );
  };

  // Download Excel Reshuffle Template
  const downloadTemplate = async () => {
    try {
      const workbook = new ExcelJS.Workbook();
      const ws = workbook.addWorksheet('Template_Reshuffle');
      ws.columns = [
        { header: 'NIS*', key: 'nis', width: 15 },
        { header: 'Nama Siswa', key: 'name', width: 25 },
        { header: 'Nama Kelas Tujuan*', key: 'targetClass', width: 20 },
        { header: 'Nomor Rombel (Opsional)', key: 'rombel', width: 20 },
      ];
      ws.addRow({ nis: '25101001', name: 'Ahmad Dahlan', targetClass: 'XI AK 1', rombel: '1' });
      ws.addRow({ nis: '25101002', name: 'Siti Sarah', targetClass: 'XI AK 1', rombel: '1' });

      const buffer = await workbook.xlsx.writeBuffer();
      const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      saveAs(blob, 'Template_Reshuffle_GASKAN.xlsx');
      toast.success('Template Excel Reshuffle berhasil diunduh');
    } catch (e) {
      toast.error('Gagal mengunduh template Excel');
    }
  };

  // Parse Excel File
  const handleExcelParse = async (file: File) => {
    setExcelFile(file);
    try {
      const workbook = new ExcelJS.Workbook();
      const arrayBuffer = await file.arrayBuffer();
      await workbook.xlsx.load(arrayBuffer);
      const ws = workbook.worksheets[0];
      if (!ws || ws.rowCount < 2) {
        toast.error('File Excel kosong atau hanya header');
        return;
      }

      const rows: any[] = [];
      ws.eachRow((row, rowNumber) => {
        if (rowNumber === 1) return;
        const nis = String(row.getCell(1).value || '').trim();
        const name = String(row.getCell(2).value || '').trim();
        const targetClass = String(row.getCell(3).value || '').trim();
        const rombel = String(row.getCell(4).value || '').trim();

        if (nis || name) {
          rows.push({ row: rowNumber, nis, name, targetClass, rombel, status: 'SIAP' });
        }
      });

      setExcelRows(rows);
      toast.success(`Berhasil membaca ${rows.length} data siswa dari Excel`);
    } catch (e) {
      toast.error('Gagal membaca file Excel. Pastikan format .xlsx valid.');
    }
  };

  const openWebConfirm = () => {
    if (selectedStudentIds.length === 0) {
      toast.error('Pilih minimal 1 siswa yang akan dipindahkan');
      return;
    }
    if (!targetClassId) {
      toast.error('Harap pilih Kelas Tujuan terlebih dahulu');
      return;
    }
    setShowConfirmModal(true);
  };

  const openExcelConfirm = () => {
    if (excelRows.length === 0) {
      toast.error('Belum ada data Excel yang diunggah');
      return;
    }
    if (!excelTargetClassId) {
      toast.error('Harap pilih Kelas Tujuan terlebih dahulu');
      return;
    }
    setShowConfirmModal(true);
  };

  const handleExecuteReshuffle = async () => {
    setIsProcessing(true);
    setShowConfirmModal(false);
    setShowProgressModal(true);
    setProgressPercent(20);

    try {
      if (activeTab === 'website') {
        setProgressPercent(60);
        await api.post('/classes/reshuffle', {
          sourceClassId,
          targetClassId,
          studentIds: selectedStudentIds,
          rombel: targetRombel,
        });

        const targetObj = classes.find((c) => c.id === targetClassId);
        const sourceObj = classes.find((c) => c.id === sourceClassId);
        const summary = selectedStudentIds.map((id) => {
          const st = students.find((s) => String(s.id) === id);
          return {
            nis: st?.nis || st?.NIS || '-',
            name: st?.name || st?.Nama || '-',
            fromClass: sourceObj?.className || 'Kelas Asal',
            toClass: targetObj?.className || 'Kelas Tujuan',
            rombel: targetRombel || '-',
          };
        });

        setProgressPercent(100);
        setSummaryList(summary);
        setSelectedStudentIds([]);
        await fetchSourceStudents(sourceClassId);
      } else {
        setProgressPercent(60);
        await api.post('/classes/reshuffle/batch', {
          targetClassId: excelTargetClassId,
          rows: excelRows,
        });

        const targetObj = classes.find((c) => c.id === excelTargetClassId);
        const summary = excelRows.map((r) => ({
          nis: r.nis,
          name: r.name || 'Siswa',
          fromClass: 'Kelas Asal',
          toClass: targetObj?.className || r.targetClass || 'Kelas Tujuan',
          rombel: r.rombel || '-',
        }));

        setProgressPercent(100);
        setSummaryList(summary);
        setExcelRows([]);
        setExcelFile(null);
      }

      setTimeout(() => {
        setShowProgressModal(false);
        setShowSummaryModal(true);
      }, 400);
    } catch (e: any) {
      setShowProgressModal(false);
      toast.error(e?.response?.data?.message || 'Gagal memproses reshuffle siswa');
    } finally {
      setIsProcessing(false);
    }
  };

  const selectedTargetClassName = useMemo(() => {
    const targetId = activeTab === 'website' ? targetClassId : excelTargetClassId;
    const c = classes.find((item) => item.id === targetId);
    return c?.className || c?.nama_kelas || 'Kelas Tujuan';
  }, [classes, targetClassId, excelTargetClassId, activeTab]);

  return (
    <div className="space-y-6 pb-20 animate-in fade-in duration-500 max-w-7xl mx-auto">
      {/* Top Header Card matching Nuxt 1-to-1 */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-card p-6 rounded-3xl border border-border shadow-sm">
        <div>
          <div className="flex items-center gap-2 text-xs font-bold text-muted-foreground/60 mb-1">
            <Link href="/kelas" className="hover:text-primary transition-colors">
              Manajemen Kelas
            </Link>
            <span>/</span>
            <span className="text-primary font-black">Reshuffle & Acak Kelas</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-foreground tracking-tight">
            Reshuffle & Penataan Kelas
          </h1>
          <p className="text-xs text-muted-foreground font-semibold mt-1">
            Pindahkan siswa antar kelas dan atur rombel (rombongan belajar) untuk persiapan tahun ajaran baru.
          </p>
        </div>

        {/* Tab Selection Toggle matching Nuxt */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center p-1.5 bg-muted/40 rounded-2xl border border-border shrink-0 gap-1.5 w-full sm:w-auto">
          <div className="grid grid-cols-2 gap-1.5 sm:flex sm:items-center">
            <button
              onClick={() => setActiveTab('website')}
              className={`px-3 sm:px-4 py-2.5 sm:py-2 rounded-xl text-xs font-black transition-all flex items-center justify-center gap-2 ${
                activeTab === 'website'
                  ? 'bg-primary text-primary-foreground shadow-lg shadow-primary/20'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              <Icon icon="mingcute:cursor-hand-line" className="text-base" />
              <span>Pilih Langsung</span>
            </button>
            <button
              onClick={() => setActiveTab('excel')}
              className={`px-3 sm:px-4 py-2.5 sm:py-2 rounded-xl text-xs font-black transition-all flex items-center justify-center gap-2 ${
                activeTab === 'excel'
                  ? 'bg-amber-500 text-slate-950 shadow-lg shadow-amber-500/20'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              <Icon icon="mingcute:file-import-fill" className="text-base" />
              <span>Import Excel</span>
            </button>
          </div>

          <Link
            href="/reshuffle/history"
            className="px-3 sm:px-4 py-2.5 sm:py-2 rounded-xl text-xs font-black transition-all flex items-center justify-center gap-2 text-sky-400 hover:text-white hover:bg-sky-500/20 border border-sky-500/20 w-full sm:w-auto shrink-0"
          >
            <Icon icon="mingcute:history-line" className="text-base" />
            <span>Riwayat Audit Log</span>
          </Link>
        </div>
      </div>

      {/* TAB 1: WEBSITE RESHUFFLE */}
      {activeTab === 'website' && (
        <div className="space-y-6">
          {/* Control Panel matching Nuxt */}
          <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
            {/* Source Class Select */}
            <div className="md:col-span-4 bg-card p-5 rounded-3xl border border-border shadow-sm space-y-2">
              <label className="text-xs font-black uppercase tracking-wider text-muted-foreground/60 flex items-center gap-1.5">
                <Icon icon="mingcute:logout-box-line" className="text-amber-500 text-base" />
                1. Pilih Kelas Asal
              </label>
              <CustomSelect
                options={classes.map((c) => ({
                  value: c.id,
                  label: `${c.className || c.nama_kelas} (${c._count?.students || c.studentCount || 0} siswa)`,
                }))}
                value={sourceClassId}
                onChange={setSourceClassId}
                placeholder="-- Pilih Kelas Asal --"
              />
            </div>

            {/* Target Class & Rombel */}
            <div className="md:col-span-8 bg-card p-5 rounded-3xl border border-border shadow-sm grid grid-cols-1 sm:grid-cols-12 gap-3 items-center">
              <div className="sm:col-span-6 space-y-2">
                <label className="text-xs font-black uppercase tracking-wider text-muted-foreground/60 flex items-center gap-1.5">
                  <Icon icon="mingcute:login-box-line" className="text-emerald-500 text-base" />
                  2. Pilih Kelas Tujuan
                </label>
                <CustomSelect
                  options={classes.map((c) => ({ value: c.id, label: c.className || c.nama_kelas }))}
                  value={targetClassId}
                  onChange={setTargetClassId}
                  placeholder="-- Pilih Kelas Tujuan --"
                />
              </div>

              <div className="sm:col-span-6 space-y-2">
                <label className="text-xs font-black uppercase tracking-wider text-muted-foreground/60 flex items-center gap-1.5">
                  <Icon icon="mingcute:group-fill" className="text-sky-500 text-base" />
                  Rombel Baru (Opsional)
                </label>
                <Input
                  value={targetRombel}
                  onChange={(e) => setTargetRombel(e.target.value)}
                  placeholder="Contoh: Rombel A / 1"
                  className="h-11 rounded-2xl bg-muted/30 font-bold text-xs"
                />
              </div>
            </div>
          </div>

          {/* Student Selector Table */}
          <div className="bg-card border border-border rounded-3xl overflow-hidden shadow-sm">
            <div className="p-4 bg-muted/20 border-b border-border flex flex-col sm:flex-row items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <input
                  type="checkbox"
                  checked={isAllSelected}
                  onChange={toggleSelectAll}
                  className="w-4 h-4 rounded border-border text-primary cursor-pointer"
                />
                <span className="text-xs font-black uppercase tracking-wider text-foreground">
                  Pilih Siswa ({selectedStudentIds.length} / {filteredStudents.length} Terpilih)
                </span>
              </div>

              <div className="w-full sm:w-64">
                <Input
                  type="text"
                  placeholder="Cari Nama / NIS / Rombel..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="h-9 rounded-xl text-xs bg-background"
                />
              </div>
            </div>

            <div className="max-h-96 overflow-y-auto divide-y divide-border">
              {isLoading ? (
                <div className="p-12 text-center text-xs font-bold text-muted-foreground flex items-center justify-center gap-2">
                  <Icon icon="mingcute:loading-fill" className="animate-spin text-lg" /> Memuat daftar siswa...
                </div>
              ) : filteredStudents.length === 0 ? (
                <div className="p-12 text-center text-xs font-bold text-muted-foreground/40 italic">
                  Tidak ada siswa yang ditemukan di kelas asal
                </div>
              ) : (
                filteredStudents.map((std) => {
                  const sId = String(std.id);
                  const isChecked = selectedStudentIds.includes(sId);
                  return (
                    <div
                      key={sId}
                      onClick={() => toggleSelectStudent(sId)}
                      className={`px-6 py-3.5 flex items-center justify-between text-xs font-bold cursor-pointer transition-colors ${
                        isChecked ? 'bg-primary/10' : 'hover:bg-muted/30'
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <input
                          type="checkbox"
                          checked={isChecked}
                          onChange={() => {}}
                          className="w-4 h-4 rounded border-border text-primary"
                        />
                        <span className="text-foreground text-sm font-black">{std.name || std.Nama}</span>
                      </div>
                      <div className="flex items-center gap-4 text-muted-foreground">
                        <span className="font-mono">NIS: {std.nis || std.NIS}</span>
                        {std.rombel && <Badge variant="outline" className="text-[10px] font-bold">{std.rombel}</Badge>}
                      </div>
                    </div>
                  );
                })
              )}
            </div>

            <div className="p-6 border-t border-border bg-muted/10 flex justify-end">
              <Button
                disabled={selectedStudentIds.length === 0 || !targetClassId}
                onClick={openWebConfirm}
                className="rounded-2xl font-bold px-8 bg-primary text-primary-foreground shadow-lg shadow-primary/20 h-12"
              >
                <Icon icon="mingcute:transfer-4-line" className="text-base mr-2" />
                <span>Pindahkan {selectedStudentIds.length} Siswa ke {selectedTargetClassName}</span>
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: EXCEL RESHUFFLE */}
      {activeTab === 'excel' && (
        <div className="space-y-6">
          <div className="bg-card border border-border rounded-3xl p-8 sm:p-12 text-center space-y-6 shadow-sm">
            <div
              onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={(e) => {
                e.preventDefault();
                setIsDragging(false);
                if (e.dataTransfer.files[0]) handleExcelParse(e.dataTransfer.files[0]);
              }}
              onClick={() => fileInputRef.current?.click()}
              className={`border-2 border-dashed rounded-3xl p-10 flex flex-col items-center justify-center cursor-pointer transition-all ${
                isDragging ? 'border-amber-500 bg-amber-500/10' : 'border-border hover:border-amber-500/50 bg-muted/20'
              }`}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept=".xlsx, .xls"
                onChange={(e) => e.target.files && handleExcelParse(e.target.files[0])}
                className="hidden"
              />
              <div className="w-16 h-16 rounded-2xl bg-amber-500/10 text-amber-500 flex items-center justify-center mb-4">
                <Icon icon="mingcute:file-import-fill" className="text-3xl" />
              </div>
              <h3 className="text-lg font-black text-foreground mb-1">
                {excelFile ? `File: ${excelFile.name}` : 'Pilih atau Tarik File Excel Reshuffle'}
              </h3>
              <p className="text-xs text-muted-foreground font-semibold max-w-sm">
                Unggah file .xlsx berisi NIS siswa dan Nama Kelas Tujuan untuk memindahkan kelas secara otomatis.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <Button onClick={downloadTemplate} variant="outline" className="rounded-2xl gap-2 font-bold text-xs h-11 px-5 border-border">
                <Icon icon="mingcute:download-2-line" className="text-base text-amber-500" />
                Unduh Template Excel Reshuffle Resmi
              </Button>
            </div>
          </div>

          {/* Select Excel Target Class */}
          <div className="bg-card border border-border rounded-3xl p-5 space-y-2 shadow-sm">
            <label className="text-xs font-black uppercase tracking-wider text-muted-foreground/60">
              Pilih Kelas Tujuan untuk Import Excel
            </label>
            <CustomSelect
              options={classes.map((c) => ({ value: c.id, label: c.className || c.nama_kelas }))}
              value={excelTargetClassId}
              onChange={setExcelTargetClassId}
              placeholder="-- Pilih Kelas Tujuan --"
            />
          </div>

          {/* Parsed Excel Rows */}
          {excelRows.length > 0 && (
            <div className="bg-card border border-border rounded-3xl overflow-hidden shadow-sm">
              <div className="p-4 bg-muted/20 border-b border-border flex justify-between items-center">
                <span className="text-xs font-black text-amber-500 uppercase tracking-wider">
                  Pratinjau ({excelRows.length} Data Siswa dari Excel)
                </span>
              </div>
              <div className="max-h-80 overflow-y-auto divide-y divide-border">
                {excelRows.map((r, i) => (
                  <div key={i} className="grid grid-cols-12 px-6 py-3 items-center text-xs font-bold">
                    <div className="col-span-1 text-muted-foreground font-mono">#{r.row}</div>
                    <div className="col-span-3 font-mono text-foreground">{r.nis}</div>
                    <div className="col-span-4 text-foreground">{r.name || 'Siswa'}</div>
                    <div className="col-span-4 text-amber-500 text-right font-black">Ke: {selectedTargetClassName}</div>
                  </div>
                ))}
              </div>
              <div className="p-6 border-t border-border bg-muted/10 flex justify-end">
                <Button
                  disabled={!excelTargetClassId}
                  onClick={openExcelConfirm}
                  className="rounded-2xl font-bold px-8 bg-amber-500 text-slate-950 hover:bg-amber-400 shadow-lg shadow-amber-500/20 h-12"
                >
                  <Icon icon="mingcute:file-import-fill" className="text-base mr-2" />
                  <span>Jalankan Reshuffle Excel Sekarang</span>
                </Button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ═══ CONFIRMATION MODAL ═══ */}
      <Dialog open={showConfirmModal} onOpenChange={setShowConfirmModal}>
        <DialogContent className="sm:max-w-md p-6 text-center">
          <div className="w-16 h-16 bg-primary/10 text-primary rounded-2xl flex items-center justify-center mx-auto mb-3">
            <Icon icon="mingcute:transfer-4-line" className="text-3xl" />
          </div>
          <DialogHeader className="p-0 border-none bg-transparent">
            <DialogTitle className="text-2xl font-black text-foreground text-center">
              Konfirmasi Reshuffle Kelas
            </DialogTitle>
          </DialogHeader>
          <p className="text-xs text-muted-foreground font-semibold leading-relaxed my-3">
            Apakah Anda yakin ingin memindahkan{' '}
            <span className="font-bold text-foreground">
              {activeTab === 'website' ? selectedStudentIds.length : excelRows.length} siswa
            </span>{' '}
            ke kelas <strong className="text-primary">"{selectedTargetClassName}"</strong>?
          </p>
          <DialogFooter className="p-0 border-none bg-transparent gap-3 flex-row justify-center mt-4">
            <Button variant="ghost" className="rounded-2xl flex-1 font-bold" onClick={() => setShowConfirmModal(false)}>
              Batal
            </Button>
            <Button className="rounded-2xl flex-1 font-bold bg-primary text-primary-foreground shadow-lg shadow-primary/20" disabled={isProcessing} onClick={handleExecuteReshuffle}>
              {isProcessing ? 'Memproses...' : 'Ya, Pindahkan Siswa'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ═══ PROGRESS MODAL ═══ */}
      <Dialog open={showProgressModal} onOpenChange={() => {}}>
        <DialogContent className="sm:max-w-sm p-6 text-center">
          <Icon icon="mingcute:loading-fill" className="text-4xl text-primary animate-spin mx-auto mb-3" />
          <DialogHeader className="p-0 border-none bg-transparent">
            <DialogTitle className="text-xl font-black text-foreground text-center">
              Memproses Reshuffle Siswa...
            </DialogTitle>
          </DialogHeader>
          <div className="w-full bg-muted rounded-full h-3 overflow-hidden my-4">
            <div className="bg-primary h-full transition-all duration-300" style={{ width: `${progressPercent}%` }} />
          </div>
          <p className="text-xs font-bold text-primary">{progressPercent}% Selesai</p>
        </DialogContent>
      </Dialog>

      {/* ═══ SUMMARY MODAL ═══ */}
      <Dialog open={showSummaryModal} onOpenChange={setShowSummaryModal}>
        <DialogContent className="sm:max-w-lg max-h-[85vh] flex flex-col p-0 overflow-hidden border-border bg-card rounded-3xl shadow-2xl">
          <DialogHeader className="p-6 pb-4 border-b border-border shrink-0 bg-card text-center">
            <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 text-emerald-500 flex items-center justify-center mx-auto mb-2">
              <Icon icon="mingcute:check-circle-fill" className="text-2xl" />
            </div>
            <DialogTitle className="text-xl font-black text-foreground text-center">
              Reshuffle Berhasil! {summaryList.length} Siswa Dipindahkan
            </DialogTitle>
          </DialogHeader>

          <div className="flex-1 overflow-y-auto p-6 space-y-2 text-xs font-semibold">
            {summaryList.map((item, idx) => (
              <div key={idx} className="p-3 bg-muted/30 border border-border rounded-2xl flex items-center justify-between">
                <div>
                  <p className="font-black text-foreground">{item.name}</p>
                  <p className="text-[10px] text-muted-foreground font-mono">NIS: {item.nis}</p>
                </div>
                <div className="text-right">
                  <span className="text-[10px] text-muted-foreground">{item.fromClass}</span>
                  <span className="text-primary font-bold"> &rarr; {item.toClass}</span>
                </div>
              </div>
            ))}
          </div>

          <DialogFooter className="p-6 pt-4 border-t border-border shrink-0 bg-card">
            <Button className="w-full rounded-2xl font-bold bg-primary text-primary-foreground" onClick={() => setShowSummaryModal(false)}>
              Tutup Ringkasan
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// pages/kelas/reshuffle.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import { useNuxtApp } from '#app';
import * as XLSX from 'xlsx';

definePageMeta({
  middleware: ['auth']
});

useHead({
  title: 'Reshuffle & Acak Kelas | GASKAN'
});

const { $toast } = useNuxtApp();

const activeTab = ref('website'); // 'website' | 'excel'
const loading = ref(false);
const submitting = ref(false);

const classes = ref([]);
const sourceClassId = ref('');
const targetClassId = ref('');
const targetRombel = ref('');

const students = ref([]);
const selectedStudentIds = ref([]);
const searchQuery = ref('');

// Excel upload state
const excelFile = ref(null);
const excelRows = ref([]);
const excelParsing = ref(false);
const excelTemplateClassId = ref('');

// Fetch all classes & initial students
const fetchData = async () => {
  loading.value = true;
  try {
    const classRes = await $fetch('/api/classes').catch(() => null);
    classes.value = classRes?.data || classRes || [];
    
    if (classes.value.length > 0 && !sourceClassId.value) {
      sourceClassId.value = classes.value[0].id;
    }
    await fetchSourceStudents();
  } catch (e) {
    console.error('Error fetching reshuffle data:', e);
  } finally {
    loading.value = false;
  }
};

const fetchSourceStudents = async () => {
  if (!sourceClassId.value) {
    students.value = [];
    return;
  }
  loading.value = true;
  try {
    const res = await $fetch(`/api/students?classId=${sourceClassId.value}&limit=200&status=AKTIF`).catch(() => null);
    students.value = res?.data || [];
    selectedStudentIds.value = [];
  } catch (e) {
    $toast.error('Gagal mengambil data siswa kelas asal');
  } finally {
    loading.value = false;
  }
};

onMounted(fetchData);

// Filtered students by search
const filteredStudents = computed(() => {
  if (!searchQuery.value) return students.value;
  const q = searchQuery.value.toLowerCase();
  return students.value.filter((s) => 
    s.name?.toLowerCase().includes(q) || 
    s.nis?.includes(q) || 
    s.nisn?.includes(q) ||
    s.rombel?.toLowerCase().includes(q)
  );
});

const isAllSelected = computed(() => {
  return filteredStudents.value.length > 0 && selectedStudentIds.value.length === filteredStudents.value.length;
});

const toggleSelectAll = () => {
  if (isAllSelected.value) {
    selectedStudentIds.value = [];
  } else {
    selectedStudentIds.value = filteredStudents.value.map((s) => s.id);
  }
};

const toggleSelectStudent = (id) => {
  if (selectedStudentIds.value.includes(id)) {
    selectedStudentIds.value = selectedStudentIds.value.filter((item) => item !== id);
  } else {
    selectedStudentIds.value.push(id);
  }
};

// Website Reshuffle Submit
const handleWebReshuffle = async () => {
  if (selectedStudentIds.value.length === 0) {
    $toast.error('Pilih minimal 1 siswa yang akan dipindahkan');
    return;
  }
  if (!targetClassId.value) {
    $toast.error('Pilih kelas tujuan terlebih dahulu');
    return;
  }

  const targetClassObj = classes.value.find((c) => c.id === targetClassId.value);
  const targetClassName = targetClassObj?.className || 'Kelas Tujuan';

  if (!confirm(`Konfirmasi: Pindahkan ${selectedStudentIds.value.length} siswa ke kelas "${targetClassName}"${targetRombel.value ? ' (' + targetRombel.value + ')' : ''}?`)) {
    return;
  }

  submitting.value = true;
  try {
    const res = await $fetch('/api/system/reshuffle', {
      method: 'POST',
      body: {
        studentIds: selectedStudentIds.value,
        targetClassId: targetClassId.value,
        rombel: targetRombel.value || null
      }
    });

    $toast.success(res?.message || 'Reshuffle siswa berhasil');
    selectedStudentIds.value = [];
    await fetchSourceStudents();
  } catch (e) {
    $toast.error(e?.data?.message || 'Gagal memproses reshuffle siswa');
  } finally {
    submitting.value = false;
  }
};

// Download Template Excel
const handleDownloadTemplate = () => {
  const url = `/api/system/reshuffle/template${excelTemplateClassId.value ? '?classId=' + excelTemplateClassId.value : ''}`;
  window.open(url, '_blank');
};

// Handle Excel File Upload & Parse via SheetJS
const handleFileUpload = (event) => {
  const file = event.target.files[0];
  if (!file) return;

  excelFile.value = file;
  excelParsing.value = true;
  const reader = new FileReader();

  reader.onload = (e) => {
    try {
      const data = new Uint8Array(e.target.result);
      const workbook = XLSX.read(data, { type: 'array' });
      const firstSheet = workbook.Sheets[workbook.SheetNames[0]];
      const jsonRows = XLSX.utils.sheet_to_json(firstSheet); // Row 1 is header (No, NIS, Nama, Rombel, Kelas Tujuan)

      excelRows.value = jsonRows.filter((row) => {
        const nis = row['NIS'] || row['nis'] || row['ID Siswa'] || row.id || row['NISN'] || row.nisn;
        const name = row['Nama'] || row['nama'] || row['Nama Siswa'] || row.name;
        return Boolean(nis || name);
      });

      if (excelRows.value.length === 0) {
        $toast.error('Tidak ada baris data reshuffle valid yang ditemukan di file Excel ini');
      } else {
        $toast.success(`Berhasil membaca ${excelRows.value.length} baris data dari Excel`);
      }
    } catch (err) {
      console.error('Error parsing excel:', err);
      $toast.error('Gagal membaca file Excel. Pastikan format .xlsx valid.');
    } finally {
      excelParsing.value = false;
    }
  };

  reader.readAsArrayBuffer(file);
};

const excelTargetClassId = ref('');

// Submit Excel Reshuffle
const handleExcelReshuffle = async () => {
  if (!excelTargetClassId.value) {
    $toast.error('Harap pilih Kelas Tujuan terlebih dahulu');
    return;
  }
  if (excelRows.value.length === 0) {
    $toast.error('Belum ada data Excel yang diunggah');
    return;
  }

  const targetClassObj = classes.value.find((c) => c.id === excelTargetClassId.value);
  const targetClassName = targetClassObj?.className || 'Kelas Tujuan';

  if (!confirm(`Konfirmasi: Terapkan ${excelRows.value.length} baris data Excel ke kelas "${targetClassName}"?`)) {
    return;
  }

  submitting.value = true;
  try {
    const res = await $fetch('/api/system/reshuffle/import', {
      method: 'POST',
      body: { 
        targetClassId: excelTargetClassId.value,
        rows: excelRows.value 
      }
    });

    $toast.success(res?.message || 'Proses reshuffle dari Excel selesai');
    excelRows.value = [];
    excelFile.value = null;
    await fetchSourceStudents();
  } catch (e) {
    $toast.error(e?.data?.message || 'Gagal mengimpor reshuffle dari Excel');
  } finally {
    submitting.value = false;
  }
};
</script>

<template>
  <div class="space-y-6 pb-20 animate-in fade-in duration-500">
    
    <!-- Top Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-base-100 p-6 rounded-3xl border border-base-200 shadow-sm">
      <div>
        <div class="flex items-center gap-2 text-xs font-bold text-base-content/40 mb-1">
          <NuxtLink to="/kelas" class="hover:text-primary transition-colors">Manajemen Kelas</NuxtLink>
          <span>/</span>
          <span class="text-primary">Reshuffle & Acak Kelas</span>
        </div>
        <h1 class="text-2xl sm:text-3xl font-black text-base-content tracking-tight">Reshuffle & Penataan Kelas</h1>
        <p class="text-xs text-base-content/60 mt-1">
          Pindahkan siswa antar kelas dan atur rombel (rombongan belajar) untuk persiapan tahun ajaran baru.
        </p>
      </div>

      <!-- Tab Selection Toggle -->
      <div class="flex items-center p-1.5 bg-base-200/60 rounded-2xl border border-base-300/40 shrink-0">
        <button
          @click="activeTab = 'website'"
          :class="['px-4 py-2 rounded-xl text-xs font-black transition-all flex items-center gap-2', activeTab === 'website' ? 'bg-primary text-primary-content shadow-lg shadow-primary/20' : 'text-base-content/60 hover:text-base-content']"
        >
          <Icon name="mingcute:global-line" size="16" />
          Secara Website
        </button>
        <button
          @click="activeTab = 'excel'"
          :class="['px-4 py-2 rounded-xl text-xs font-black transition-all flex items-center gap-2', activeTab === 'excel' ? 'bg-amber-500 text-black shadow-lg shadow-amber-500/20' : 'text-base-content/60 hover:text-base-content']"
        >
          <Icon name="mingcute:file-excel-line" size="16" />
          Upload Excel
        </button>
      </div>
    </div>

    <!-- TAB 1: RESHUFFLE SECARA WEBSITE -->
    <div v-if="activeTab === 'website'" class="space-y-6">
      
      <!-- Control Panel (Source Class -> Target Class & Rombel) -->
      <div class="grid grid-cols-1 md:grid-cols-12 gap-4">
        
        <!-- Source Class Select -->
        <div class="md:col-span-4 bg-base-100 p-5 rounded-3xl border border-base-200 shadow-sm space-y-2">
          <label class="text-xs font-black uppercase tracking-wider text-base-content/50 flex items-center gap-1.5">
            <Icon name="mingcute:logout-box-line" class="text-amber-500" size="16" />
            1. Pilih Kelas Asal
          </label>
          <select 
            v-model="sourceClassId" 
            @change="fetchSourceStudents"
            class="select select-bordered select-sm w-full rounded-2xl font-bold text-xs focus:select-primary"
          >
            <option v-for="c in classes" :key="c.id" :value="c.id">
              {{ c.className }} ({{ c._count?.students || 0 }} siswa)
            </option>
          </select>
        </div>

        <!-- Target Class & Rombel Select -->
        <div class="md:col-span-8 bg-base-100 p-5 rounded-3xl border border-base-200 shadow-sm grid grid-cols-1 sm:grid-cols-12 gap-3 items-center">
          <div class="sm:col-span-6 space-y-1">
            <label class="text-xs font-black uppercase tracking-wider text-base-content/50 flex items-center gap-1.5">
              <Icon name="mingcute:login-box-line" class="text-emerald-500" size="16" />
              2. Pilih Kelas Tujuan
            </label>
            <select 
              v-model="targetClassId" 
              class="select select-bordered select-sm w-full rounded-2xl font-bold text-xs focus:select-primary"
            >
              <option value="" disabled>-- Pilih Kelas Tujuan --</option>
              <option v-for="c in classes" :key="c.id" :value="c.id">
                {{ c.className }}
              </option>
            </select>
          </div>

          <div class="sm:col-span-6 space-y-1">
            <label class="text-xs font-black uppercase tracking-wider text-base-content/50 flex items-center gap-1.5">
              <Icon name="mingcute:group-fill" class="text-sky-500" size="16" />
              Rombel Baru (Opsional)
            </label>
            <input 
              v-model="targetRombel"
              type="text" 
              placeholder="Contoh: Rombel A / 1" 
              class="input input-bordered input-sm w-full rounded-2xl font-bold text-xs focus:input-primary"
            />
          </div>
        </div>
      </div>

      <!-- Student Selection Table -->
      <div class="bg-base-100 rounded-3xl border border-base-200 shadow-sm overflow-hidden">
        
        <!-- Search & Quick Selection Header -->
        <div class="p-5 border-b border-base-200 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div class="flex items-center gap-3">
            <input 
              type="checkbox" 
              :checked="isAllSelected" 
              @change="toggleSelectAll"
              class="checkbox checkbox-primary checkbox-sm rounded-lg"
            />
            <div>
              <h3 class="font-black text-sm text-base-content">
                Daftar Siswa ({{ selectedStudentIds.length }}/{{ filteredStudents.length }} Terpilih)
              </h3>
              <p class="text-[11px] text-base-content/50">Centang siswa yang akan dipindahkan ke kelas tujuan</p>
            </div>
          </div>

          <div class="relative w-full sm:w-64">
            <Icon name="mingcute:search-line" class="absolute left-3 top-1/2 -translate-y-1/2 text-base-content/40" size="16" />
            <input 
              v-model="searchQuery" 
              type="text" 
              placeholder="Cari nama, NIS, rombel..." 
              class="input input-sm input-bordered w-full pl-9 rounded-xl text-xs font-semibold"
            />
          </div>
        </div>

        <!-- Table View -->
        <div class="overflow-x-auto">
          <table class="table table-zebra w-full text-xs">
            <thead>
              <tr class="bg-base-200/40 text-[10px] uppercase tracking-wider font-black text-base-content/50">
                <th class="w-12 text-center">Pilih</th>
                <th>Siswa</th>
                <th>NIS / NISN</th>
                <th>Rombel Saat Ini</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="loading">
                <td colspan="5" class="py-12 text-center text-base-content/40">
                  <span class="loading loading-spinner loading-md text-primary"></span>
                  <p class="mt-2 font-bold">Memuat daftar siswa...</p>
                </td>
              </tr>
              <tr v-else-if="filteredStudents.length === 0">
                <td colspan="5" class="py-12 text-center text-base-content/40 font-bold">
                  Tidak ada siswa aktif ditemukan di kelas asal ini.
                </td>
              </tr>
              <tr 
                v-else
                v-for="s in filteredStudents" 
                :key="s.id"
                @click="toggleSelectStudent(s.id)"
                :class="['cursor-pointer transition-colors', selectedStudentIds.includes(s.id) ? 'bg-primary/5' : '']"
              >
                <td class="text-center" @click.stop>
                  <input 
                    type="checkbox" 
                    :checked="selectedStudentIds.includes(s.id)"
                    @change="toggleSelectStudent(s.id)"
                    class="checkbox checkbox-primary checkbox-xs rounded"
                  />
                </td>
                <td>
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-black text-xs shrink-0 overflow-hidden">
                      <img v-if="s.photoUrl || s.faceUrl" :src="s.photoUrl || s.faceUrl" class="w-full h-full object-cover" />
                      <span v-else>{{ s.name?.charAt(0) }}</span>
                    </div>
                    <span class="font-bold text-base-content">{{ s.name }}</span>
                  </div>
                </td>
                <td class="font-mono font-semibold text-base-content/70">
                  {{ s.nis || s.nisn || '-' }}
                </td>
                <td>
                  <span class="px-2.5 py-0.5 rounded-lg bg-sky-500/10 border border-sky-500/20 text-sky-400 font-extrabold text-[10px]">
                    {{ s.rombel || 'Tanpa Rombel' }}
                  </span>
                </td>
                <td>
                  <span class="px-2 py-0.5 rounded-md bg-emerald-500/10 text-emerald-400 font-black text-[9px] uppercase">
                    {{ s.status || 'AKTIF' }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Floating Action Footer -->
      <div v-if="selectedStudentIds.length > 0" class="fixed bottom-6 left-1/2 -translate-x-1/2 bg-base-100/90 backdrop-blur-md border border-primary/30 p-4 rounded-3xl shadow-2xl flex items-center gap-6 z-50 animate-in slide-in-from-bottom duration-300">
        <div>
          <p class="text-xs font-black text-white">
            {{ selectedStudentIds.length }} Siswa Terpilih
          </p>
          <p class="text-[11px] text-base-content/60">
            Akan dipindahkan ke kelas yang dipilih
          </p>
        </div>

        <button 
          @click="handleWebReshuffle"
          :disabled="submitting || !targetClassId"
          class="btn btn-primary btn-sm rounded-2xl font-black shadow-lg shadow-primary/30 px-6 gap-2"
        >
          <span v-if="submitting" class="loading loading-spinner loading-xs"></span>
          <Icon v-else name="mingcute:transfer-4-line" size="16" />
          Proses Reshuffle Ke Kelas Tujuan
        </button>
      </div>

    </div>

    <!-- TAB 2: RESHUFFLE VIA UPLOAD EXCEL -->
    <div v-if="activeTab === 'excel'" class="space-y-6">
      
      <!-- Step 1: Download Template -->
      <div class="bg-base-100 p-6 rounded-3xl border border-base-200 shadow-sm grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
        <div class="md:col-span-7 space-y-1">
          <div class="flex items-center gap-2 text-amber-400 text-xs font-black uppercase tracking-wider">
            <Icon name="mingcute:download-3-fill" size="16" />
            Langkah 1: Unduh Template Excel Reshuffle
          </div>
          <h3 class="text-base font-black text-base-content">Unduh File Template Pre-Filled</h3>
          <p class="text-xs text-base-content/60">
            Template berisi daftar seluruh siswa aktif beserta ID, NIS, dan kolom **Kelas Tujuan** & **Rombel Baru** yang siap Anda isi.
          </p>
        </div>

        <div class="md:col-span-5 flex flex-col sm:flex-row items-center gap-3">
          <select v-model="excelTemplateClassId" class="select select-bordered select-sm w-full sm:w-auto rounded-2xl text-xs font-bold">
            <option value="">-- Semua Kelas --</option>
            <option v-for="c in classes" :key="c.id" :value="c.id">{{ c.className }}</option>
          </select>

          <button 
            @click="handleDownloadTemplate"
            class="btn btn-amber bg-amber-500 hover:bg-amber-600 text-black border-0 btn-sm rounded-2xl font-black w-full sm:w-auto shrink-0 gap-2 shadow-lg shadow-amber-500/20"
          >
            <Icon name="mingcute:file-download-line" size="16" />
            Unduh Template .XLSX
          </button>
        </div>
      </div>

      <!-- Step 2: Upload Excel -->
      <div class="bg-base-100 p-6 rounded-3xl border border-base-200 shadow-sm space-y-4">
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div class="flex items-center gap-2 text-emerald-400 text-xs font-black uppercase tracking-wider">
            <Icon name="mingcute:upload-3-fill" size="16" />
            Langkah 2: Pilih Kelas Tujuan & Unggah File Excel
          </div>

          <div class="flex items-center gap-2">
            <label class="text-xs font-bold text-base-content/60 shrink-0">Kelas Tujuan:</label>
            <select v-model="excelTargetClassId" class="select select-bordered select-sm rounded-2xl font-bold text-xs focus:select-primary">
              <option value="" disabled>-- Pilih Kelas Tujuan --</option>
              <option v-for="c in classes" :key="c.id" :value="c.id">{{ c.className }}</option>
            </select>
          </div>
        </div>

        <div class="border-2 border-dashed border-base-300 rounded-3xl p-8 text-center hover:border-primary transition-colors cursor-pointer relative bg-base-200/20">
          <input 
            type="file" 
            accept=".xlsx, .xls, .csv" 
            @change="handleFileUpload"
            class="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
          />
          <div class="space-y-2">
            <div class="w-14 h-14 rounded-2xl bg-amber-500/10 text-amber-400 flex items-center justify-center mx-auto border border-amber-500/20">
              <Icon name="mingcute:file-excel-line" size="32" />
            </div>
            <h4 class="font-black text-sm text-base-content">
              {{ excelFile ? excelFile.name : 'Klik atau drag & drop file Excel reshuffle (.xlsx) di sini' }}
            </h4>
            <p class="text-xs text-base-content/50">
              Format 4 Kolom Terbaca: <strong>No</strong> (Absen), <strong>NIS</strong>, <strong>Nama</strong>, <strong>Rombel</strong>
            </p>
          </div>
        </div>

        <!-- Excel Data Preview Table -->
        <div v-if="excelRows.length > 0" class="space-y-4 pt-4 border-t border-base-200">
          <div class="flex items-center justify-between">
            <h4 class="text-xs font-black uppercase tracking-wider text-base-content">
              Preview Data Excel ({{ excelRows.length }} Baris Terbaca)
            </h4>
            <button 
              @click="handleExcelReshuffle" 
              :disabled="submitting"
              class="btn btn-emerald bg-emerald-500 hover:bg-emerald-600 text-black border-0 btn-sm rounded-2xl font-black gap-2 shadow-lg shadow-emerald-500/20"
            >
              <span v-if="submitting" class="loading loading-spinner loading-xs"></span>
              <Icon v-else name="mingcute:check-circle-line" size="16" />
              Proses Reshuffle Dari Excel
            </button>
          </div>

          <div class="overflow-x-auto max-h-96 rounded-2xl border border-base-200">
            <table class="table table-zebra table-compact w-full text-xs">
              <thead>
                <tr class="bg-base-200 text-[10px] uppercase font-black">
                  <th>No (Absen)</th>
                  <th>NIS</th>
                  <th>Nama Siswa</th>
                  <th>Rombel</th>
                  <th>Kelas Tujuan</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(row, idx) in excelRows.slice(0, 100)" :key="idx">
                  <td class="font-bold text-center text-amber-400">{{ row['No'] || row['no'] || (idx + 1) }}</td>
                  <td class="font-mono font-bold">{{ row['NIS'] || row['nis'] || row['ID Siswa'] || row.id || '-' }}</td>
                  <td class="font-bold text-base-content">{{ row['Nama'] || row['nama'] || row['Nama Siswa'] || row.name || '-' }}</td>
                  <td>
                    <span class="px-2.5 py-0.5 rounded-lg bg-sky-500/10 border border-sky-500/20 text-sky-400 font-extrabold text-[10px]">
                      {{ row['Rombel'] || row['rombel'] || '-' }}
                    </span>
                  </td>
                  <td>
                    <span class="px-2 py-0.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-extrabold text-[10px]">
                      {{ row['Kelas Tujuan'] || row['Kelas'] || row['Kelas Tujuan (Nama Kelas)'] || 'Kelas Saat Ini' }}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

      </div>

    </div>

  </div>
</template>
