// app/(dashboard)/admin/users/detail/[id]/page.tsx
'use client';

import React, { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { toast } from 'sonner';
import api from '@/lib/api';
import { Icon } from '@/components/ui/icon';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { CustomSelect } from '@/components/shared/CustomSelect';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'https://gaskan-api.smtijogja.my.id';

const getAvatarUrl = (photoUrl?: string) => {
  if (!photoUrl) return '';
  if (photoUrl.startsWith('http://') || photoUrl.startsWith('https://')) return photoUrl;
  return `${API_BASE}${photoUrl.startsWith('/') ? '' : '/'}${photoUrl}`;
};

export default function UserDetailPage() {
  const params = useParams();
  const router = useRouter();
  const userId = params?.id as string;

  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showRegisterDeviceModal, setShowRegisterDeviceModal] = useState(false);

  const [activeDevices, setActiveDevices] = useState<any[]>([]);
  const [selectedDevice, setSelectedDevice] = useState('ALL');
  const [registeringState, setRegisteringState] = useState(false);

  const [editForm, setEditForm] = useState({
    name: '',
    email: '',
    nis: '',
    nisn: '',
    role: 'SISWA',
    phone: '',
    gender: '',
    religion: '',
    birthDate: '',
    birthPlace: '',
    address: '',
    vehiclePlate: '',
    status: 'AKTIF',
  });

  const fetchUserDetail = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get(`/users/${userId}`).catch(() => api.get(`/students/${userId}`));
      const d = res?.data?.data || res?.data;
      if (d) {
        setUser(d);
        setEditForm({
          name: d.name || d.nama || '',
          email: d.email || '',
          nis: d.nis || d.username || '',
          nisn: d.nisn || '',
          role: d.role || 'SISWA',
          phone: d.phone || d.noHp || '',
          gender: d.gender || '',
          religion: d.religion || '',
          birthDate: d.birthDate ? new Date(d.birthDate).toISOString().split('T')[0] : '',
          birthPlace: d.birthPlace || '',
          address: d.address || '',
          vehiclePlate: d.vehiclePlate || '',
          status: d.status || 'AKTIF',
        });
      }
    } catch (err) {
      console.error(err);
      toast.error('Gagal mengambil rincian data pengguna');
    } finally {
      setLoading(false);
    }
  }, [userId]);

  useEffect(() => {
    fetchUserDetail();
  }, [fetchUserDetail]);

  const saveUserDetail = async () => {
    if (!editForm.name) {
      toast.error('Nama wajib diisi');
      return;
    }
    setSaving(true);
    try {
      await api.put(`/users/${userId}`, editForm).catch(() => api.patch(`/students/${userId}`, editForm));
      toast.success('Data pengguna berhasil diperbarui');
      setShowEditModal(false);
      await fetchUserDetail();
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Gagal memperbarui data pengguna');
    } finally {
      setSaving(false);
    }
  };

  const openRegisterDeviceModal = async () => {
    setSelectedDevice('ALL');
    setShowRegisterDeviceModal(true);
    try {
      const res = await api.get('/device');
      const d = res?.data?.data || res?.data || [];
      setActiveDevices(Array.isArray(d) ? d : []);
    } catch (err) {
      console.error(err);
    }
  };

  const handleRegisterToDevice = async () => {
    setRegisteringState(true);
    try {
      await api.post(`/students/${userId}/register-device`, { deviceId: selectedDevice });
      toast.success('Pendaftaran wajah ke perangkat Hikvision berhasil');
      setShowRegisterDeviceModal(false);
      await fetchUserDetail();
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Gagal mendaftarkan ke perangkat');
    } finally {
      setRegisteringState(false);
    }
  };

  if (loading) {
    return (
      <div className="max-w-5xl mx-auto p-12 text-center text-muted-foreground animate-pulse font-bold">
        Memuat detail pengguna...
      </div>
    );
  }

  if (!user) {
    return (
      <div className="max-w-5xl mx-auto p-12 text-center space-y-4">
        <h2 className="text-xl font-black text-foreground">Pengguna Tidak Ditemukan</h2>
        <Button onClick={() => router.push('/admin/users')} className="rounded-2xl">
          Kembali ke Manajemen User
        </Button>
      </div>
    );
  }

  const avatar = getAvatarUrl(user.photoUrl || user.avatar);

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-12 animate-in fade-in duration-500">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Link
          href="/admin/users"
          className="p-2.5 rounded-2xl bg-card border border-border hover:bg-muted/40 transition-all text-muted-foreground"
        >
          <Icon icon="mingcute:left-line" className="text-lg" />
        </Link>
        <div>
          <h1 className="text-2xl font-black tracking-tight text-foreground">Profil Rinci Pengguna</h1>
          <p className="text-xs text-muted-foreground font-semibold">ID Pengguna: #{user.id}</p>
        </div>
      </div>

      {/* Main Profile Card */}
      <div className="bg-card border border-border rounded-3xl p-6 sm:p-8 shadow-sm space-y-6">
        <div className="flex flex-col sm:flex-row items-center sm:items-start gap-6 border-b border-border pb-6">
          <Avatar className="w-24 h-24 border-2 border-primary/20 shadow-md">
            <AvatarImage src={avatar} alt={user.name} />
            <AvatarFallback className="font-black text-2xl bg-primary/10 text-primary">
              {(user.name || 'U').charAt(0).toUpperCase()}
            </AvatarFallback>
          </Avatar>

          <div className="space-y-2 text-center sm:text-left flex-1">
            <div className="flex flex-wrap items-center justify-center sm:justify-start gap-2">
              <h2 className="text-2xl font-black text-foreground">{user.name || user.nama}</h2>
              <Badge className="bg-primary/15 text-primary border-primary/30 text-xs font-black uppercase">
                {user.role || 'SISWA'}
              </Badge>
              <Badge className={user.status === 'AKTIF' ? 'bg-emerald-500/15 text-emerald-500' : 'bg-rose-500/15 text-rose-500'}>
                {user.status || 'AKTIF'}
              </Badge>
            </div>
            <p className="text-xs text-muted-foreground font-mono">
              Username/NIS: {user.nis || user.username || '-'} · Email: {user.email || '-'}
            </p>
            <p className="text-xs text-muted-foreground font-semibold">
              Kelas: {user.class?.className || 'Tidak Terdaftar Dalam Kelas'}
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <Button
              onClick={() => setShowEditModal(true)}
              variant="outline"
              className="rounded-2xl font-bold text-xs gap-2 h-10 border-border"
            >
              <Icon icon="mingcute:pencil-line" className="text-base" />
              Edit Profil
            </Button>

            <Button
              onClick={openRegisterDeviceModal}
              className="rounded-2xl font-black text-xs bg-primary text-primary-foreground gap-2 h-10 px-4"
            >
              <Icon icon="mingcute:face-fill" className="text-base" />
              Register Hikvision Gate
            </Button>
          </div>
        </div>

        {/* Detailed Attributes Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <span className="text-[10px] font-black uppercase text-muted-foreground/60">Nomor HP / WA</span>
            <p className="text-sm font-bold text-foreground mt-1">{user.phone || user.noHp || '-'}</p>
          </div>

          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <span className="text-[10px] font-black uppercase text-muted-foreground/60">Plat Kendaraan</span>
            <p className="text-sm font-mono font-bold text-foreground mt-1">{user.vehiclePlate || '-'}</p>
          </div>

          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <span className="text-[10px] font-black uppercase text-muted-foreground/60">Jenis Kelamin</span>
            <p className="text-sm font-bold text-foreground mt-1">{user.gender || '-'}</p>
          </div>

          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <span className="text-[10px] font-black uppercase text-muted-foreground/60">Agama</span>
            <p className="text-sm font-bold text-foreground mt-1">{user.religion || '-'}</p>
          </div>

          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <span className="text-[10px] font-black uppercase text-muted-foreground/60">Tempat, Tgl Lahir</span>
            <p className="text-sm font-bold text-foreground mt-1">
              {user.birthPlace || '-'}, {user.birthDate ? new Date(user.birthDate).toLocaleDateString('id-ID') : '-'}
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-muted/30 border border-border">
            <span className="text-[10px] font-black uppercase text-muted-foreground/60">Alamat Tempat Tinggal</span>
            <p className="text-sm font-bold text-foreground mt-1 truncate">{user.address || '-'}</p>
          </div>
        </div>
      </div>

      {/* Edit Profile Modal */}
      <Dialog open={showEditModal} onOpenChange={setShowEditModal}>
        <DialogContent className="sm:max-w-lg rounded-3xl p-6">
          <DialogHeader>
            <DialogTitle className="text-lg font-black text-foreground flex items-center gap-2">
              <Icon icon="mingcute:pencil-fill" className="text-primary text-xl" />
              Edit Informasi Profil Pengguna
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-3 py-2 max-h-[60vh] overflow-y-auto custom-scrollbar pr-1">
            <div className="space-y-1">
              <Label className="text-xs font-bold">Nama Lengkap</Label>
              <Input
                type="text"
                value={editForm.name}
                onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                className="rounded-2xl h-10 text-xs font-semibold"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label className="text-xs font-bold">Username / NIS</Label>
                <Input
                  type="text"
                  value={editForm.nis}
                  onChange={(e) => setEditForm({ ...editForm, nis: e.target.value })}
                  className="rounded-2xl h-10 text-xs font-semibold"
                />
              </div>

              <div className="space-y-1">
                <Label className="text-xs font-bold">Role Hak Akses</Label>
                <CustomSelect
                  value={editForm.role}
                  onChange={(val) => setEditForm({ ...editForm, role: val })}
                  options={[
                    { label: 'SISWA', value: 'SISWA' },
                    { label: 'GURU', value: 'GURU' },
                    { label: 'ADMIN', value: 'ADMIN' },
                    { label: 'DEVELOPER', value: 'DEVELOPER' },
                  ]}
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label className="text-xs font-bold">Email</Label>
                <Input
                  type="email"
                  value={editForm.email}
                  onChange={(e) => setEditForm({ ...editForm, email: e.target.value })}
                  className="rounded-2xl h-10 text-xs font-semibold"
                />
              </div>

              <div className="space-y-1">
                <Label className="text-xs font-bold">Nomor HP</Label>
                <Input
                  type="text"
                  value={editForm.phone}
                  onChange={(e) => setEditForm({ ...editForm, phone: e.target.value })}
                  className="rounded-2xl h-10 text-xs font-semibold"
                />
              </div>
            </div>

            <div className="space-y-1">
              <Label className="text-xs font-bold">Plat Kendaraan</Label>
              <Input
                type="text"
                placeholder="AB 1234 CD"
                value={editForm.vehiclePlate}
                onChange={(e) => setEditForm({ ...editForm, vehiclePlate: e.target.value })}
                className="rounded-2xl h-10 text-xs font-mono font-semibold"
              />
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowEditModal(false)} className="rounded-2xl font-bold text-xs h-10">
              Batal
            </Button>
            <Button
              onClick={saveUserDetail}
              disabled={saving}
              className="rounded-2xl font-bold text-xs bg-primary text-primary-foreground px-6 h-10"
            >
              {saving ? 'Memproses...' : 'Simpan Perubahan'}
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Register Hikvision Gate Device Modal */}
      <Dialog open={showRegisterDeviceModal} onOpenChange={setShowRegisterDeviceModal}>
        <DialogContent className="sm:max-w-md rounded-3xl p-6">
          <DialogHeader>
            <DialogTitle className="text-lg font-black text-foreground flex items-center gap-2">
              <Icon icon="mingcute:face-fill" className="text-primary text-xl" />
              Register Wajah ke Physical Gate Hikvision
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-2">
            <p className="text-xs text-muted-foreground font-medium">
              Kirimkan data template wajah pengguna <strong>{user.name}</strong> ke mesin gerbang fisik Hikvision untuk verifikasi presensi otomatis.
            </p>

            <div className="space-y-1">
              <Label className="text-xs font-bold">Pilih Target Perangkat Gate</Label>
              <CustomSelect
                value={selectedDevice}
                onChange={(val) => setSelectedDevice(val)}
                options={[
                  { label: 'Semua Perangkat Active Gate (ALL)', value: 'ALL' },
                  ...activeDevices.map((d: any) => ({ label: d.deviceName || d.name || d.ipAddress, value: d.id })),
                ]}
              />
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowRegisterDeviceModal(false)} className="rounded-2xl font-bold text-xs h-10">
              Batal
            </Button>
            <Button
              onClick={handleRegisterToDevice}
              disabled={registeringState}
              className="rounded-2xl font-bold text-xs bg-primary text-primary-foreground px-5 h-10"
            >
              {registeringState ? 'Mengirim...' : 'Sinkronkan Sekarang'}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// pages/admin/users/detail/[id].vue
<script setup>
import { ref, onMounted } from 'vue';
const route = useRoute();
const router = useRouter();
const config = useRuntimeConfig();
const { $toast } = useNuxtApp();

const user = ref(null);
const loading = ref(true);

const fetchUserDetail = async () => {
  loading.value = true;
  try {
    const res = await $fetch(`/api/users/${route.params.id}`);
    user.value = res?.data || null;
  } catch (err) {
    $toast.error('Gagal mengambil data user');
    router.push('/admin/users');
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  fetchUserDetail();
});

const getAvatar = (u) => {
  if (!u || !u.photoUrl) return null;
  if (u.photoUrl.startsWith('http')) return u.photoUrl;
  
  // Use the Nuxt API proxy for uploads
  const filename = u.photoUrl.split('/').pop();
  return `/api/uploads/profiles/${filename}`;
};

const getInitials = (name) => {
  if (!name) return '??';
  return name.split(' ').filter(Boolean).map(n => n[0]).slice(0, 2).join('').toUpperCase();
};

const formatDate = (date) => {
  if (!date) return '-';
  return new Date(date).toLocaleDateString('id-ID', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

const bentoCard = "bg-base-100 rounded-3xl p-6 md:p-8 border border-base-200/60 shadow-sm transition-all duration-300";

const isDeletingPhoto = ref(false);
const showDeleteConfirm = ref(false);

const deleteUserPhoto = async () => {
  isDeletingPhoto.value = true;
  try {
    const res = await $fetch(`/api/users/${route.params.id}/photo`, { method: 'DELETE' });
    if (res.success) {
      $toast.success('Foto profil berhasil dihapus');
      showDeleteConfirm.value = false;
      await fetchUserDetail();
    }
  } catch (e) {
    $toast.error('Gagal menghapus foto profil');
  } finally {
    isDeletingPhoto.value = false;
  }
};
</script>

<template>
  <div class="max-w-5xl mx-auto py-6 md:py-10 px-4 space-y-6 md:space-y-8 text-left">
    
    <!-- Back Button & Title -->
    <div class="flex items-center gap-4">
      <button @click="router.back()" class="btn btn-ghost btn-sm md:btn-md rounded-2xl bg-base-200/50">
        <Icon name="mingcute:left-line" size="20" />
        <span class="hidden md:inline">Kembali</span>
      </button>
      <div>
        <h1 class="text-xl md:text-2xl font-black text-base-content tracking-tight">Detail Pengguna</h1>
        <p class="text-xs md:text-sm text-base-content/50">Informasi sistem lengkap untuk akun ini</p>
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="flex flex-col items-center justify-center py-20 gap-4">
      <span class="loading loading-spinner loading-lg text-primary opacity-40"></span>
      <p class="text-xs font-bold uppercase tracking-widest text-base-content/30">Memuat Data...</p>
    </div>

    <div v-else-if="user" class="grid grid-cols-1 lg:grid-cols-3 gap-6 md:gap-8">
      
      <!-- Left: Profile Summary -->
      <div class="lg:col-span-1 space-y-6">
        <div :class="[bentoCard, 'flex flex-col items-center text-center pt-10']">
          <div class="relative group">
            <div class="w-24 h-24 md:w-32 md:h-32 rounded-[2.5rem] bg-primary/10 flex items-center justify-center text-primary text-3xl md:text-4xl font-black overflow-hidden border-4 border-base-200 shadow-xl mb-6">
              <img v-if="getAvatar(user)" :src="getAvatar(user)" class="w-full h-full object-cover" />
              <span v-else>{{ getInitials(user.name) }}</span>
            </div>
            <div :class="['absolute bottom-8 right-0 w-6 h-6 rounded-full border-4 border-base-100 shadow-sm', user.isActive ? 'bg-success' : 'bg-base-300']"></div>
          </div>
          
          <h2 class="text-xl md:text-2xl font-black text-base-content break-words max-w-full">{{ user.name }}</h2>
          <div :class="['mt-2 px-4 py-1 rounded-full text-[10px] font-black tracking-widest border uppercase', 
            user.role === 'ADMIN' ? 'bg-violet-500/10 text-violet-400 border-violet-500/20' : 
            user.role === 'GURU' ? 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20' : 
            'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
          ]">
            {{ user.role }}
          </div>
          
          <!-- Admin Action: Delete Photo -->
          <button 
            v-if="user.photoUrl"
            @click="showDeleteConfirm = true"
            class="btn btn-ghost btn-xs mt-4 text-error gap-1.5 hover:bg-error/10 rounded-lg"
          >
            <Icon name="mingcute:delete-2-fill" />
            Hapus Foto
          </button>
          
          <div class="w-full grid grid-cols-2 gap-4 mt-8 pt-8 border-t border-base-200/60">
             <div class="text-center">
               <p class="text-[10px] font-bold text-base-content/30 uppercase mb-1">Status</p>
               <p :class="['text-xs font-black uppercase', user.isActive ? 'text-success' : 'text-base-content/40']">{{ user.isActive ? 'Aktif' : 'Nonaktif' }}</p>
             </div>
             <div class="text-center border-l border-base-200/60 min-w-0">
               <p class="text-[10px] font-bold text-base-content/30 uppercase mb-1">ID Sistem</p>
               <p class="text-[10px] font-black text-base-content/60 truncate px-1" :title="user.id">#{{ user.id }}</p>
             </div>
          </div>
        </div>

        <!-- System Times -->
        <div :class="[bentoCard, 'p-6 bg-base-200/20']">
          <h3 class="text-xs font-black text-base-content/40 uppercase tracking-widest mb-4">Metadata Sistem</h3>
          <div class="space-y-4">
            <div class="flex items-start gap-3">
              <Icon name="mingcute:time-line" class="text-base-content/30 mt-0.5" />
              <div>
                <p class="text-[10px] font-bold text-base-content/30 uppercase">Dibuat Pada</p>
                <p class="text-xs font-medium text-base-content/70">{{ formatDate(user.createdAt) }}</p>
              </div>
            </div>
            <div class="flex items-start gap-3">
              <Icon name="mingcute:refresh-2-line" class="text-base-content/30 mt-0.5" />
              <div>
                <p class="text-[10px] font-bold text-base-content/30 uppercase">Update Terakhir</p>
                <p class="text-xs font-medium text-base-content/70">{{ formatDate(user.updatedAt) }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Right: Detailed Info -->
      <div class="lg:col-span-2 space-y-6">
        
        <!-- Account Information -->
        <div :class="[bentoCard]">
          <div class="flex items-center gap-3 mb-8">
            <div class="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
              <Icon name="mingcute:idcard-fill" size="20" />
            </div>
            <h3 class="text-lg font-black text-base-content tracking-tight">Informasi Akun</h3>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-y-6 md:gap-x-12">
            <div>
              <p class="text-[10px] font-bold text-base-content/30 uppercase tracking-widest mb-1">Email</p>
              <p class="text-sm font-medium text-base-content/80 break-all">{{ user.email || 'Tidak Terhubung' }}</p>
            </div>
            <div>
              <p class="text-[10px] font-bold text-base-content/30 uppercase tracking-widest mb-1">NIS (Username)</p>
              <p class="text-sm font-medium text-base-content/80">{{ user.nis || '-' }}</p>
            </div>
            <div v-if="user.role === 'SISWA'">
              <p class="text-[10px] font-bold text-base-content/30 uppercase tracking-widest mb-1">NISN</p>
              <p class="text-sm font-medium text-base-content/80">{{ user.nisn || '-' }}</p>
            </div>
            <div v-if="user.role === 'SISWA'">
              <p class="text-[10px] font-bold text-base-content/30 uppercase tracking-widest mb-1">Kelas Saat Ini</p>
              <div class="flex items-center gap-2 mt-1">
                <span class="badge badge-primary badge-outline font-black text-[10px]">{{ user.class?.className || 'BELUM SET' }}</span>
                <span v-if="user.class" class="text-[10px] text-base-content/40 font-medium">#{{ user.classId }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Role Permissions Info -->
        <div :class="[bentoCard, 'bg-primary/5 border-primary/10']">
           <div class="flex items-start gap-4">
              <div class="w-12 h-12 rounded-2xl bg-white flex items-center justify-center text-primary shadow-sm shrink-0">
                <Icon name="mingcute:safety-certificate-fill" size="24" />
              </div>
              <div>
                <h4 class="font-black text-base-content mb-1">Hak Akses: {{ user.role }}</h4>
                <p class="text-xs text-base-content/60 leading-relaxed">
                  {{ 
                    user.role === 'ADMIN' ? 'Memiliki kontrol penuh terhadap manajemen user, sistem import, pengaturan kelas, dan seluruh modul akademik.' :
                    user.role === 'GURU' ? 'Dapat melakukan absensi harian, mengelola jurnal kelas, dan melihat data siswa yang terdaftar di kelasnya.' :
                    'Dapat melihat dashboard pribadi, status kehadiran, dan menerima pengumuman dari sekolah.'
                  }}
                </p>
              </div>
           </div>
        </div>

        <!-- System ID (Full) -->
        <div :class="[bentoCard, 'bg-base-200/20 border-dashed']">
          <p class="text-[10px] font-bold text-base-content/30 uppercase mb-2">ID Sistem Lengkap</p>
          <div class="bg-base-100 p-3 rounded-xl border border-base-200 font-mono text-[10px] text-base-content/60 break-all select-all cursor-pointer" title="Klik untuk pilih">
            {{ user.id }}
          </div>
        </div>

        <!-- Quick Actions -->
        <div class="flex flex-wrap gap-3">
          <button @click="$toast.info('Fitur reset password menyusul')" class="btn btn-ghost border-base-300 rounded-2xl gap-2 flex-1 md:flex-none">
            <Icon name="mingcute:key-2-line" />
            Reset Password
          </button>
          <NuxtLink :to="`/admin/users`" class="btn btn-ghost border-base-300 rounded-2xl gap-2 flex-1 md:flex-none">
            <Icon name="mingcute:list-check-line" />
            Manajemen User
          </NuxtLink>
        </div>

      </div>
    </div>

    <!-- Modal: Delete Photo Confirmation -->
    <dialog v-if="user" :class="['modal modal-bottom sm:modal-middle', { 'modal-open': showDeleteConfirm }]">
      <div class="modal-box bg-base-100 border border-base-200/60 shadow-2xl rounded-t-[2rem] sm:rounded-[2rem] p-8 text-center">
        <div class="w-16 h-16 rounded-full bg-error/10 text-error flex items-center justify-center mx-auto mb-4">
          <Icon name="mingcute:delete-2-fill" size="32" />
        </div>
        <h3 class="font-bold text-xl text-base-content mb-2">Hapus Foto User?</h3>
        <p class="text-sm text-base-content/60 mb-8 px-4">
          Tindakan ini akan menghapus foto profil kustom milik <b>{{ user.name }}</b> secara permanen.
        </p>
        
        <div class="flex flex-col sm:flex-row gap-3">
          <button @click="showDeleteConfirm = false" class="btn btn-ghost flex-1 rounded-2xl order-2 sm:order-1">Batal</button>
          <button 
            @click="deleteUserPhoto" 
            class="btn btn-error text-white flex-1 rounded-2xl shadow-lg shadow-error/20 order-1 sm:order-2"
            :disabled="isDeletingPhoto"
          >
            <span v-if="isDeletingPhoto" class="loading loading-spinner loading-xs"></span>
            Ya, Hapus
          </button>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop bg-black/40 backdrop-blur-sm" @click="showDeleteConfirm = false">
        <button>close</button>
      </form>
    </dialog>
  </div>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar { width: 4px; }
.custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(var(--bc), 0.1); border-radius: 10px; }
</style>
