// pages/login.vue
<script setup>
definePageMeta({ layout: false })

import { storeToRefs } from 'pinia';
import { useAuthStore } from '~/store/useAuthStore';
const { authenticateUser } = useAuthStore()
const { authenticated } = storeToRefs(useAuthStore())
const router = useRouter()

const user = ref({ NIS: '', Password: '', force: false })
const error = ref(false)
const errorMessage = ref('')
const isLoading = ref(false)
const showPassword = ref(false)

const login = async () => {
  error.value = false
  isLoading.value = true
  try {
    await authenticateUser(user.value)
    if (authenticated.value) {
      router.push('/home')
    }
  } catch (err) {
    error.value = true
    // Robust error message extraction
    const rawError = err.data?.data || err.data || err
    if (typeof rawError === 'string') {
      errorMessage.value = { error: rawError }
    } else if (rawError.message && !rawError.error) {
      errorMessage.value = { error: rawError.message, ...rawError }
    } else {
      errorMessage.value = rawError
    }
  } finally {
    isLoading.value = false
  }
}

const forceLogin = async () => {
  user.value.force = true
  await authenticateUser(user.value)
  if (authenticated.value) {
    router.push('/home')
  }
}

useSeoMeta({
  title: 'Login | GASKAN',
  ogTitle: 'Login | GASKAN',
  description: 'Login ke Gerbang Akses Pintar dan Kehadiran',
  image: '/banner.webp',
  url: 'https://gaskan.smtijogja.sch.id/login',
  ogUrl: 'https://gaskan.smtijogja.sch.id/login',
  ogDescription: 'Login ke Gerbang Akses Pintar dan Kehadiran',
  ogImage: '/banner.webp',
  ogType: 'website',
  ogSiteName: 'GASKAN',
  ogLocale: 'id_ID',
  twitterCard: 'summary_large_image',
  twitterTitle: 'Login | GASKAN',
  twitterDescription: 'Login ke Gerbang Akses Pintar dan Kehadiran',
  twitterImage: '/banner.webp',
  twitterUrl: 'https://gaskan.smtijogja.sch.id/login',
})
</script>

<template>
  <div class="min-h-screen flex items-stretch">
    <!-- Left panel: Branding -->
    <div class="hidden lg:flex lg:w-1/2 bg-primary/10 border-r border-base-300 relative overflow-hidden flex-col items-center justify-center p-12 gap-8">
      <!-- Background blobs -->
      <div class="absolute top-0 left-0 w-72 h-72 bg-primary/20 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2 pointer-events-none" />
      <div class="absolute bottom-0 right-0 w-96 h-96 bg-primary/10 rounded-full blur-3xl translate-x-1/3 translate-y-1/3 pointer-events-none" />

      <div class="relative z-10 text-center space-y-6 max-w-sm">
        <!-- Logo -->
        <div class="flex items-center justify-center gap-3 mb-4">
          <div class="w-14 h-14 rounded-2xl bg-primary/15 border border-primary/30 flex items-center justify-center">
            <Icon name="mingcute:key-2-fill" class="text-3xl text-primary" />
          </div>
          <span class="text-3xl font-extrabold">GASKAN</span>
        </div>

        <h2 class="text-2xl font-bold leading-tight">
          Sistem Absensi Digital<br />
          <span class="text-primary">SMTI Jogja</span>
        </h2>
        <p class="opacity-50 text-sm leading-relaxed">
          Kelola dan pantau kehadiran siswa secara real-time dengan mudah, cepat, dan akurat.
        </p>

        <!-- Stats preview -->
        <div class="grid grid-cols-3 gap-3 pt-4">
          <div class="bg-base-100/60 rounded-xl p-3 border border-base-300">
            <p class="text-xl font-bold text-primary">500+</p>
            <p class="text-xs opacity-50 mt-0.5">Siswa</p>
          </div>
          <div class="bg-base-100/60 rounded-xl p-3 border border-base-300">
            <p class="text-xl font-bold text-primary">3</p>
            <p class="text-xs opacity-50 mt-0.5">Role</p>
          </div>
          <div class="bg-base-100/60 rounded-xl p-3 border border-base-300">
            <p class="text-xl font-bold text-primary">99.9%</p>
            <p class="text-xs opacity-50 mt-0.5">Uptime</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Right panel: Login form -->
    <div class="w-full lg:w-1/2 flex items-center justify-center p-6">
      <div class="w-full max-w-md space-y-8">
        <!-- Mobile logo -->
        <div class="flex lg:hidden items-center gap-2 mb-2">
          <Icon name="mingcute:key-2-fill" class="text-primary text-2xl" />
          <span class="text-xl font-extrabold">GASKAN</span>
        </div>

        <!-- Heading -->
        <div class="space-y-1">
          <h1 class="text-3xl font-extrabold">Selamat Datang</h1>
          <p class="opacity-50 text-sm">Masuk dengan NIS / Email dan password kamu</p>
        </div>

        <!-- Error alert -->
        <Transition name="fade">
          <div v-if="error" class="alert alert-error rounded-xl text-sm py-3 px-4 flex items-start gap-3 border-none shadow-lg shadow-error/20 bg-error text-error-content">
            <Icon name="mingcute:warning-fill" class="text-xl shrink-0 mt-0.5" />
            <div class="flex-1 flex flex-col gap-1 text-left">
              <span class="font-bold">Login Gagal</span>
              <span class="opacity-90 leading-tight">{{ errorMessage.error || errorMessage.message || 'Email/NIS atau password salah' }}</span>
            </div>
            <button
              v-if="errorMessage.code === 400"
              @click.prevent="forceLogin"
              class="btn btn-xs btn-ghost bg-white/20 hover:bg-white/30"
            >
              Paksa Masuk
            </button>
          </div>
        </Transition>

        <!-- Form -->
        <form class="space-y-5" @submit.prevent="login">
          <!-- NIS / Email field -->
          <div class="space-y-2">
            <label for="nis" class="block text-sm font-semibold">NIS / Email</label>
            <div class="relative">
              <div class="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none">
                <Icon name="mingcute:user-4-line" class="text-lg opacity-40" />
              </div>
              <input
                type="text"
                id="nis"
                v-model="user.NIS"
                placeholder="Masukkan NIS / Email kamu"
                required
                class="input input-bordered w-full pl-10 rounded-xl bg-base-200 border-base-300 focus:border-primary focus:outline-none"
              />
            </div>
          </div>

          <!-- Password field -->
          <div class="space-y-2">
            <div class="flex items-center justify-between">
              <label for="password" class="block text-sm font-semibold">Password</label>
              <NuxtLink to="/forgot-password" class="text-xs font-bold text-primary hover:opacity-80 transition-opacity">
                Lupa Password?
              </NuxtLink>
            </div>
            <div class="relative">
              <div class="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none">
                <Icon name="mingcute:lock-line" class="text-lg opacity-40" />
              </div>
              <input
                :type="showPassword ? 'text' : 'password'"
                id="password"
                v-model="user.Password"
                placeholder="••••••••"
                required
                class="input input-bordered w-full pl-10 pr-12 rounded-xl bg-base-200 border-base-300 focus:border-primary focus:outline-none"
              />
              <button
                type="button"
                @click="showPassword = !showPassword"
                class="absolute inset-y-0 right-0 pr-3.5 flex items-center opacity-40 hover:opacity-80 transition-opacity"
              >
                <Icon :name="showPassword ? 'mingcute:eye-close-line' : 'mingcute:eye-line'" class="text-lg" />
              </button>
            </div>
          </div>

          <!-- Submit -->
          <button
            id="login-submit"
            type="submit"
            :disabled="isLoading"
            class="btn btn-primary w-full rounded-xl font-bold text-base shadow-lg hover:shadow-primary/30 transition-shadow"
          >
            <Icon v-if="isLoading" name="mingcute:loading-3-line" class="animate-spin mr-2" />
            <span>{{ isLoading ? 'Memproses...' : 'Masuk ke GASKAN' }}</span>
          </button>
        </form>

        <p class="text-center text-sm opacity-40">
          <NuxtLink to="/" class="hover:opacity-80 transition-opacity hover:text-primary">
            ← Kembali ke halaman utama
          </NuxtLink>
        </p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active, .fade-leave-active { transition: opacity 0.3s, transform 0.3s; }
.fade-enter-from, .fade-leave-to { opacity: 0; transform: translateY(-8px); }
</style>

// gaskan-next/app/(auth)/login/page.tsx
'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { toast } from 'sonner';
import { Icon } from '@iconify/react';
import api from '@/lib/api';
import { useAuth } from '@/context/AuthContext';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';

export default function LoginPage() {
  const router = useRouter();
  const { login } = useAuth();
  const [identifier, setIdentifier] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [errorData, setErrorData] = useState<{ message?: string; code?: number; canForce?: boolean } | null>(null);

  const performLogin = async (force: boolean = false) => {
    if (!identifier || !password) {
      toast.error('Silakan isi NIS / Email dan Password');
      return;
    }

    setIsLoading(true);
    setErrorData(null);

    const payload = {
      NIS: identifier,
      email: identifier,
      username: identifier,
      Password: password,
      password: password,
      force,
    };

    try {
      // Call primary login endpoint or fallback endpoint
      let response;
      try {
        response = await api.post('/auth/login', payload);
      } catch (firstErr: any) {
        if (firstErr?.response?.status === 404) {
          response = await api.post('/api/auth/login', payload);
        } else {
          throw firstErr;
        }
      }

      const resData = response.data;

      // Extract user info and token
      const token =
        resData?.token ||
        resData?.access_token ||
        resData?.data?.token ||
        response.headers['authorization']?.replace('Bearer ', '') ||
        'session_active';

      const user =
        resData?.user ||
        resData?.data?.user ||
        resData?.data || {
          id: resData?.id || identifier,
          nis: resData?.nis || identifier,
          name: resData?.nama || resData?.name || identifier,
          role: resData?.role || (identifier.toLowerCase().includes('admin') ? 'admin' : 'siswa'),
          email: resData?.email || (identifier.includes('@') ? identifier : `${identifier}@smtijogja.sch.id`),
        };

      login(token, user);
      toast.success('Login berhasil! Selamat datang.');
      router.push('/home');
    } catch (err: any) {
      console.error('API login error response:', err?.response?.data || err);

      const errResponseData = err?.response?.data;
      const statusCode = err?.response?.status;
      const apiMessage =
        errResponseData?.message ||
        errResponseData?.error ||
        errResponseData?.data?.message ||
        (typeof errResponseData === 'string' ? errResponseData : null) ||
        'NIS/Email atau password yang Anda masukkan tidak sesuai.';

      const canForceLogin = statusCode === 400 || errResponseData?.code === 400 || errResponseData?.forceAvailable;

      setErrorData({
        message: apiMessage,
        code: statusCode,
        canForce: canForceLogin,
      });

      toast.error(apiMessage);
    } fontFinally: {
      setIsLoading(false);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    performLogin(false);
  };

  const handleForceLogin = () => {
    performLogin(true);
  };

  return (
    <div className="min-h-screen flex items-stretch bg-background">
      {/* Left panel: Branding */}
      <div className="hidden lg:flex lg:w-1/2 bg-primary/10 border-r border-border relative overflow-hidden flex-col items-center justify-center p-12 gap-8">
        <div className="absolute top-0 left-0 w-72 h-72 bg-primary/20 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2 pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-96 h-96 bg-primary/10 rounded-full blur-3xl translate-x-1/3 translate-y-1/3 pointer-events-none" />

        <div className="relative z-10 text-center space-y-6 max-w-sm">
          <div className="flex items-center justify-center gap-3 mb-4">
            <div className="w-14 h-14 rounded-2xl bg-primary/15 border border-primary/30 flex items-center justify-center text-primary">
              <Icon icon="mingcute:key-2-fill" className="text-3xl" />
            </div>
            <span className="text-3xl font-extrabold tracking-tight">GASKAN</span>
          </div>

          <h2 className="text-2xl font-bold leading-tight">
            Sistem Absensi Digital<br />
            <span className="text-primary">SMTI Jogja</span>
          </h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            Kelola dan pantau kehadiran siswa secara real-time dengan mudah, cepat, dan akurat.
          </p>

          <div className="grid grid-cols-3 gap-3 pt-4">
            <div className="bg-card/80 rounded-xl p-3 border border-border">
              <p className="text-xl font-bold text-primary">500+</p>
              <p className="text-xs text-muted-foreground mt-0.5">Siswa</p>
            </div>
            <div className="bg-card/80 rounded-xl p-3 border border-border">
              <p className="text-xl font-bold text-primary">3</p>
              <p className="text-xs text-muted-foreground mt-0.5">Role</p>
            </div>
            <div className="bg-card/80 rounded-xl p-3 border border-border">
              <p className="text-xl font-bold text-primary">99.9%</p>
              <p className="text-xs text-muted-foreground mt-0.5">Uptime</p>
            </div>
          </div>
        </div>
      </div>

      {/* Right panel: Login form */}
      <div className="w-full lg:w-1/2 flex items-center justify-center p-6 sm:p-12">
        <div className="w-full max-w-md space-y-6">
          <div className="flex lg:hidden items-center gap-2 mb-2">
            <Icon icon="mingcute:key-2-fill" className="text-primary text-2xl" />
            <span className="text-xl font-extrabold">GASKAN</span>
          </div>

          <Card className="border-border shadow-md">
            <CardHeader className="space-y-1">
              <CardTitle className="text-2xl font-bold">Selamat Datang</CardTitle>
              <CardDescription>
                Masuk dengan NIS / Email dan password kamu
              </CardDescription>
            </CardHeader>
            <CardContent>
              {errorData && (
                <div className="mb-4 p-3.5 rounded-xl bg-destructive/15 border border-destructive/30 text-destructive text-sm flex items-start justify-between gap-3">
                  <div className="flex items-start gap-2 min-w-0">
                    <Icon icon="mingcute:warning-fill" className="text-lg shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <p className="font-bold text-sm">Login Gagal</p>
                      <p className="text-xs opacity-90 leading-snug">{errorData.message}</p>
                    </div>
                  </div>
                  {errorData.canForce && (
                    <Button
                      type="button"
                      size="sm"
                      variant="outline"
                      onClick={handleForceLogin}
                      className="bg-destructive/20 border-destructive/40 text-destructive hover:bg-destructive/30 font-bold shrink-0 text-xs"
                    >
                      Paksa Masuk
                    </Button>
                  )}
                </div>
              )}

              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="nis">NIS / Email</Label>
                  <div className="relative">
                    <Icon icon="mingcute:user-4-line" className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-lg pointer-events-none" />
                    <Input
                      id="nis"
                      type="text"
                      placeholder="Masukkan NIS / Email kamu"
                      value={identifier}
                      onChange={(e) => setIdentifier(e.target.value)}
                      className="pl-9"
                      required
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="password">Password</Label>
                    <Link
                      href="/forgot-password"
                      className="text-xs font-semibold text-primary hover:underline"
                    >
                      Lupa Password?
                    </Link>
                  </div>
                  <div className="relative">
                    <Icon icon="mingcute:lock-line" className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-lg pointer-events-none" />
                    <Input
                      id="password"
                      type={showPassword ? 'text' : 'password'}
                      placeholder="••••••••"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      className="pl-9 pr-10"
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                      aria-label={showPassword ? 'Sembunyikan password' : 'Tampilkan password'}
                    >
                      <Icon icon={showPassword ? 'mingcute:eye-close-line' : 'mingcute:eye-line'} className="text-lg" />
                    </button>
                  </div>
                </div>

                <Button type="submit" className="w-full font-bold" disabled={isLoading}>
                  {isLoading && <Icon icon="mingcute:loading-3-line" className="animate-spin mr-2 text-lg" />}
                  {isLoading ? 'Memproses...' : 'Masuk ke GASKAN'}
                </Button>
              </form>
            </CardContent>
            <CardFooter className="flex justify-center border-t border-border pt-4">
              <Link href="/" className="text-xs text-muted-foreground hover:text-primary transition-colors">
                ← Kembali ke halaman utama
              </Link>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  );
}
