// pages/admin/users/index.vue
<script setup>
import { ref, onMounted, computed, watch } from 'vue';
import { storeToRefs } from 'pinia';
import { useAuthStore } from '~/store/useAuthStore';

const { role } = storeToRefs(useAuthStore());
const { $toast } = useNuxtApp();
const config = useRuntimeConfig();

useSeoMeta({
  title: 'Manajemen User | GASKAN',
  description: 'Kelola semua pengguna sistem (Admin, Guru, Siswa)',
});

// State
const users = ref([]);
const classes = ref([]);
const loading = ref(true);
const showModal = ref(false);
const editMode = ref(false);
const saving = ref(false);
const searchQuery = ref('');
const filterRole = ref('');
const showDeleteModal = ref(false);
const deleteId = ref(null);
const activeDropdown = ref(null);

// Helper for Profile Picture
const getAvatar = (user) => {
  if (!user || !user.photoUrl) return null;
  if (user.photoUrl.startsWith('http')) return user.photoUrl;
  
  // Use the Nuxt API proxy for uploads
  // If the path contains /uploads/profiles/, we need to extract the filename or the relative path
  const filename = user.photoUrl.split('/').pop();
  return `/api/uploads/profiles/${filename}`;
};

const getInitials = (name) => {
  if (!name) return '??';
  try {
    return name.split(' ').filter(Boolean).map(n => n[0]).slice(0, 2).join('').toUpperCase();
  } catch (e) {
    return '??';
  }
};

// Toggle mobile dropdown
const toggleDropdown = (id) => {
  if (activeDropdown.value === id) activeDropdown.value = null;
  else activeDropdown.value = id;
};

// Close dropdown on click outside
if (process.client) {
  onMounted(() => {
    window.addEventListener('click', (e) => {
      if (!e.target.closest('.mobile-dropdown')) {
        activeDropdown.value = null;
      }
    });
  });
}

// Fetch data
const fetchUsers = async () => {
  loading.value = true;
  try {
    const data = await $fetch('/api/users');
    users.value = Array.isArray(data?.data) ? data.data : [];
  } catch (e) {
    console.error('Failed to fetch users:', e);
    users.value = [];
  } finally {
    loading.value = false;
  }
};

const fetchClasses = async () => {
  try {
    const data = await $fetch('/api/classes');
    classes.value = Array.isArray(data?.data) ? data.data : [];
  } catch (e) {
    console.error('Failed to fetch classes:', e);
  }
};

onMounted(() => {
  fetchUsers();
  fetchClasses();
});

const filteredUsers = computed(() => {
  if (!Array.isArray(users.value)) return [];
  
  return users.value.filter(u => {
    if (!u) return false;
    const name = u.name || '';
    const email = u.email || '';
    const nis = u.nis || '';
    
    const matchesSearch = !searchQuery.value || 
      name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      email.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      nis.toLowerCase().includes(searchQuery.value.toLowerCase());
      
    const matchesRole = !filterRole.value || u.role === filterRole.value;
    return matchesSearch && matchesRole;
  });
});

const form = ref({
  id: null,
  name: '',
  email: '',
  nis: '',
  nisn: '',
  password: '',
  role: 'GURU',
  classId: '',
  isActive: true,
});

const openCreate = () => {
  editMode.value = false;
  form.value = { id: null, name: '', email: '', nis: '', nisn: '', password: '', role: 'GURU', classId: '', isActive: true };
  showModal.value = true;
};

const openEdit = (user) => {
  if (!user) return;
  editMode.value = true;
  form.value = {
    id: user.id,
    name: user.name || '',
    email: user.email || '',
    nis: user.nis || '',
    nisn: user.nisn || '',
    password: '', 
    role: user.role || 'GURU',
    classId: user.classId || '',
    isActive: user.isActive ?? true,
  };
  showModal.value = true;
  activeDropdown.value = null;
};

const saveUser = async () => {
  saving.value = true;
  try {
    const payload = { ...form.value };
    if (!payload.password) delete payload.password;
    if (!payload.email) payload.email = null;
    if (!payload.nis) payload.nis = null;
    if (!payload.nisn) payload.nisn = null;
    if (!payload.classId) payload.classId = null;

    if (editMode.value && form.value.id) {
      await $fetch(`/api/users/${form.value.id}`, { method: 'PUT', body: payload });
    } else {
      await $fetch('/api/users', { method: 'POST', body: payload });
    }

    showModal.value = false;
    $toast.success(editMode.value ? 'User diperbarui' : 'User ditambahkan');
    await fetchUsers();
  } catch (e) {
    const msg = e?.data?.message || e?.message || 'Error';
    $toast.error('Gagal simpan: ' + msg);
  } finally {
    saving.value = false;
  }
};

const deleteUser = async () => {
  if (!deleteId.value) return;
  try {
    await $fetch(`/api/users/${deleteId.value}`, { method: 'DELETE' });
    $toast.success('User dihapus');
    showDeleteModal.value = false;
    await fetchUsers();
  } catch (e) {
    $toast.error('Gagal hapus user');
  }
};

const confirmDelete = (id) => {
  deleteId.value = id;
  showDeleteModal.value = true;
  activeDropdown.value = null;
};

const bentoCard = "bg-base-100 rounded-[1.5rem] md:rounded-[2rem] p-4 md:p-6 border border-base-200/60 shadow-sm transition-all duration-300";
</script>

<template>
  <div class="space-y-4 md:space-y-6 max-w-7xl mx-auto px-4 pb-12 text-left">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 py-4">
      <div>
        <h1 class="text-2xl md:text-3xl font-black text-base-content tracking-tight">Manajemen User</h1>
        <p class="text-sm md:text-base text-base-content/60 mt-1">Kelola akses Admin, Guru, dan Siswa</p>
      </div>
      <div class="flex flex-col sm:flex-row gap-2">
        <div class="flex gap-2 w-full sm:w-auto">
          <NuxtLink to="/siswa/import" class="btn btn-ghost btn-sm md:btn-md border-base-300 rounded-xl md:rounded-2xl gap-2 h-10 md:h-12 flex-1">
            <Icon name="mingcute:user-add-fill" size="18" class="text-primary/60" />
            <span class="text-xs md:text-sm">Bulk Siswa</span>
          </NuxtLink>
          <NuxtLink to="/admin/import-staff" class="btn btn-ghost btn-sm md:btn-md border-base-300 rounded-xl md:rounded-2xl gap-2 h-10 md:h-12 flex-1">
            <Icon name="mingcute:file-import-fill" size="18" class="text-violet-500/60" />
            <span class="text-xs md:text-sm">Bulk Staff</span>
          </NuxtLink>
        </div>
        <button @click="openCreate" class="btn btn-primary btn-sm md:btn-md rounded-xl md:rounded-2xl gap-2 h-10 md:h-12 shadow-lg shadow-primary/20 w-full sm:w-auto">
          <Icon name="mingcute:user-add-fill" size="18" />
          <span class="text-xs md:text-sm">Tambah User</span>
        </button>
      </div>
    </div>

    <!-- Filters -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-3 bg-base-100 p-4 rounded-[1.5rem] md:rounded-[2rem] border border-base-200/60 shadow-sm">
      <div class="md:col-span-2 relative">
        <Icon name="mingcute:search-line" class="absolute left-4 top-1/2 -translate-y-1/2 text-base-content/30" />
        <input 
          v-model="searchQuery" 
          type="text" 
          placeholder="Cari Nama, Email, atau NIS..." 
          autocomplete="off"
          class="input input-bordered w-full pl-11 rounded-xl md:rounded-2xl bg-base-200/30" 
        />
      </div>
      <div>
        <select v-model="filterRole" class="select select-bordered w-full rounded-xl md:rounded-2xl bg-base-200/30">
          <option value="">Semua Role</option>
          <option value="ADMIN">ADMIN</option>
          <option value="GURU">GURU</option>
          <option value="SISWA">SISWA</option>
        </select>
      </div>
      <div class="flex items-center justify-center font-bold text-[10px] md:text-xs text-base-content/40 uppercase tracking-widest">
        Total: {{ filteredUsers.length }} User
      </div>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="flex justify-center py-20">
      <span class="loading loading-spinner loading-lg text-primary opacity-40"></span>
    </div>

    <!-- User List / Table -->
    <div v-else class="space-y-3">
      <!-- Desktop Table -->
      <div :class="[bentoCard, 'hidden md:block p-0 overflow-hidden']">
        <div class="overflow-x-auto max-h-[600px] custom-scrollbar">
          <table class="table table-lg w-full border-separate border-spacing-0">
            <thead class="sticky top-0 z-10 bg-base-100 shadow-sm">
              <tr class="bg-base-200/50 text-base-content/50 uppercase text-[10px] tracking-widest font-black">
                <th class="pl-8 py-4">Pengguna</th>
                <th>Role</th>
                <th>Status</th>
                <th>Email / NIS</th>
                <th class="text-right pr-8">Aksi</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-base-200/40">
              <tr v-for="user in filteredUsers" :key="user.id" class="hover:bg-base-200/30 transition-colors group">
                <td class="pl-8">
                  <div class="flex items-center gap-3 py-1">
                    <div class="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary shrink-0 overflow-hidden border border-primary/5">
                      <img v-if="getAvatar(user)" :src="getAvatar(user)" class="w-full h-full object-cover" />
                      <span v-else class="font-black text-xs">{{ getInitials(user?.name) }}</span>
                    </div>
                    <div class="min-w-0 max-w-[200px]">
                      <p class="font-bold text-base-content truncate">{{ user?.name || 'User' }}</p>
                      <p v-if="user?.role === 'SISWA'" class="text-[10px] font-bold text-base-content/40 uppercase tracking-widest truncate">{{ user.class?.className || 'Tanpa Kelas' }}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <span v-if="user?.role" :class="['px-3 py-1 rounded-lg text-[10px] font-black tracking-widest border', user.role === 'ADMIN' ? 'bg-violet-500/10 text-violet-400 border-violet-500/20' : user.role === 'GURU' ? 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20' : 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20']">
                    {{ user.role }}
                  </span>
                </td>
                <td>
                  <div class="flex items-center gap-1.5">
                    <div :class="['w-2 h-2 rounded-full', user?.isActive ? 'bg-success shadow-[0_0_8px_rgba(34,197,94,0.5)]' : 'bg-base-300']"></div>
                    <span class="text-[10px] font-bold uppercase tracking-widest text-base-content/50">{{ user?.isActive ? 'Aktif' : 'Nonaktif' }}</span>
                  </div>
                </td>
                <td class="text-sm font-medium text-base-content/60">
                  {{ user?.email || user?.nis || user?.nisn || '-' }}
                </td>
                <td class="text-right pr-8">
                  <div class="flex items-center justify-end gap-2">
                    <NuxtLink :to="`/admin/users/detail/${user.id}`" class="btn btn-ghost btn-xs rounded-lg hover:bg-base-200">Detail</NuxtLink>
                    <button @click="openEdit(user)" class="btn btn-ghost btn-xs rounded-lg hover:bg-primary/10 hover:text-primary transition-all">Edit</button>
                    <button @click="confirmDelete(user?.id)" class="btn btn-ghost btn-xs rounded-lg hover:bg-error/10 hover:text-error transition-all">Hapus</button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Mobile List -->
      <div class="md:hidden space-y-3">
        <div v-for="user in filteredUsers" :key="user.id" :class="[bentoCard, 'p-4 border-l-4 !overflow-visible', user?.role === 'ADMIN' ? 'border-l-violet-500' : user?.role === 'GURU' ? 'border-l-indigo-500' : 'border-l-emerald-500']">
          <div v-if="user" class="flex items-start justify-between gap-2">
            <div class="flex items-center gap-3 min-w-0">
              <div class="w-10 h-10 rounded-xl bg-base-200 flex items-center justify-center text-base-content/40 shrink-0 overflow-hidden border border-base-300">
                <img v-if="getAvatar(user)" :src="getAvatar(user)" class="w-full h-full object-cover" />
                <span v-else class="font-black text-xs">{{ getInitials(user?.name) }}</span>
              </div>
              <div class="min-w-0 flex-1">
                <h4 class="font-bold text-base-content truncate">{{ user?.name || 'User' }}</h4>
                <div class="flex items-center flex-wrap gap-2 mt-1">
                   <span class="text-[9px] font-black uppercase tracking-widest px-2 py-0.5 rounded bg-base-200 text-base-content/60">{{ user?.role || 'User' }}</span>
                   <span v-if="user?.role === 'SISWA'" class="text-[9px] font-bold text-primary truncate max-w-[100px]">{{ user.class?.className || 'Tanpa Kelas' }}</span>
                </div>
              </div>
            </div>
            <div class="relative mobile-dropdown shrink-0">
              <button 
                @click.stop="toggleDropdown(user.id)"
                class="btn btn-ghost btn-xs px-1 h-8 w-8 rounded-lg"
              >
                <Icon name="mingcute:more-2-fill" />
              </button>
              
              <div v-if="activeDropdown === user.id" class="absolute right-0 top-full z-[50] mt-1 p-2 shadow-2xl bg-base-100 border border-base-200 rounded-2xl w-40 animate-in fade-in zoom-in duration-200">
                <NuxtLink :to="`/admin/users/detail/${user.id}`" class="w-full flex items-center gap-3 py-3 px-4 font-bold text-xs hover:bg-base-200 rounded-xl transition-colors">
                  <Icon name="mingcute:eye-2-line" class="text-base-content/60" /> Lihat Detail
                </NuxtLink>
                <button @click="openEdit(user)" class="w-full flex items-center gap-3 py-3 px-4 font-bold text-xs hover:bg-base-200 rounded-xl transition-colors">
                  <Icon name="mingcute:edit-2-line" class="text-primary" /> Edit User
                </button>
                <button @click="confirmDelete(user.id)" class="w-full flex items-center gap-3 py-3 px-4 font-bold text-xs text-error hover:bg-error/5 rounded-xl transition-colors text-left">
                  <Icon name="mingcute:delete-2-line" /> Hapus User
                </button>
              </div>
            </div>
          </div>
          <div class="mt-4 flex items-center justify-between border-t border-base-200 pt-3">
             <div class="text-[10px] text-base-content/50 truncate max-w-[150px]">
               {{ user?.email || user?.nis || '-' }}
             </div>
             <div class="flex items-center gap-1.5 shrink-0">
                <div :class="['w-1.5 h-1.5 rounded-full', user?.isActive ? 'bg-success' : 'bg-base-300']"></div>
                <span class="text-[10px] font-bold uppercase tracking-widest text-base-content/40">{{ user?.isActive ? 'AKTIF' : 'NONAKTIF' }}</span>
             </div>
          </div>
        </div>
      </div>

      <div v-if="filteredUsers.length === 0" class="text-center py-20 text-base-content/30 italic bg-base-100 rounded-[2rem] border border-base-200/60">
        Tidak ada data user yang ditemukan
      </div>
    </div>

    <!-- Modals -->
    <dialog :class="['modal modal-bottom sm:modal-middle', showModal ? 'modal-open' : '']">
      <div class="modal-box bg-base-100 border border-base-200 rounded-t-[2.5rem] sm:rounded-[2.5rem] p-6 md:p-8 max-w-lg">
        <h3 class="text-xl md:text-2xl font-black text-base-content mb-6">
          {{ editMode ? 'Edit Pengguna' : 'Tambah Pengguna Baru' }}
        </h3>
        <div class="space-y-4">
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div class="form-control sm:col-span-2">
              <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Nama Lengkap</span></label>
              <input v-model="form.name" type="text" autocomplete="off" placeholder="Nama Lengkap" class="input input-bordered w-full rounded-xl md:rounded-2xl bg-base-200/30" />
            </div>
            <div class="form-control">
              <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Role</span></label>
              <select v-model="form.role" class="select select-bordered w-full rounded-xl md:rounded-2xl bg-base-200/30">
                <option value="ADMIN">ADMIN</option>
                <option value="GURU">GURU</option>
                <option value="SISWA">SISWA</option>
              </select>
            </div>
            <div class="form-control">
              <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Email (Opsional)</span></label>
              <input v-model="form.email" type="email" autocomplete="off" placeholder="email@example.com" class="input input-bordered w-full rounded-xl md:rounded-2xl bg-base-200/30" />
            </div>
          </div>
          <div v-if="form.role === 'SISWA'" class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div class="form-control">
              <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">NISN / NIS</span></label>
              <input v-model="form.nisn" type="text" autocomplete="off" placeholder="NISN/NIS" class="input input-bordered w-full rounded-xl md:rounded-2xl bg-base-200/30" />
            </div>
            <div class="form-control">
              <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Kelas</span></label>
              <select v-model="form.classId" class="select select-bordered w-full rounded-xl md:rounded-2xl bg-base-200/30">
                <option value="">Pilih Kelas</option>
                <option v-for="c in classes" :key="c.id" :value="c.id">{{ c.className }}</option>
              </select>
            </div>
          </div>
          <div v-else class="form-control">
             <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">NIS (Username)</span></label>
             <input v-model="form.nis" type="text" autocomplete="off" placeholder="Nomor Induk Staff" class="input input-bordered w-full rounded-xl md:rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control">
            <label class="label"><span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-40">Password</span></label>
            <input v-model="form.password" type="password" autocomplete="new-password" placeholder="••••••" class="input input-bordered w-full rounded-xl md:rounded-2xl bg-base-200/30" />
          </div>
          <div class="form-control">
            <label class="label cursor-pointer justify-start gap-3 px-1">
              <input v-model="form.isActive" type="checkbox" class="toggle toggle-primary toggle-sm" />
              <span class="label-text font-bold text-[10px] uppercase tracking-widest opacity-60">Status Akun Aktif</span>
            </label>
          </div>
        </div>
        <div class="modal-action mt-8 gap-2">
          <button @click="showModal = false" class="btn btn-ghost rounded-xl md:rounded-2xl px-6 flex-1 sm:flex-none">Batal</button>
          <button @click="saveUser" class="btn btn-primary rounded-xl md:rounded-2xl px-8 shadow-lg shadow-primary/20 flex-1 sm:flex-none" :disabled="saving || !form.name">
            <span v-if="saving" class="loading loading-spinner loading-xs"></span> Simpan
          </button>
        </div>
      </div>
    </dialog>

    <dialog :class="['modal modal-bottom sm:modal-middle', showDeleteModal ? 'modal-open' : '']">
      <div class="modal-box max-w-sm text-center bg-base-100 border border-base-200 rounded-t-[2.5rem] sm:rounded-[2.5rem] p-8">
        <div class="w-16 h-16 rounded-3xl bg-error/10 flex items-center justify-center text-error mx-auto mb-4">
          <Icon name="mingcute:alert-line" size="32" />
        </div>
        <h3 class="text-xl font-black text-base-content">Konfirmasi Hapus</h3>
        <p class="py-4 text-base-content/60 text-sm">Hapus pengguna ini secara permanen?</p>
        <div class="flex gap-2 justify-center mt-2 w-full">
          <button @click="showDeleteModal = false" class="btn btn-ghost rounded-xl md:rounded-2xl flex-1">Batal</button>
          <button @click="deleteUser" class="btn btn-error rounded-xl md:rounded-2xl flex-1">Hapus</button>
        </div>
      </div>
    </dialog>
  </div>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar { width: 4px; height: 4px; }
.custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
.custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(var(--bc), 0.1); border-radius: 10px; }
</style>

// app/(dashboard)/admin/users/page.tsx
'use client';

import React, { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { ColumnDef } from '@tanstack/react-table';
import { toast } from 'sonner';
import api from '@/lib/api';
import { Icon } from '@/components/ui/icon';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { CustomSelect } from '@/components/shared/CustomSelect';
import { DataMasterTableContentSkeleton } from '@/components/shared/DataMasterSkeletons';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'https://gaskan-api.smtijogja.my.id';

const getAvatarUrl = (photoUrl?: string) => {
  if (!photoUrl) return '';
  if (photoUrl.startsWith('http://') || photoUrl.startsWith('https://')) return photoUrl;
  return `${API_BASE}${photoUrl.startsWith('/') ? '' : '/'}${photoUrl}`;
};

export default function UsersManagementPage() {
  const [users, setUsers] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterRole, setFilterRole] = useState('');
  const [pagination, setPagination] = useState({ pageIndex: 0, pageSize: 15 });
  const [totalCount, setTotalCount] = useState(0);

  // Dialog State for Add User
  const [isAddOpen, setIsAddOpen] = useState(false);
  const [form, setForm] = useState({
    name: '',
    email: '',
    username: '',
    nis: '',
    role: 'SISWA',
    password: '',
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const fetchUsers = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({
        page: String(pagination.pageIndex + 1),
        limit: String(pagination.pageSize),
      });
      if (searchQuery) params.set('search', searchQuery);
      if (filterRole) params.set('role', filterRole);

      const res = await api.get(`/users?${params.toString()}`).catch(() => api.get(`/admin?${params.toString()}`));
      const d = res?.data?.data || res?.data;
      if (Array.isArray(d)) {
        setUsers(d);
        if (res.data?.pagination) {
          setTotalCount(res.data.pagination.total);
        } else {
          setTotalCount(d.length);
        }
      }
    } catch (err) {
      console.error(err);
      toast.error('Gagal mengambil daftar pengguna');
    } finally {
      setLoading(false);
    }
  }, [pagination.pageIndex, pagination.pageSize, searchQuery, filterRole]);

  useEffect(() => {
    fetchUsers();
  }, [fetchUsers]);

  const handleCreateUser = async () => {
    if (!form.name || (!form.email && !form.nis && !form.username)) {
      toast.error('Nama dan Username/NIP/Email wajib diisi');
      return;
    }
    setIsSubmitting(true);
    try {
      await api.post('/users', {
        name: form.name,
        email: form.email,
        username: form.username || form.nis,
        nis: form.nis || form.username,
        role: form.role,
        password: form.password || 'smtijogja123',
      });
      toast.success('Pengguna baru berhasil ditambahkan');
      setIsAddOpen(false);
      setForm({ name: '', email: '', username: '', nis: '', role: 'SISWA', password: '' });
      await fetchUsers();
    } catch (err: any) {
      toast.error(err?.response?.data?.message || 'Gagal membuat pengguna baru');
    } finally {
      setIsSubmitting(false);
    }
  };

  const roleBadgeClass = (roleStr: string) => {
    switch ((roleStr || '').toUpperCase()) {
      case 'DEVELOPER':
        return 'bg-purple-500/15 text-purple-500 border-purple-500/30';
      case 'ADMIN':
        return 'bg-rose-500/15 text-rose-500 border-rose-500/30';
      case 'GURU':
        return 'bg-sky-500/15 text-sky-400 border-sky-500/30';
      default:
        return 'bg-emerald-500/15 text-emerald-500 border-emerald-500/30';
    }
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12 animate-in fade-in duration-500">
      {/* Header */}
      <div className="flex flex-col justify-between gap-4 rounded-3xl border border-border bg-card p-4 shadow-sm sm:flex-row sm:items-center sm:p-6">
        <div className="min-w-0">
          <h1 className="flex flex-wrap items-center gap-3 text-2xl font-black tracking-tight text-foreground sm:text-3xl">
            Manajemen Pengguna (User Management)
            <Badge className="bg-primary/15 text-primary border-primary/30 text-xs font-black">
              {totalCount} Total User
            </Badge>
          </h1>
          <p className="text-xs sm:text-sm text-muted-foreground font-semibold mt-0.5">
            Kelola semua akun pengguna sistem (Developer, Admin, Guru, dan Siswa).
          </p>
        </div>

        <div className="grid w-full grid-cols-1 gap-2 min-[420px]:grid-cols-2 sm:flex sm:w-auto sm:items-center">
          <Link href="/admin/import-staff" className="w-full">
            <Button variant="outline" className="h-11 w-full gap-2 rounded-2xl border-border text-xs font-bold">
              <Icon icon="mingcute:upload-3-line" className="text-base text-violet-500" />
              Import Staff Excel
            </Button>
          </Link>

          <Button
            onClick={() => setIsAddOpen(true)}
            className="h-11 w-full gap-2 rounded-2xl bg-primary px-5 text-xs font-black text-primary-foreground"
          >
            <Icon icon="mingcute:add-circle-fill" className="text-lg" />
            Tambah User
          </Button>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="flex flex-col sm:flex-row items-center gap-3 bg-card p-4 rounded-3xl border border-border shadow-sm">
        <div className="relative flex-1 w-full">
          <Icon icon="mingcute:search-line" className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground text-sm" />
          <Input
            type="text"
            placeholder="Cari berdasarkan nama, email, NIS, NIP, atau username..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9 rounded-2xl h-11 bg-muted/30 text-xs font-bold"
          />
        </div>

        <div className="w-full sm:w-48">
          <CustomSelect
            value={filterRole}
            onChange={(val) => setFilterRole(val)}
            placeholder="Semua Role"
            options={[
              { label: 'Semua Role', value: '' },
              { label: 'DEVELOPER', value: 'DEVELOPER' },
              { label: 'ADMIN', value: 'ADMIN' },
              { label: 'GURU', value: 'GURU' },
              { label: 'SISWA', value: 'SISWA' },
            ]}
          />
        </div>
      </div>

      {/* Users Table */}
      {loading ? (
        <DataMasterTableContentSkeleton mobileList />
      ) : (
        <div className="bg-card rounded-3xl border border-border overflow-hidden shadow-sm">
          <div className="divide-y divide-border lg:hidden">
            {users.length === 0 ? (
              <div className="p-10 text-center text-xs font-bold text-muted-foreground">
                Tidak ada pengguna ditemukan.
              </div>
            ) : (
              users.map((u: any) => {
                const avatar = getAvatarUrl(u.photoUrl || u.avatar);
                const userName = u.name || u.nama || 'Pengguna';

                return (
                  <article key={u.id} className="min-w-0 space-y-3 p-4">
                    <div className="flex min-w-0 items-start gap-3">
                      <Avatar className="h-11 w-11 shrink-0 border border-border">
                        <AvatarImage src={avatar} alt={userName} />
                        <AvatarFallback className="bg-primary/10 text-xs font-black text-primary">
                          {userName.charAt(0).toUpperCase()}
                        </AvatarFallback>
                      </Avatar>
                      <div className="min-w-0 flex-1">
                        <p className="break-words text-sm font-bold text-foreground">{userName}</p>
                        <p className="mt-1 break-all font-mono text-xs text-muted-foreground">
                          {u.email || u.nis || u.username || `ID: ${u.id}`}
                        </p>
                      </div>
                      <Badge className={`shrink-0 border text-[9px] font-black ${roleBadgeClass(u.role)}`}>
                        {(u.role || 'SISWA').toUpperCase()}
                      </Badge>
                    </div>
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge variant="outline" className="text-[9px] font-bold">
                        {u.nis || u.username || '-'}
                      </Badge>
                      {u.faceEmbedding ? (
                        <Badge className="border-emerald-500/30 bg-emerald-500/15 text-[9px] text-emerald-500">
                          REGISTERED
                        </Badge>
                      ) : (
                        <Badge className="border-amber-500/30 bg-amber-500/15 text-[9px] text-amber-500">
                          NO FACE
                        </Badge>
                      )}
                    </div>
                    <Link href={`/admin/users/detail/${u.id}`} className="block w-full">
                      <Button variant="outline" className="h-11 w-full rounded-xl text-xs font-bold text-primary">
                        <Icon icon="mingcute:eye-line" className="mr-1 text-sm" />
                        Detail Profil
                      </Button>
                    </Link>
                  </article>
                );
              })
            )}
          </div>

          <div className="hidden max-w-full overflow-x-auto lg:block">
            <table className="w-full text-left text-xs">
              <thead className="bg-muted/50 text-muted-foreground font-black uppercase text-[10px] tracking-wider border-b border-border">
                <tr>
                  <th className="p-4">Pengguna</th>
                  <th className="p-4">Role</th>
                  <th className="p-4">Username / NIS</th>
                  <th className="p-4">Email</th>
                  <th className="p-4">Status Wajah</th>
                  <th className="p-4 text-right">Aksi</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border font-semibold">
                {users.map((u: any) => {
                  const avatar = getAvatarUrl(u.photoUrl || u.avatar);
                  return (
                    <tr key={u.id} className="hover:bg-muted/20 transition-all">
                      <td className="p-4">
                        <div className="flex items-center gap-3">
                          <Avatar className="w-9 h-9 border border-border">
                            <AvatarImage src={avatar} alt={u.name || u.nama} />
                            <AvatarFallback className="font-black bg-primary/10 text-primary text-xs">
                              {(u.name || u.nama || 'U').charAt(0).toUpperCase()}
                            </AvatarFallback>
                          </Avatar>
                          <div>
                            <p className="font-bold text-foreground text-xs">{u.name || u.nama || 'Pengguna'}</p>
                            <p className="text-[10px] text-muted-foreground font-mono">{u.class?.className || 'ID: ' + u.id}</p>
                          </div>
                        </div>
                      </td>
                      <td className="p-4">
                        <Badge className={`text-[9px] font-black border ${roleBadgeClass(u.role)}`}>
                          {(u.role || 'SISWA').toUpperCase()}
                        </Badge>
                      </td>
                      <td className="p-4 font-mono text-foreground">{u.nis || u.username || '-'}</td>
                      <td className="p-4 text-muted-foreground">{u.email || '-'}</td>
                      <td className="p-4">
                        {u.faceEmbedding ? (
                          <Badge className="bg-emerald-500/15 text-emerald-500 border-emerald-500/30 text-[9px]">
                            REGISTERED ✅
                          </Badge>
                        ) : (
                          <Badge className="bg-amber-500/15 text-amber-500 border-amber-500/30 text-[9px]">
                            NO FACE
                          </Badge>
                        )}
                      </td>
                      <td className="p-4 text-right">
                        <Link href={`/admin/users/detail/${u.id}`}>
                          <Button variant="ghost" size="sm" className="rounded-xl text-xs font-bold text-primary gap-1">
                            <Icon icon="mingcute:eye-line" className="text-sm" />
                            Detail Profil
                          </Button>
                        </Link>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Add User Modal */}
      <Dialog open={isAddOpen} onOpenChange={setIsAddOpen}>
        <DialogContent className="max-h-[calc(100dvh-1rem)] overflow-y-auto rounded-3xl p-4 sm:max-w-md sm:p-6">
          <DialogHeader>
            <DialogTitle className="text-lg font-black text-foreground flex items-center gap-2">
              <Icon icon="mingcute:user-add-line" className="text-primary text-xl" />
              Tambah Pengguna Baru
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-3 py-2">
            <div className="space-y-1">
              <label className="text-xs font-bold">Nama Lengkap*</label>
              <Input
                type="text"
                placeholder="Nama..."
                value={form.name}
                onChange={(e) => setForm({ ...form, name: e.target.value })}
                className="rounded-2xl h-10 text-xs font-semibold"
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold">Role Hak Akses*</label>
              <CustomSelect
                value={form.role}
                onChange={(val) => setForm({ ...form, role: val })}
                options={[
                  { label: 'SISWA', value: 'SISWA' },
                  { label: 'GURU', value: 'GURU' },
                  { label: 'ADMIN', value: 'ADMIN' },
                  { label: 'DEVELOPER', value: 'DEVELOPER' },
                ]}
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold">Username / NIS / NIP*</label>
              <Input
                type="text"
                placeholder="Username / NIS..."
                value={form.username}
                onChange={(e) => setForm({ ...form, username: e.target.value, nis: e.target.value })}
                className="rounded-2xl h-10 text-xs font-semibold"
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold">Email</label>
              <Input
                type="email"
                placeholder="user@smtijogja.sch.id"
                value={form.email}
                onChange={(e) => setForm({ ...form, email: e.target.value })}
                className="rounded-2xl h-10 text-xs font-semibold"
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold">Password Default</label>
              <Input
                type="password"
                placeholder="smtijogja123"
                value={form.password}
                onChange={(e) => setForm({ ...form, password: e.target.value })}
                className="rounded-2xl h-10 text-xs font-semibold"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 gap-3 pt-2 min-[420px]:grid-cols-2">
            <Button variant="outline" onClick={() => setIsAddOpen(false)} className="h-11 w-full rounded-2xl text-xs font-bold">
              Batal
            </Button>
            <Button
              onClick={handleCreateUser}
              disabled={isSubmitting}
              className="h-11 w-full rounded-2xl bg-primary px-6 text-xs font-bold text-primary-foreground"
            >
              {isSubmitting ? 'Menyimpan...' : 'Simpan User'}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
